### ISSUE TITLE
Information: Development of "Mobile TCP"

### ISSUE THREAD

**Issue by Technologov** [multipath-tcp/mptcp#103]
Hi all,

I have developed a new Internet Protocol - Five Fields, and as a bonus I have also developed Mobile TCP component, that let's people reconnect to a disconnected session.

It may be complimentary to your work, but take a look.

See draft. spec.
https://www.dropbox.com/s/tnwtsjwav8yxcho/IP-FF-2015-12-09.zip?dl=0

**Comment by cpaasch** [comment]
Not the right forum for such announcments. Please use the mptcp-dev list.
