### ISSUE TITLE
Number of subflows ndiffports

### ISSUE THREAD

**Issue by Raksus** [multipath-tcp/mptcp#105]
Hi,
We are testing the performance of mptcp based in number of subflows in different network environments. When we try to generate a high number of flows with ndiffports as path-manager, the mptcp kernel stops creating flows at 30.
Are there any configuration available at mptcp that allows me to increment this limit?
Why is this happening? 
It was a design decision?

Thx in advance,
Raksus

**Comment by obonaventure** [comment]
Hello,

> We are testing the performance of mptcp based in number of subflows in
> different network environments. When we try to generate a high number of
> flows with ndiffports as path-manager, the mptcp kernel stops creating
> flows at 30.
> Are there any configuration available at mptcp that allows me to
> increment this limit?

No

> Why is this happening?

Because MPTCP uses a 32 bits mask to encode information about the subflows

> It was a design decision?

Yes.

r.withnell@lancaster.ac.uk sent patches to increase that number in the past

OB
