### ISSUE TITLE
Kernel 2.6.35.14 - Patchfile

### ISSUE THREAD

**Issue by rubberduck2006** [multipath-tcp/mptcp#110]
Hello Community,
I would like to use MPTCP with a relatively old kernel (2.6.35.14). Reason: I use a mx.53 based router. Unfortunately, there are no newer kernel which supports this processor.
A patch file would fully satisfy me.
Are there any ideas, suggestions or even workarounds?

Kind regards

Chris

**Comment by obonaventure** [comment]
There are no plans to back port Multipath TCP on 2.6x kernels. The TCP stack has changed too much with the move to 3.x and doing a back port would be very difficult.
