### ISSUE TITLE
My MPTCP Project

### ISSUE THREAD

**Issue by faddat** [multipath-tcp/mptcp#112]
Hi, 

I live in Vietnam where the internet is often quite so-so.  I have 3 fiber connections of varying quality, and I want to use them to connect to a VPN that I'll put on a GCE instance.  I get that the GCE instance has to be running MPTCP, too.  What I do need to know is:

How am I going to get MPTCP onto this?  

![image](https://cloud.githubusercontent.com/assets/7142025/13657062/d3666634-e69e-11e5-800f-6b80d4bb0359.png)

In fact, an additional thought just occured to me-- Am I going to be able to give the LAN ports I'll be re-purposing to WAN pots IP addresses?  Anyway, any help, tips, pointers, etc are greatly appreciated.  The Board is a fully supported in mainline sunxi a20 called lamobo r1.  

Best,

-Jake

**Comment by cpaasch** [comment]
You can check out http://gfdsa.gfdsa.org/2013/05/18/using-2-connections-4/ for a detailled description on how to do something like this.
