### ISSUE TITLE
MPTCP Congestion Control

### ISSUE THREAD

**Issue by GinesGarcia** [multipath-tcp/mptcp#113]
Hi,
i have a doubt related to the default congestion control used by MPTCP. If i install the MPTCP kernel using apt repository, is MPTCP using  the same congestion control used by TCP?

Here is my configuration:
$ cat /proc/sys/net/ipv4/tcp_congestion_control
   cubic
in my case, is using cubic?

thanks in advance

**Comment by cpaasch** [comment]
Seems like the default-congestion control in the debian image is incorrect. Which distro are you using and what exactly is the repository you configured to use?

**Comment by GinesGarcia** [comment]
Hi,
i followed the instructions given in http://multipath-tcp.org/pmwiki.php/Users/AptRepository. i'm using Ubuntu Trusty (14.04) so i have used the link related to this version.

thanks.

**Comment by zorun** [comment]
Hi,

On Archlinux, this is similar:

```
# sysctl net | grep congestion
net.ipv4.tcp_allowed_congestion_control = cubic reno
net.ipv4.tcp_available_congestion_control = cubic reno lia olia wvegas balia
net.ipv4.tcp_congestion_control = cubic
```

The kernel configuration is the following:

```
# CONFIG_DEFAULT_CUBIC is not set
# CONFIG_DEFAULT_LIA is not set
CONFIG_DEFAULT_OLIA=y
# CONFIG_DEFAULT_WVEGAS is not set
# CONFIG_DEFAULT_BALIA is not set
# CONFIG_DEFAULT_RENO is not set
CONFIG_DEFAULT_TCP_CONG="cubic"
```

Should `CONFIG_DEFAULT_TCP_CONG` be changed to olia? What is the purpose of `CONFIG_DEFAULT_OLIA` then?

**Comment by zorun** [comment]
Ah, I see the problem. `DEFAULT_TCP_CONG` is supposed to be set automatically, but olia is missing from its definition: https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/net/ipv4/Kconfig#L704

**Comment by cpaasch** [comment]
Oh, nice catch! Do you want to submit a patch?

**Comment by zorun** [comment]
Sure, I just sent the patch to the mptcp-dev mailing list :)

**Comment by joernschellhaas** [comment]
I'm in the same situation. I did some simulations with MPTCP. So if `proc/sys/net/ipv4/tcp_congestion_control` is `cubic`, does that mean that MPTCP indeed used the CUBIC algorithm?

**Comment by cpaasch** [comment]
Yes

**Comment by joernschellhaas** [comment]
OK, thank you!

**Comment by deshmukhrajvardhan** [comment]
## Aim: Change the Congestion control from cubic to balia

## Setting:
### OS:- 
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
```uname -a```
4.14.24.mptcp #9 SMP Fri Mar 9 19:13:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### MPTCP:- 
```dmesg | grep MPTCP```
[    5.028365] MPTCP: Stable release v0.94.0
```sudo sysctl -a | grep mptcp```
kernel.osrelease = 4.14.24.mptcp
net.mptcp.mptcp_checksum = 1
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 3
net.mptcp.mptcp_version = 0

## MPTCP CONFIG:
```less /boot/config-4.14.24.mptcp```
CONFIG_MPTCP=y
CONFIG_MPTCP_PM_ADVANCED=y
CONFIG_MPTCP_FULLMESH=y
CONFIG_MPTCP_NDIFFPORTS=m
CONFIG_MPTCP_BINDER=m
CONFIG_DEFAULT_FULLMESH=y
CONFIG_DEFAULT_MPTCP_PM="fullmesh"
CONFIG_MPTCP_SCHED_ADVANCED=y
CONFIG_MPTCP_ROUNDROBIN=m
CONFIG_MPTCP_REDUNDANT=m
CONFIG_DEFAULT_SCHEDULER=y
CONFIG_DEFAULT_MPTCP_SCHED="default"
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BIC=m
CONFIG_TCP_CONG_CUBIC=y
CONFIG_TCP_CONG_WESTWOOD=m
CONFIG_TCP_CONG_HTCP=m
CONFIG_TCP_CONG_HSTCP=m
CONFIG_TCP_CONG_HYBLA=m
CONFIG_TCP_CONG_VEGAS=m
CONFIG_TCP_CONG_NV=m
CONFIG_TCP_CONG_SCALABLE=m
CONFIG_TCP_CONG_LP=m
CONFIG_TCP_CONG_VENO=m
CONFIG_TCP_CONG_YEAH=m
CONFIG_TCP_CONG_ILLINOIS=m
CONFIG_TCP_CONG_DCTCP=m
CONFIG_TCP_CONG_CDG=m
CONFIG_TCP_CONG_BBR=m
CONFIG_TCP_CONG_LIA=m
CONFIG_TCP_CONG_OLIA=m
CONFIG_TCP_CONG_WVEGAS=m
CONFIG_TCP_CONG_BALIA=m
CONFIG_DEFAULT_TCP_CONG="cubic"

### MPTCP CC modules: 
```find /lib/modules/$(uname -r) -name "*lia.ko" ```
/lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko
/lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_balia.ko

### MPTCP capable:
```curl http://www.multipath-tcp.org```
Yay, you are MPTCP-capable! You can now rest in peace.

## Problem:
As per [this](https://github.com/multipath-tcp/mptcp/issues/157): 
```sudo modprobe mptcp_balia```
modprobe: ERROR: could not insert 'mptcp_balia': Invalid argument

modprobe: ERROR: could not insert 'mptcp_balia': Invalid argument
### Issue1:
```sysctl net | grep congestion```
net.ipv4.tcp_allowed_congestion_control = cubic reno
net.ipv4.tcp_available_congestion_control = cubic reno
net.ipv4.tcp_congestion_control = cubic

## Any ideas on how to change congestion control are appreciated. Thanks

**Comment by FiratA** [comment]
But MPTCP is using CUBIC not as a coupled congestion control?

**Comment by matttbe** [comment]
MPTCP is using the TCP CC algo that you specify. It is not mandatory to use a coupled one. The coupled ones make sense only if you share the same congested medium for multiple subflows and you want to be "more fare" with the non MPTCP connections.

**Comment by FiratA** [comment]
@matttbe thank you sir.
