### ISSUE TITLE
Getting an Error while trying to install MPTCP kernel

### ISSUE THREAD

**Issue by ashwinraod** [multipath-tcp/mptcp#116]
Hi, I'm trying to install mptcp kernel on ubuntu 14.04. 

I'm encountering following error:

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-mptcp : Depends: linux-headers-3.18.20-90-mptcp but it is not installable
               Depends: linux-image-3.18.20-90-mptcp but it is not installable
N: Ignoring file 'mptcp1.gpg' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
N: Ignoring file 'y-ppa-manager_0.0.9.1-1~getdeb1_all.deb' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to correct problems, you have held broken packages.
I followed instructions on the website: http://multipath-tcp.org/pmwiki.php/Users/AptRepository

Please let me know how to proceed.

Thanks,
Ashwin

**Comment by ashwinraod** [comment]
Is it required that MPTCP needs to be installed only in Virtual Machine?

**Comment by mshary** [comment]
I have it working perfectly fine on Ubuntu 14.04.4 on at least two physical machines (one 32bit and other 64bit). Did you added GPG key correctly? The GPG key file extension is suppose to be ".key" not ".gpg".

Please re-run exactly as given in instructions on page.

Thank you.

**Comment by faddat** [comment]
I've gotten this to work well on 14.04, also.  If you need a further hand, I'm very happy to lend one.  faddat@gmail.com (hangouts, please)
