### ISSUE TITLE
Is this usable on Ubuntu Xenial?

### ISSUE THREAD

**Issue by faddat** [multipath-tcp/mptcp#117]
And by the way-- I am LOVING mptcp!

Thanks for building the future of the net!

**Comment by cpaasch** [comment]
Yes, it should be usable on the latest Ubuntu. Just need to compile and install the kernel :)

**Comment by faddat** [comment]
Thanks!  I've really been enjoying your work :)

**Comment by thusharams** [comment]
@cpaasch @faddat 
I am not sure is this the relevant place to trigger this query but still this thread relates to my issue, Can I find the sources where mptcp patches are merged with Ubuntu Xenial kernel version. I tried applying http://multipath-tcp.org/patches/ on Ubuntu's Xenial but ended up with lot of conflicts. I have also seen there was a release on Ubuntu's Trusty but it seems like didn't continued afterwards.

**Comment by yosephmaloche** [comment]
Hi, I already cloned from the git but I don't know how to Compile and Install in Ubuntu 16.04. The automatic option is not working. Can you help me, please?
