### ISSUE TITLE
Replicate sockopt IP_TOS over whole sockets cluster after MPTCP connection establishment

### ISSUE THREAD

**Issue by mwetterw** [multipath-tcp/mptcp#118]
Hello,
At OVH for OverTheBox, we noticed (at least for the sockopt IP_TOS) that it is not replicated over the whole sockets cluster, when setsockopt is called **after** MPTCP connection establishment.
(But it works fine when the setsockopt is called before connection establishment.)

Is there a quick fix for this issue?
Regards,
Martin

**Comment by mwetterw** [comment]
Link with #9 ?

**Comment by sduponch** [comment]
diff --git a/net/ipv4/ip_sockglue.c b/net/ipv4/ip_sockglue.c
index 4cd78d3..59bc1b2 100644
--- a/net/ipv4/ip_sockglue.c
+++ b/net/ipv4/ip_sockglue.c
@@ -42,6 +42,8 @@
 #endif
 #include <net/ip_fib.h>
 
+#include <net/mptcp.h>
+
 #include <linux/errqueue.h>
 #include <asm/uaccess.h>
 
@@ -606,6 +608,22 @@ static int do_ip_setsockopt(struct sock *sk, int level,
			sk->sk_priority = rt_tos2priority(val);
 			sk_dst_reset(sk);
 		}
+ 		// Update TOS on mptcp subflow
+		if (is_meta_sk(sk)) {
+			struct sock *sk_it, *tmpsk;
+			mptcp_for_each_sk_safe(tcp_sk(sk)->mpcb, sk_it, tmpsk) {
+				if (tcp_sk(sk_it)->closing || tcp_sk(sk_it)->send_mp_fclose)
+					continue;
+				//mptcp_sub_inherit_sockopts(sk, sk_it)
+				{
+					if (inet_sk(sk_it)->tos != inet_sk(sk)->tos) {
+						inet_sk(sk_it)->tos = inet_sk(sk)->tos;
+						sk_it->sk_priority = sk->sk_priority;
+						sk_dst_reset(sk_it);
+					}
+				}
+			}
+		}
 		break;
 	case IP_TTL:
 		if (optlen < 1)

**Comment by sduponch** [comment]
`
diff --git a/net/ipv4/ip_sockglue.c b/net/ipv4/ip_sockglue.c
index 4cd78d3..59bc1b2 100644
--- a/net/ipv4/ip_sockglue.c
+++ b/net/ipv4/ip_sockglue.c
@@ -42,6 +42,8 @@
 #endif
 #include <net/ip_fib.h>
 
+#include <net/mptcp.h>
+
 #include <linux/errqueue.h>
 #include <asm/uaccess.h>
 
@@ -606,6 +608,22 @@ static int do_ip_setsockopt(struct sock *sk, int level,
			sk->sk_priority = rt_tos2priority(val);
 			sk_dst_reset(sk);
 		}
+ 		// Update TOS on mptcp subflow
+		if (is_meta_sk(sk)) {
+			struct sock *sk_it, *tmpsk;
+			mptcp_for_each_sk_safe(tcp_sk(sk)->mpcb, sk_it, tmpsk) {
+				if (tcp_sk(sk_it)->closing || tcp_sk(sk_it)->send_mp_fclose)
+					continue;
+				//mptcp_sub_inherit_sockopts(sk, sk_it)
+				{
+					if (inet_sk(sk_it)->tos != inet_sk(sk)->tos) {
+						inet_sk(sk_it)->tos = inet_sk(sk)->tos;
+						sk_it->sk_priority = sk->sk_priority;
+						sk_dst_reset(sk_it);
+					}
+				}
+			}
+		}
 		break;
 	case IP_TTL:
 		if (optlen < 1)
`

**Comment by sduponch** [comment]
```
diff --git a/net/ipv4/ip_sockglue.c b/net/ipv4/ip_sockglue.c
index 4cd78d3..59bc1b2 100644
--- a/net/ipv4/ip_sockglue.c
+++ b/net/ipv4/ip_sockglue.c
@@ -42,6 +42,8 @@
 #endif
 #include <net/ip_fib.h>

+#include <net/mptcp.h>
+
 #include <linux/errqueue.h>
 #include <asm/uaccess.h>

@@ -606,6 +608,22 @@ static int do_ip_setsockopt(struct sock *sk, int level,
            sk->sk_priority = rt_tos2priority(val);
            sk_dst_reset(sk);
        }
+       // Update TOS on mptcp subflow
+       if (is_meta_sk(sk)) {
+           struct sock *sk_it, *tmpsk;
+           mptcp_for_each_sk_safe(tcp_sk(sk)->mpcb, sk_it, tmpsk) {
+               if (tcp_sk(sk_it)->closing || tcp_sk(sk_it)->send_mp_fclose)
+                   continue;
+               //mptcp_sub_inherit_sockopts(sk, sk_it)
+               {
+                   if (inet_sk(sk_it)->tos != inet_sk(sk)->tos) {
+                       inet_sk(sk_it)->tos = inet_sk(sk)->tos;
+                       sk_it->sk_priority = sk->sk_priority;
+                       sk_dst_reset(sk_it);
+                   }
+               }
+           }
+       }
        break;
    case IP_TTL:
        if (optlen < 1)
```

**Comment by mwetterw** [comment]
Link with PR #124

**Comment by cpaasch** [comment]
Closing, as the pull-request is taking care of this.
