### ISSUE TITLE
Question about reordering

### ISSUE THREAD

**Issue by T0mek** [multipath-tcp/mptcp#119]
Hi All,

Does the MPTCP have special protection against packet reordering? Does this work better than in the regular TCP protocol?

I have to transmit a video stream between two hosts, the network conditions can be very bad and packets can be received in bursts and moreover in wrong order.
Although I am using TCP protocol (instead of UDP) the video receiver complains about reordered packets.

I just wonder whether installing MPTCP on both hosts could remove (or at least reduce) the packet reordering.
Will it work for two hosts with only single network interfaces and with single connection path between them?

I will appreciate any suggestions.
Regards,
Tomek

**Comment by obonaventure** [comment]
MPTCP includes two levels of sequence numbers. This provides additional protection against packet injection attacks, but concerning normal reordering it should not behave better than regular TCP. If you use different subflows, then it is likely that there will be more reordering (but it will be hidden by MPTCP to the applications). I'm surprised that you report reordering with regular TCP.

**Comment by T0mek** [comment]
Thank you for explanation.
I also expected that there will be no reordering when using TCP.
I will check again settings of the video receiver.

Tomek
