### ISSUE TITLE
+ sign while compiling kernel from source

### ISSUE THREAD

**Issue by Speedy1991** [multipath-tcp/mptcp#120]
I am not sure if its realy a bug, but i followed the instructions from your site here:
http://multipath-tcp.org/pmwiki.php/Users/DoItYourself
and
https://wiki.ubuntuusers.de/Kernel/Kompilierung/

My Steps:

git clone --depth=1 git://github.com/multipath-tcp/mptcp.git

cd mptcp

make defconfig

make nconfig (Enable MPTPC with all subselections)

make-kpkg --initrd buildpackage 

That leads to:

make[2]: Entering directory `/home/ubuntu/mptcp-bak/mptcp'    
The changelog says we are creating 3.18.26+    
However, I thought the version is 3.18.26    
exit 4    
make[2]: *** [sanity_check] Error 4    
make[2]: Leaving directory`/home/ubuntu/mptcp-bak/mptcp'  
make[1]: **\* [debian/stamp/do-pre-build-arch] Error 2  
make[1]: Leaving directory `/home/ubuntu/mptcp-bak/mptcp'  
dpkg-buildpackage: error: debian/rules build gave error exit status 2  
make: **\* [debian/stamp/build/buildpackage] Error 2    

After renameing the .git to e.g. .gitdisabled the build is running fine.

I'm compiling on a Ubuntu-Server 14.04 LTS in VirtualBox, fresh installed with newest updates.

**Comment by cpaasch** [comment]
Yes, seems like you are not the only one reporting this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=588178

Another workaround for you would be to tag the HEAD of your git repo.
