### ISSUE TITLE
performance issue on multi-connections

### ISSUE THREAD

**Issue by tryhslee** [multipath-tcp/mptcp#121]
Dear all,
I have performance issue on multi-connections.
As growing connection numbers, the performance decreased.
We use 10G bps interfaces, but when I got the 1000 clients, the MPTCP performance is only 3.4 Gbps.
I'm not sure what the problem is.

1.version : MPTCP 0.90
2.used program : iperf
3. interface bandwidth : 10G bps
4. performance result.
[1 connection]
TCP : 7.6 Gbps
MPTCP : 7.1 Gbps

[100 connections]
TCP : 8.5 Gbps
MPTCP : 7.2 Gbps

[1000 connections]
TCP : 5.9 Gbps
MPTCP : 3.4 Gbps
1. command that I used
   1) iperf -s
   2) iperf -c hostip

Please give me the idea whtat the problem is.

**Comment by cpaasch** [comment]
Have you disabled DSS-checksumming (`sysctl -w net.mptcp.mptcp_checksum=0`) ?

How many interfaces do you have? You should try to make sure that MPTCP is not creating cross-subflows.

**Comment by GinesGarcia** [comment]
Hi,
@cpaasch is right, you have to avoid cross-subflows in order to get the maximun performance, redirecting each flow over a different interface.

**Comment by cpaasch** [comment]
Closing. Please reopen or ask on mptcp-dev if the issue is still there.
