### ISSUE TITLE
MPTCP drops a sub-flow in between data transmission

### ISSUE THREAD

**Issue by cyriac83** [multipath-tcp/mptcp#123]
Hello,

I am encountering a strange behaviour while experimenting with MPTCP. I am using  MPTCP v0.90-release (for linux). In my experiment setup, there are two machines, connected to each other over wifi link (wifi router in between) and an ethernet link (ethernet switch in between). Upon transmitting data, two sub-flows are created, one over wifi and other over ethernet link. In this scenario, MPTCP is observed to drop sub flow over wifi at times. This is more pronounced when an additional delay of 3 - 5ms is added to the wifi interface at one of the machine (this means an additional RTT of 3 - 5 ms over wifi link). Later, MPTCP sometimes (not always) re-establishes the connection over wifi. 

Note: While going through the packet trace, lots of duplicate ACKs are seen on the wifi path. Does MPTCP disconnects a sub-flow if it sees lots of duplicate ACKS in that path?

Thanks!
James

**Comment by cpaasch** [comment]
Discussed on the mailing-list.
