### ISSUE TITLE
MPTCP not fully utilizing paths

### ISSUE THREAD

**Issue by moshfequr** [multipath-tcp/mptcp#125]
Hi

i have 2 ubuntu server with mptcp version 0.90. Both are connecting via two 1Gb/s links. Buffersize and mtu size are default value. If i reduce the link capacity to 100Mb/s, then i can get 180-190Mb/s throughput. Both links are fully utilized. But i use 1Gb/s links, i am getting 900Mb/s throughput, instead of close to 2Gb/s. What should i change? i have increased the buffersize but didn't work.

Thanks

**Comment by cpaasch** [comment]
Disable DSS-checksumming: `sysctl -w net.mptcp.mptcp_checksum=0`. On both, client and server.

**Comment by moshfequr** [comment]
Thanks a lot!
