### ISSUE TITLE
Docker and MPTCP Kernel

### ISSUE THREAD

**Issue by GinesGarcia** [multipath-tcp/mptcp#127]
Hi,
i'm trying to run dockers with MPTCP kernel. "aufs"module is required and is not included at the mptcp-kernel, so, how can I properly include this module in the mptcp-kernel?

Thanks.

**EDIT:** I tried to apply patches over the mptcp kernel, but when i try to apply kbuild patch, i got the following errors:

$ patch -p1 < aufs4-kbuild.patch 
patching file fs/Kconfig
Hunk #1 FAILED at 218.
1 out of 1 hunk FAILED -- saving rejects to file fs/Kconfig.rej
patching file fs/Makefile
patching file include/uapi/linux/Kbuild
Hunk #1 FAILED at 58.
1 out of 1 hunk FAILED -- saving rejects to file include/uapi/linux/Kbuild.rej

Thanks in advance.

**Comment by cpaasch** [comment]
You will have to take a look at the rejects-file and fix eventual merge-conflicts.

**Comment by GinesGarcia** [comment]
Thanks a lot!!
