### ISSUE TITLE
Problem in debian apt repository

### ISSUE THREAD

**Issue by paketecuento** [multipath-tcp/mptcp#129]
I followed the instructions in http://multipath-tcp.org/pmwiki.php/Users/AptRepository but cannot install anything because of the following error

```
root@debian:/etc/apt/sources.list.d# apt-get update
Obj http://multipath-tcp.org jessie InRelease
W: Failed to fetch http://multipath-tcp.org/repos/apt/debian/dists/jessie/InRelease  Unable to find expected entry «main/binary-armhf/Packages» in «Release» file (Wrong sources.list entry or malformed file)
```

Thanks to [this entry](http://www.omgubuntu.co.uk/2016/03/fix-failed-to-fetch-google-chrome-apt-error-ubuntu) I solved with

`deb [arch=i386] http://multipath-tcp.org/repos/apt/debian jessie main`

**Comment by cpaasch** [comment]
Thanks, added a note on https://multipath-tcp.org/pmwiki.php/Users/AptRepository
