### ISSUE TITLE
abnormal mptcp throughput combined lte + wifi

### ISSUE THREAD

**Issue by strongKennyLee** [multipath-tcp/mptcp#131]
While developing on MPTCP, I got stuck on throughput problem.
LTE only throughput shows 100Mbps, and WiFi only throughput is 100M. But when I combined lte and wifi at the same time, the throughput was about 70Mbps, lte was 69Mbps and wifi was 1Mbps. I expected the throughput would be over 170~190Mbps. I don’t know why the throughput is too low and wifi speed decreased too much. I set up mptcp checksum is disabled, though. Please let me know what I should do to get a normal performance.
Here is my device environment
Linux kernel version: 3.17.0
MPTCP version: 0.89.5  
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.2.251   0.0.0.0         UG    0      0        0 lte
10.0.0.0        \*               255.255.255.0   U     0      0        0 mlan0
192.168.1.0     \*               255.255.255.0   U     0      0        0 br0
192.168.2.0     \*               255.255.255.0   U     0      0        0 lte

mlan0 interface is for wifi station mode. my device has one lte interface and two wifi interface, uap0(for AP) and mlan0 (for STA). wifi packets comes from another AP connected to mlan0 and a laptop pc to measure the throughput is connected to uap0

**Comment by cpaasch** [comment]
Please update to a more recent MPTCP version.
