### ISSUE TITLE
Missing mptcp_enabled

### ISSUE THREAD

**Issue by cjsakfh89** [multipath-tcp/mptcp#132]
Hi

Got the below Errors while installing MPTCP on CentOS 32bit machine

[root@centos7 mptcp-mptcp_v0.91]# sysctl -a | grep mptcp_enabled
[root@centos7 mptcp-mptcp_v0.91]# sysctl -w net.mptcp.mptcp_enabled=1
sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or directory

I already reboot server but /proc/sys/net/mptcp directory does not appear.
There are server info.. and
Can you please help me to resolve this issue

[root@centos7 mptcp-mptcp_v0.91]# uname -r
3.18.8-201.mptcp.el7.centos.x86_64
[root@centos7 mptcp-mptcp_v0.91]# rpm -qa | grep kernel | grep mptcp
kernel-modules-extra-3.18.8-201.mptcp.el7.centos.x86_64
kernel-core-3.18.8-201.mptcp.el7.centos.x86_64
kernel-tools-3.18.8-201.mptcp.el7.centos.x86_64
kernel-devel-3.18.8-201.mptcp.el7.centos.x86_64
kernel-headers-3.18.8-201.mptcp.el7.centos.x86_64
kernel-debuginfo-common-x86_64-3.18.8-201.mptcp.el7.centos.x86_64
kernel-modules-3.18.8-201.mptcp.el7.centos.x86_64
kernel-tools-libs-3.18.8-201.mptcp.el7.centos.x86_64
kernel-debuginfo-3.18.8-201.mptcp.el7.centos.x86_64
kernel-3.18.8-201.mptcp.el7.centos.x86_64

Thanks
Maro, Cheon

**Comment by cpaasch** [comment]
How did you generate the centos-packages? Where are they coming from? Looks like MPTCP is not enabled in the kernel's config-file.

**Comment by cjsakfh89** [comment]
I got this kernel package file from pre-compiled images by Kenjiro Nakayama that shown Linux distributions of MPTCP main page.
Git : https://gist.github.com/nak3/99a9a782548a8cab5122
Image : http://copr-be.cloud.fedoraproject.org/results/kenjiro/mptcp-kernel/epel-7-x86_64/00159631-kernel/
Is that not proper image for MPTCP?

**Comment by cpaasch** [comment]
I see. I checked the kernel-config of this package and it doesn't have MPTCP enabled.

**Comment by cpaasch** [comment]
Closing this and checking with Kenjiro directly.
