### ISSUE TITLE
Static code issue OVERRUN 

### ISSUE THREAD

**Issue by madhanraj** [multipath-tcp/mptcp#140]
Hi , 
While running the prevent , got the following issue 

tcp_ipv4.c 

Issue Line: memset((char *)&tp->tk_table + sizeof(tp->tk_table), 0, size);

Issue: 

CID 32749 (#1 of 1): Out-of-bounds access (OVERRUN)1. overrun-buffer-val: Overrunning struct type hlist_nulls_node of 16 bytes by passing it to a function which accesses it at byte offset 16. [Note: The source code implementation of the function has been overridden by a builtin model.]

tcp_ipv6.c 

Issue Line: memset((char *)&tp->tk_table + sizeof(tp->tk_table), 0, size_tk_table);

Issue:

CID 32747 (#1 of 1): Out-of-bounds access (OVERRUN)1. overrun-buffer-val: Overrunning struct type hlist_nulls_node of 16 bytes by passing it to a function which accesses it at byte offset 16. [Note: The source code implementation of the function has been overridden by a builtin model.]

**Comment by cpaasch** [comment]
Hello!

What tool are you using for the static code analysis? (so I can integrate it into my workflow)

Christoph

**Comment by madhanraj** [comment]
I am using prevent tool . 
 P.S : it is not reported in the SVACE . However it looks like it needs a fix

**Comment by cpaasch** [comment]
This looks more like a false positive to me, because `hlist_nulls_node` is part of the `tcp_sock`. So, there shouldn't be an overrun. We are basically memset'ing the memory after the `hlist_nulls_node`.

**Comment by cpaasch** [comment]
Closing. Please reopen if my analysis is wrong and it indeed is a bug.
