### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by madhanraj** [multipath-tcp/mptcp#141]
CID 32801 (#1 of 1): Resource leak (RESOURCE_LEAK)
9. leaked_storage: Variable mptcp_local going out of scope leaks the storage it points to.

```
    **return 0;**
```

err_seq_fops:

```
    kfree(mptcp_local);
```

err_mptcp_local:

```
    kfree(fm_ns);

    return err;
```

}

mptcp_local has possibility that it is not released properly

**Comment by madhanraj** [comment]
in file 
mptcp_fullmesh.c

**Comment by cpaasch** [comment]
This is again a false positive (at least, from what I see). Please correct me if I'm wrong.

I guess the tool is reporting the code-flow where we `goto err_mptcp_local;`, right? In that case mptcp_local has not been allocated so there is no resource leak.

**Comment by madhanraj** [comment]
the error is in  
return 0;

this looks like bug cause mptcp_local is allocated successfully but not released .
i.e no error in fops and kzalloc

**Comment by cpaasch** [comment]
But, the code assigns `mptcp_local` to `fm_ns->local`, and `fm_ns` is assigned to `net->mptcp.path_managers`. So, there shouldn't be a resource-leak:

```
        rcu_assign_pointer(fm_ns->local, mptcp_local);
        INIT_DELAYED_WORK(&fm_ns->address_worker, mptcp_address_worker);
        INIT_LIST_HEAD(&fm_ns->events);
        spin_lock_init(&fm_ns->local_lock);
        fm_ns->net = net;
        net->mptcp.path_managers[MPTCP_PM_FULLMESH] = fm_ns;
```

Can you show us the full output of Coverity and what code-flow it says is buggy? (normally, Coverity shows which branches it had to take to trigger the resource-leak.

**Comment by madhanraj** [comment]
//1. Condition !fm_ns, taking false branch.
        if (!fm_ns)
                return -ENOBUFS;

//2. alloc_fn: Storage is returned from allocation function kzalloc. [show details]
//3. var_assign: Assigning: mptcp_local = storage returned from kzalloc(232UL, 208U).
        mptcp_local = kzalloc(sizeof(*mptcp_local), GFP_KERNEL);
//4. Condition !mptcp_local, taking false branch.
        if (!mptcp_local) {
                err = -ENOBUFS;
                goto err_mptcp_local;
        }

//5. Condition !proc_create("mptcp_fullmesh", 292 /\* (0x100 | 0x20) | 4 */, net->proc_net, &mptcp_fm_seq_fops), taking false branch.
        if (!proc_create("mptcp_fullmesh", S_IRUGO, net->proc_net,
                         &mptcp_fm_seq_fops)) {
                err = -ENOMEM;
                goto err_seq_fops;
        }

```
    mptcp_local->next_v4_index = 1;
```

//6. Condition __cond, taking false branch.
//7. Switch case value 8UL.
//8. Breaking from switch.
        rcu_assign_pointer(fm_ns->local, mptcp_local);
        INIT_DELAYED_WORK(&fm_ns->address_worker, mptcp_address_worker);
        INIT_LIST_HEAD(&fm_ns->events);
        spin_lock_init(&fm_ns->local_lock);
        fm_ns->net = net;
        net->mptcp.path_managers[MPTCP_PM_FULLMESH] = fm_ns;

//9. leaked_storage: Variable mptcp_local going out of scope leaks the storage it points to.
        return 0;

**Comment by cpaasch** [comment]
Ok, it seems like you are compiling for arm64. Are you sure that Coverity understands the arm64 instruction set?

Because, it seems like Coverity goes into `case 8` and doesn't understand the stlr:

```
#define smp_store_release(p, v)                                         \
do {                                                                    \
        compiletime_assert_atomic_type(*p);                             \
        switch (sizeof(*p)) {                                           \
        case 1:                                                         \
                asm volatile ("stlrb %w1, %0"                           \
                                : "=Q" (*p) : "r" (v) : "memory");      \
                break;                                                  \
        case 2:                                                         \
                asm volatile ("stlrh %w1, %0"                           \
                                : "=Q" (*p) : "r" (v) : "memory");      \
                break;                                                  \
        case 4:                                                         \
                asm volatile ("stlr %w1, %0"                            \
                                : "=Q" (*p) : "r" (v) : "memory");      \
                break;                                                  \
        case 8:                                                         \
                asm volatile ("stlr %1, %0"                             \
                                : "=Q" (*p) : "r" (v) : "memory");      \
                break;                                                  \
        }                                                               \
} while (0)
```

**Comment by madhanraj** [comment]
yup I am compiling for arm64 .. I am not quite sure if prevent understands arm64 .. but for other similar rcu cases there is no error throwen

**Comment by cpaasch** [comment]
I'm pretty sure that there is no bug here in this code. I don't see where there is a missing `kfree()`. IMO, Coverity does not handle this here correctly.
