### ISSUE TITLE
can't configure MPTCP

### ISSUE THREAD

**Issue by delinage** [multipath-tcp/mptcp#142]
I installed MPTCP on Ubuntu 16.04 LTS:

```
Satellite-Pro-C660:~$ sudo apt-get install linux-mptcp 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-mptcp is already the newest version (20160810215640).
0 upgraded, 0 newly installed, 0 to remove and 208 not upgraded.
```

I rebooted my computer and then when I tried to configure it, I encountered this problem:

```
Satellite-Pro-C660:~$ sysctl -w net.mptcp.mptcp_enabled=1
sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or directory
```

I don't know what I'm supposed to do to fix it (I'm willing to change my O.S. if that's the issue).
Thank you in advance for your time.

**Comment by matttbe** [comment]
Hi @delinage,

Can you check you booted on the right kernel?

```
uname -a
```

You should see "mptcp" somewhere. If the problem is that, you can fix it by choosing the kernel you want to use at startup: https://help.ubuntu.com/community/Grub2

> Hold down (right) SHIFT to display the menu during boot

**Comment by delinage** [comment]
That was it.

Thank you so much for your quick and accurate answer!

**Comment by crn1986** [comment]
can't configure mptcp on fedora 20. getting the following error. please help me in fixing this.
[root@localhost ~]# sysctl -w net.mptcp.mptcp_enabled=1
sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or directory

**Comment by matttbe** [comment]
On December 12, 2017 6:56:47 AM GMT, crn1986 <notifications@github.com> wrote:
>can't configure mptcp on fedora 20. getting the following error. please
>help me in fixing this.
>[root@localhost ~]# sysctl -w net.mptcp.mptcp_enabled=1
>sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or
>directory
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/multipath-tcp/mptcp/issues/142#issuecomment-350962020

Hi,
It means you didn't boot on a kernel supporting MPTCP. Check your GRUB config.
Matt
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 

------------------------------
DISCLAIMER.
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.
