### ISSUE TITLE
Issues with servers

### ISSUE THREAD

**Issue by delinage** [multipath-tcp/mptcp#143]
I've installed mptcp, and when I try on "http://amiusingmptcp.de/" it says I'm using it on most ports (No MPTCP on 80, yes MPTCP on 5900, yes MPTCP on 8080) and I have a couple of issues:

1.- I try "iperf -c multipath-tcp.org" and I get: "connect failed: Connection timed out".

2.- I try "ifstat" and I open multipath-tcp.org I can see both interfaces downloading data, but if I just download something in "multipath-tcp.org/snapshots/" I only download data on the main flow.

3.- I want to create an MPTCP server, how should I do it considering multipath-tcp uses multiple subflows? Because if I use "iperf -s" then I'll have to use "Iperf -c _address_" and I will write just an address when I want to connect to both server addresses, not just one.

Thank you so much.

**Comment by matttbe** [comment]
Hi,

> I've installed mptcp, and when I try on "http://amiusingmptcp.de/" it says I'm using it on most ports (No MPTCP on 80, yes MPTCP on 5900, yes MPTCP on 8080)

It seems a middlebox is blocking MPTCP on the port 80. You can have the confirmation using Tracebox.

> 1.- I try "iperf -c multipath-tcp.org" and I get: "connect failed: Connection timed out".

It seems IPerf server is no longer reachable.
@obonaventure: is it normal?

> 2.- I try "ifstat" and I open multipath-tcp.org I can see both interfaces downloading data, but if I just download something in "multipath-tcp.org/snapshots/" I only download data on the main flow.

I guess the middlebox is not blocking port 443 (https://multipath-tcp.org), it makes sense. But "snapshots" should also only be available only via the port 443. Are you using the same tools? Maybe one is using a proxy/another port and not the other one?

> 3.- I want to create an MPTCP server, how should I do it considering multipath-tcp uses multiple subflows? Because if I use "iperf -s" then I'll have to use "Iperf -c address" and I will write just an address when I want to connect to both server addresses, not just one.

You only have to connect to one address. Then several subflows will be created depending of the Path Manager you have selected, e.g. if on your client with two IP addresses you have the Fullmesh Path Manager and on your server you have selected the Default Path Manager, then the client will try to establish two subflows with its two different IP to the single IP address of the server that it knows. See https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP for more details.

**Comment by delinage** [comment]
> It seems a middlebox is blocking MPTCP on the port 80. You can have the confirmation using Tracebox.

 I think both 80 and 433 ports are being blocked now... Because I only get download data in both subflows in amiusingmptcp.de (I think it's because it uses the port 8080). I will try to install Tracebox and confirm it later.

> It seems IPerf server is no longer reachable.

I can't either connect to ftp://ftp.multipath-tcp.org... I guess it's the same issue.

> You only have to connect to one address...

Oh, so I can just use iperf -s and iperf -c and I will get a mptcp connection traceable with wireshark or another tools? is there any special recoomendation?

Thank you for everything.

**Comment by matttbe** [comment]
> I can't either connect to ftp://ftp.multipath-tcp.org... I guess it's the same issue.

Me neither. I guess so.

> Oh, so I can just use iperf -s and iperf -c and I will get a mptcp connection traceable with wireshark or another tools? is there any special recoomendation?

Yes, you only have to set a non-default Path Manager for the client and/or the server.

I am closing this issue as all questions have been answered. Feel free to re-open it if it is not the case.

**Comment by cpaasch** [comment]
FYI, I remove the note about iperf on https://multipath-tcp.org/pmwiki.php/Users/UseMPTCP until iperf is running again on this server.

**Comment by obonaventure** [comment]
We'll try to setup another on iperf.multipath-tcp.org
