### ISSUE TITLE
Socket options are not copied to subflows

### ISSUE THREAD

**Issue by jnevens** [multipath-tcp/mptcp#147]
If a mark is set on the tcp socket that is opened (with setsockopt SOL_SOCKET SO_MARK), only the `main` tcp stream has the mark set, the subflows do not have that mark set anymore.

**Comment by matttbe** [comment]
Hello @jnevens 

Only a subset of the socket options are inherit: https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.91/net/mptcp/mptcp_ctrl.c#L935

I guess it makes sense to also inherit the marks for the firewall (or routing?). @cpaasch: what do you think about that?

**Comment by cpaasch** [comment]
Yes, we should fix that.

**Comment by matttbe** [comment]
@jnevens: feel free to test this small patch: https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2016-11/msg00005.html

**Comment by jnevens** [comment]
Yes, this patch definitely fixes my routing issue!

**Comment by matttbe** [comment]
Great! Closing this issue then.
