### ISSUE TITLE
I can't use multiple subflows properly 

### ISSUE THREAD

**Issue by delinage** [multipath-tcp/mptcp#148]
So… I have a problem/question. I’m going to try to give all the information needed, but if I miss something, please tell me.

I have 2 computers (one is “server” and the other one is “client”) with mptcp installed (also tools).
I have configured the routing tables (and added the scripts mptcp_up and mptcp_down, because I’m using ubuntu 16.04 LTS).

When I check “amiusing mptcp.de” I get a positive result, I get I’m using 2 subflows to connect on certain ports. (5900 and 8080 with scheduler default)

Everything seems normal but… 
1. If I use ifstat while surfing on amiusingmptcp.de I get I’m using a lot one interface but nearly nothing the other one (I thought this was normal, so I didn’t worry) (I’m using fullmesh in both computers).
2. If I try to make a connection between the computers, using ipref, it seems I’m only using 1 subflow (I’ve checked netstat and wireshark) because the second ones don’t connect.
   So, I don’t know where the mistake is, and I would appreciate the help.

Images: 
-Client: (it looks like it tries to connect the other subflow but it can't)

![client1](https://i.imgsafe.org/32485d3660.png)

![client2](https://i.imgsafe.org/324e820626.png)

-Server: 

![server](https://i.imgsafe.org/32551662a6.png)

PS:
Client:
10.102.81.138 (it's the one used to connect with server)
192.168.10.158 (it's the other one /30)
Server:
10.102.81.130 (it's the one I use to connect)
192.168.0.122

Thanks in advance.

**Comment by cpaasch** [comment]
@delinage, you closed, reopened, closed the issue. So, I guess you managed to fix it?

**Comment by delinage** [comment]
Yes, sorry. I'm trying something different, I'll reopen if it doesn't work.
Sorry for the inconvenience.
