### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by delinage** [multipath-tcp/mptcp#151]
I wanted to live stream + vod on mptcp and I thought on VLC, but it seems it's not working (it only connects one subflow).

Can't I use VLC for streaming? Wasn't mptcp supposed to work on these applications if the server and the client work with mptcp? There's another way you know to live stream+vod on mptcp?

Thanks in advance

**Comment by cpaasch** [comment]
It should just work. Are you sure that the server supports MPTCP?

**Comment by cpaasch** [comment]
Closing.
