### ISSUE TITLE
How can I install MPTCP in ubuntu 16.04 or Resolve this problem in 14.04? 

### ISSUE THREAD

**Issue by EricSotillo** [multipath-tcp/mptcp#152]
Hello, i want to know how can i install MPTCP in ubuntu 16.04.
I had a problem install in Ubuntu 14.04, I'll upload a image to my issue, How can I repeared this ? 
or how can install MPTCP in ubuntu 16.04, it's the same for my, i only want install v.90 in my computer. 

![15045353_10210663493565609_928836411_o](https://cloud.githubusercontent.com/assets/22304200/20243309/4ded9fee-a931-11e6-8ee7-e4438620bffb.png)

I followed Older Releases: http://multipath-tcp.org/pmwiki.php/Users/AptRepository

**Comment by cpaasch** [comment]
It should be possible to install it. Unfortunately the logs you show are in spanish. Can you set your system to english so that we can look at what is going wrong?

**Comment by EricSotillo** [comment]
Sorry, Now i will upload in english.

**Comment by EricSotillo** [comment]
I install ubuntu in english, and i don't know why but Now I hadn't any error.

**Comment by cpaasch** [comment]
Great! Closing.
