### ISSUE TITLE
Can't create 2nd subflow in MPTCP v0.90

### ISSUE THREAD

**Issue by yangfurong** [multipath-tcp/mptcp#155]
Hello, I encounter such a problem:
1. I install a 3.18.20-90-mptcp in my ubuntu14.04 machine which has two interfaces (eth0, eth1).
2. I configure routes for these two interfaces. The default route via eth1.
3. I write a program to download a file from a server (also equipped 3.18.20-90-mptcp), and during the download period, I use `ifconfig` to close eth1. 
4. The outcome is strange: If the 2nd subflow (through eth0) established before eth1 closed, the rest data can be transmitted over eth0.  Otherwise, the transmmition stall, and the client don't attempt to create the 2nd subflow via eth0 (means don't try to send SYN to server).
5. And if I use `ifconfig` to up eth1 again, the transmmition continue, and the 2nd subflow is created.
But MPTCP should support that behavior, according to its' "break-before-make" design.
I hope someone can help me. many thanks!!

**Comment by cpaasch** [comment]
@yangfurong : MPTCP establishes the second subflow only after it has received an acknowledgment on the first subflow. I guess that in your step 4, you bring down eth1 before an ACK has been received. Can you double-check that with tcpdump ?

**Comment by yangfurong** [comment]
Thank for you answer.  
But it may not be the reason. Because there were mutiple ACKs received by both client and server.
There are two figures about the capture file.
![Fig1](https://d17oy1vhnax1f7.cloudfront.net/items/2B3K2r1e1L0s2E1F1E2z/1.png?v=cb14510d)
The first figure show that after the first subflow established, there were multiple ACKs exchanging between client and server.
![Fig2](https://d17oy1vhnax1f7.cloudfront.net/items/321R2e1P2g3W2t3S0P0S/2.png?v=6f3fcc16)
The second figure show that when the 2nd subflow did not establish before close eth1, the entire connection stalled, then recoveried after restart eth1.

**Comment by cpaasch** [comment]
Can you share a packet trace (in pcap format) of each scenario?

**Comment by yangfurong** [comment]
Of course, can you leave a email to me ?  So, I can send it to you by email.

**Comment by cpaasch** [comment]
cpaasch@apple.com

**Comment by cpaasch** [comment]
@yangfurong Thanks for sharing the packet-trace. It looks indeed quite weird. Can you enable debugging with ```sysctl -w net.mptcp.mptcp_debug=1``` and reproduce the issue? Then share what is showing up in ```dmesg```. Thanks!
