### ISSUE TITLE
Question : ‘SOL_TCP’ undeclared (first use in this function) 

### ISSUE THREAD

**Issue by edabanli** [multipath-tcp/mptcp#156]
Hi,
I tried to compile simple client / server pair in c. I'm working on Ubuntu 14.04 LTS 64bit and  3.18.20-90-mptcp kernel. And I have several kernels on this machine. I tested the mptcp by using http://amiusingmptcp.de/ web site and its ok. 
1- When I try to compile the simple client /server api I faced "SOL_TCP’ undeclared (first use in this function)" error I think somehow I need to declare the correct kernel headers for compiling but when I did by -I/usr/src/linux...-mptcp/ then i faced "fatal error: asm/linkage.h: No such file or directory" and many others. 
2. How can I found sample client /server api in C for to test mptcp simply.
Regards
Esat

**Comment by cpaasch** [comment]
Do you do a ```#include <netinet/tcp.h>``` ?

**Comment by edabanli** [comment]
Hi,

SOL_TCP now is ok, But still I cannot succeed the obtain client / server pair which works on mptcp. Could you help me to find sample client / server api in C ?  And is there sample tools in C for to see possible usages of mptcp ? 

Kind Regards
esat

**Comment by cpaasch** [comment]
MPTCP should just work, without having to modify the client/server applications. What do you see not working? How do you test it? (test-topology, configuration,...)

**Comment by edabanli** [comment]
I sent some data from client and client has 3 eth connection. And server receive the data by using 1 eth connection. During this process I check the outgoing data rate on client side (ifstat) and see that only 1 eth is sending the data. 
What I did in both sides:
1)
net.mptcp.mptcp_checksum = 1
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 3

2. Configure IP tables.
ip rule add from 10.45.223.61 table 1
....
ip route add 10.45.223.0/24 dev eth0
scope link table ip route add default via 10.64.64.64 dev eth0 table 1
...
ip route add default scope global nexthop via 10.64.64.64 dev eth0
...
and test with the web side I can see all client connection have data traffic but after that I test it my own applications I see only a connection has data traffic.

**Comment by ghost** [comment]
> Do you do a `#include <netinet/tcp.h>` ?

thank u
