### ISSUE TITLE
Changing Congestion Control

### ISSUE THREAD

**Issue by psfabio** [multipath-tcp/mptcp#157]
Hi,
I successfully install the MPTCP kernel using apt repository on two machines.

My distro is Ubuntu 16.04.1 LTS (Xenial Xerus)

I used these instructions:
```
sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 379CE192D401AB61
deb https://dl.bintray.com/cpaasch/deb jessie main
sudo apt-get update
sudo apt-get install linux-mptcp
```

Then i made the route changes...

My system:

```
$ uname -a
Linux bond 4.1.35.mptcp #4 SMP Sat Nov 5 04:56:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ dmesg | grep MPTCP
[    0.327261] MPTCP: Stable release v0.91.2
```

Using a 4g (15Mbps/10Mbps) and a Cable connection (20Mbps/2Mbps) at one side i can upload a single file via scp or ftp with speeds about 12 mbps and download with speeds about 35 Mbps. (on the other side i have a big pipe of 100mbps).
**Perfect**. I can see the both interfaces at full throttle.

But my main goal is to use on a rtmp streaming connection. In this protocol i think that the mptcp mainly using the cable because the low rtt, and only about 100 or 200kbps of 4G connection. So i can´t upload more than 2mbps. 

I decided to try the different Congestion Control options like olia or balia, but i´m not sure if they are installed on my system.
  
```
$ sysctl net | grep congestion
net.ipv4.tcp_allowed_congestion_control = cubic reno
net.ipv4.tcp_available_congestion_control = cubic reno
net.ipv4.tcp_congestion_control = cubic
```

Do i need to compile them?

some more questions:
Do i need change on both sides?
An about path-manager and scheduler? they can change this behaviour? on both sides too?

thanks a lot.

Fabio

**Comment by cpaasch** [comment]
You need to modprobe the modules:

```
modprobe mptcp_balia
modprobe mptcp_olia
```

**Comment by deshmukhrajvardhan** [comment]
## Aim: Change the Congestion control from cubic to balia

## Setting:
### OS:- 
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
```uname -a```
4.14.24.mptcp #9 SMP Fri Mar 9 19:13:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### MPTCP:- 
```dmesg | grep MPTCP```
[    5.028365] MPTCP: Stable release v0.94.0
```sudo sysctl -a | grep mptcp```
kernel.osrelease = 4.14.24.mptcp
net.mptcp.mptcp_checksum = 1
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 3
net.mptcp.mptcp_version = 0

## MPTCP CONFIG:
```less /boot/config-4.14.24.mptcp```
CONFIG_MPTCP=y
CONFIG_MPTCP_PM_ADVANCED=y
CONFIG_MPTCP_FULLMESH=y
CONFIG_MPTCP_NDIFFPORTS=m
CONFIG_MPTCP_BINDER=m
CONFIG_DEFAULT_FULLMESH=y
CONFIG_DEFAULT_MPTCP_PM="fullmesh"
CONFIG_MPTCP_SCHED_ADVANCED=y
CONFIG_MPTCP_ROUNDROBIN=m
CONFIG_MPTCP_REDUNDANT=m
CONFIG_DEFAULT_SCHEDULER=y
CONFIG_DEFAULT_MPTCP_SCHED="default"
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BIC=m
CONFIG_TCP_CONG_CUBIC=y
CONFIG_TCP_CONG_WESTWOOD=m
CONFIG_TCP_CONG_HTCP=m
CONFIG_TCP_CONG_HSTCP=m
CONFIG_TCP_CONG_HYBLA=m
CONFIG_TCP_CONG_VEGAS=m
CONFIG_TCP_CONG_NV=m
CONFIG_TCP_CONG_SCALABLE=m
CONFIG_TCP_CONG_LP=m
CONFIG_TCP_CONG_VENO=m
CONFIG_TCP_CONG_YEAH=m
CONFIG_TCP_CONG_ILLINOIS=m
CONFIG_TCP_CONG_DCTCP=m
CONFIG_TCP_CONG_CDG=m
CONFIG_TCP_CONG_BBR=m
CONFIG_TCP_CONG_LIA=m
CONFIG_TCP_CONG_OLIA=m
CONFIG_TCP_CONG_WVEGAS=m
CONFIG_TCP_CONG_BALIA=m
CONFIG_DEFAULT_CUBIC=y
CONFIG_DEFAULT_TCP_CONG="cubic"

### MPTCP CC modules: 
```find /lib/modules/$(uname -r) -name "*lia.ko" ```
/lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko
/lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_balia.ko

### MPTCP capable:
```curl http://www.multipath-tcp.org```
Yay, you are MPTCP-capable! You can now rest in peace.

## Problem:
As per [this](https://github.com/multipath-tcp/mptcp/issues/157): 
```sudo modprobe mptcp_balia```
modprobe: ERROR: could not insert 'mptcp_balia': Invalid argument

modprobe: ERROR: could not insert 'mptcp_balia': Invalid argument
### Issue1:
```sysctl net | grep congestion```
net.ipv4.tcp_allowed_congestion_control = cubic reno
net.ipv4.tcp_available_congestion_control = cubic reno
net.ipv4.tcp_congestion_control = cubic

## Any ideas on how to change congestion control are appreciated. Thanks
