### ISSUE TITLE
Recommended hardware

### ISSUE THREAD

**Issue by delinage** [multipath-tcp/mptcp#158]
If I had to implement mptcp in 2 computers to test the protocol and I have no hardware, what is the hardware recommended (if we talk about an ideal case)? a laptop with X ram or X processor? a mini computer?

And if I wanted to do the same on a phone? A nexus?

**Comment by cpaasch** [comment]
It all depends on what you want to measure. What is the goal of your tests?

**Comment by delinage** [comment]
My goal is to stream traffic (streaming vod, real time, download, uploads of big files...) between the server and the client and measure
 1. speed increase with mptpcp
 2. rtt
 3. cpu usage
 4. subflows usage
 5. bandwith ...
And typical features of a tcp conexion, to see the improvement (or not) of the mptcp versus tcp (or mptcp with 1 subflow).

**Comment by cpaasch** [comment]
Sounds to me like you should just use a regular computer that has the interfaces you need. You are not looking for super-high performance nor running MPTCP on a low-end machine (e.g., ARM-processor).
