### ISSUE TITLE
Errors while installing MPTCP on debian wheeze 32 bit machine

### ISSUE THREAD

**Issue by nakannap** [multipath-tcp/mptcp#16]
Hi 

Got the below Errors while installing MPTCP on debian wheeze 32 bit machine

"Error! Bad return status for module build on kernel: 3.10.9.wheezymptcp (i686)"

Can you please help me to resolve this issue

Thanks
Kannappan
## Entire Console dump:

root@debian:~# vi /etc/apt/sources.list.d/mptcp.list
root@debian:~# apt-get update
Ign cdrom://[Debian GNU/Linux 7.0.0 _Wheezy_ - Official Snapshot i386 LIVE/INSTALL Binary 20130505-15:44] wheezy Release.gpg
Ign cdrom://[Debian GNU/Linux 7.0.0 _Wheezy_ - Official Snapshot i386 LIVE/INSTALL Binary 20130505-15:44] wheezy Release
Ign cdrom://[Debian GNU/Linux 7.0.0 _Wheezy_ - Official Snapshot i386 LIVE/INSTALL Binary 20130505-15:44] wheezy/main i386 Packages/DiffIndex
Ign cdrom://[Debian GNU/Linux 7.0.0 _Wheezy_ - Official Snapshot i386 LIVE/INSTALL Binary 20130505-15:44] wheezy/main Translation-en_US
Ign cdrom://[Debian GNU/Linux 7.0.0 _Wheezy_ - Official Snapshot i386 LIVE/INSTALL Binary 20130505-15:44] wheezy/main Translation-en
Get:1 http://multipath-tcp.org wheezy Release.gpg [490 B]
Get:2 http://multipath-tcp.org wheezy Release [1,642 B]
Get:3 http://multipath-tcp.org wheezy/main i386 Packages [3,172 B]
Ign http://multipath-tcp.org wheezy/main Translation-en_US
Ign http://multipath-tcp.org wheezy/main Translation-en
Fetched 5,304 B in 2s (2,015 B/s)
Reading package lists... Done
root@debian:~# apt-get install linux-mptcp
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  linux-headers-3.10.9.wheezymptcp linux-image-3.10.9.wheezymptcp
Suggested packages:
  fdutils linux-doc-3.10.9.wheezymptcp linux-source-3.10.9.wheezymptcp ksymoops linux-image-3.10.9.wheezymptcp-dbg
The following NEW packages will be installed:
  linux-headers-3.10.9.wheezymptcp linux-image-3.10.9.wheezymptcp linux-mptcp
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 42.8 MB of archives.
After this operation, 137 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://multipath-tcp.org/repos/apt/debian/ wheezy/main linux-image-3.10.9.wheezymptcp i386 201308300116 [33.9 MB]
Get:2 http://multipath-tcp.org/repos/apt/debian/ wheezy/main linux-headers-3.10.9.wheezymptcp i386 201308300116 [8,864 kB]
Get:3 http://multipath-tcp.org/repos/apt/debian/ wheezy/main linux-mptcp all 201308300116 [1,570 B]
Fetched 42.8 MB in 54s (787 kB/s)
Preconfiguring packages ...
Selecting previously unselected package linux-image-3.10.9.wheezymptcp.
(Reading database ... 118529 files and directories currently installed.)
Unpacking linux-image-3.10.9.wheezymptcp (from .../linux-image-3.10.9.wheezymptcp_201308300116_i386.deb) ...
Done.
Selecting previously unselected package linux-headers-3.10.9.wheezymptcp.
Unpacking linux-headers-3.10.9.wheezymptcp (from .../linux-headers-3.10.9.wheezymptcp_201308300116_i386.deb) ...
Selecting previously unselected package linux-mptcp.
Unpacking linux-mptcp (from .../linux-mptcp_201308300116_all.deb) ...
Setting up linux-image-3.10.9.wheezymptcp (201308300116) ...

 Hmm. There is a symbolic link /lib/modules/3.10.9.wheezymptcp/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/3.10.9.wheezymptcp/build

 Hmm. The package shipped with a symbolic link /lib/modules/3.10.9.wheezymptcp/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/3.10.9.wheezymptcp/source

Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/dkms 3.10.9.wheezymptcp /boot/vmlinuz-3.10.9.wheezymptcp
Error! Bad return status for module build on kernel: 3.10.9.wheezymptcp (i686)
Consult /var/lib/dkms/virtualbox-guest/4.1.18/build/make.log for more information.
Error!  Build of vmblock.ko failed for: 3.10.9.wheezymptcp (i686)
Consult the make.log in the build directory
/var/lib/dkms/open-vm-tools/2012.05.21/build/ for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.10.9.wheezymptcp /boot/vmlinuz-3.10.9.wheezymptcp
update-initramfs: Generating /boot/initrd.img-3.10.9.wheezymptcp
W: Possible missing firmware /lib/firmware/bnx2/bnx2-mips-09-6.2.1b.fw for module bnx2
W: Possible missing firmware /lib/firmware/bnx2/bnx2-mips-06-6.2.3.fw for module bnx2
run-parts: executing /etc/kernel/postinst.d/pm-utils 3.10.9.wheezymptcp /boot/vmlinuz-3.10.9.wheezymptcp
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 3.10.9.wheezymptcp /boot/vmlinuz-3.10.9.wheezymptcp
Generating grub.cfg ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-3.10.9.wheezymptcp
Found initrd image: /boot/initrd.img-3.10.9.wheezymptcp
Found linux image: /boot/vmlinuz-3.2.0-4-686-pae
Found initrd image: /boot/initrd.img-3.2.0-4-686-pae
Found linux image: /boot/vmlinuz-3.2.0-4-486
Found initrd image: /boot/initrd.img-3.2.0-4-486
done
Setting up linux-headers-3.10.9.wheezymptcp (201308300116) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.10.9.wheezymptcp /boot/vmlinuz-3.10.9.wheezymptcp
Error! Bad return status for module build on kernel: 3.10.9.wheezymptcp (i686)
Consult /var/lib/dkms/virtualbox-guest/4.1.18/build/make.log for more information.
Error!  Build of vmblock.ko failed for: 3.10.9.wheezymptcp (i686)
Consult the make.log in the build directory
/var/lib/dkms/open-vm-tools/2012.05.21/build/ for more information.
Setting up linux-mptcp (201308300116) ...
root@debian:~# sysctl -w net.mptcp.mptcp_enabled 1
sysctl: "net.mptcp.mptcp_enabled" must be of the form name=value
sysctl: "1" must be of the form name=value
root@debian:~# sysctl -w net.mptcp.mptcp_enabled=1
sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or directory
root@debian:~# sysctl -w net.mptcp.[mptcp_enabled]=[1]
sysctl: cannot stat /proc/sys/net/mptcp/[mptcp_enabled]: No such file or directory
root@debian:~# sysctl -w net.mptcp.mptcp_enabled
sysctl: "net.mptcp.mptcp_enabled" must be of the form name=value
root@debian:~# sysctl -w net.mptcp.mptcp_enabled=1
sysctl: cannot stat /proc/sys/net/mptcp/mptcp_enabled: No such file or directory
root@debian:~# ip rule show
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default
root@debian:~# ip route
default via 10.104.59.1 dev eth2  proto static
10.104.59.0/24 dev eth2  proto kernel  scope link  src 10.104.59.30
169.254.0.0/16 dev eth2  scope link  metric 1000
root@debian:~# ip route show table 1
root@debian:~# uname -a
Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.41-2 i686 GNU/Linux
root@debian:~# file /usr/bin/file
/usr/bin/file: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0x48e9cd9bbec26154bf29f4464dfe016f770316de, stripped
root@debian:~#

**Comment by cpaasch** [comment]
You have to reboot your machine, in order to use MPTCP.

From the log you show above, it does not seem like you rebooted your host.

Further, can you show the content of /var/lib/dkms/virtualbox-guest/4.1.18/build/make.log

**Comment by nakannap** [comment]
Hi Christoph

I will reload and try it out.

In between this is my make.log file

“
DKMS make.log for virtualbox-guest-4.1.18 for kernel 3.10.9.wheezymptcp (i686)
Wed Sep  4 21:57:48 EDT 2013
make: Entering directory `/usr/src/linux-headers-3.10.9.wheezymptcp'
  LD      /var/lib/dkms/virtualbox-guest/4.1.18/build/built-in.o
  LD      /var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/built-in.o
  CC [M]  /var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/VBoxGuest-linux.o
/var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/VBoxGuest-linux.c:206:49: error: expected ?=?, ?,?, ?;?, ?asm? or ?__attribute__? before ?g_VBoxGuestPciId?
/var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/VBoxGuest-linux.c:216:1: error: ?__mod_pci_device_table? aliased to undefined symbol ?g_VBoxGuestPciId?
make[2]: *** [/var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/VBoxGuest-linux.o] Error 1
make[1]: *** [/var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest] Error 2
make: *** [_module_/var/lib/dkms/virtualbox-guest/4.1.18/build] Error 2
make: Leaving directory`/usr/src/linux-headers-3.10.9.wheezymptcp'
“

Thanks
Kannappan

**Comment by cpaasch** [comment]
Can you please attach the file:
/var/lib/dkms/virtualbox-guest/4.1.18/build/vboxguest/VBoxGuest-linux.c

**Comment by nakannap** [comment]
After reload, Looks like it is fine

root@debian:~# sudo apt-get install linux-mptcp
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-mptcp is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@debian:~# sysctl -w net.mptcp.mptcp_enabled=1
net.mptcp.mptcp_enabled = 1
root@debian:~#    

Will try to get that file as well

Thanks

**Comment by cpaasch** [comment]
Ok, I close this issue as MPTCP is booting now.
