### ISSUE TITLE
How many connections is it using?

### ISSUE THREAD

**Issue by shavenne** [multipath-tcp/mptcp#162]
Hi!

I'm wondering if it's possible to see how many uplinks one specific connection is using!?
I'm using a SSH-tunnel as SOCKS proxy to speed up my internet connection and it seems that it's loosing one uplink sometimes (mostly the same because that one is a LTE connection). I have to reopen the SSH-tunnel then to get the speed of all three connections (btw: is this a normal behaviour that it's not coming back automatically?).
I would like to write a script which automatically recreates the SSH-connection when the uplink is lost but I can't when I'm not able to get the information above.

**Comment by cpaasch** [comment]
You can see the number of subflows by looking at /proc/net/mptcp_net/mptcp, which gives you a list of MPTCP connections and how many subflows each has.

Wrt to the issue you describe, you should take a look at https://github.com/multipath-tcp/mptcp/issues/153
