### ISSUE TITLE
Problem with configuration of MPTCP

### ISSUE THREAD

**Issue by lifaen123** [multipath-tcp/mptcp#163]
Hello,
Followed the guide
http://multipath-tcp.org/pmwiki.php/Users/AptRepository
and I'm getting error 

mininet@mininet-vm:/$ sudo apt-get install linux-mptcp
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-mptcp : Depends: linux-headers-3.18.20-90-mptcp but it is not installable
               Depends: linux-image-3.18.20-90-mptcp but it is not installable
E: Unable to correct problems, you have held broken packages.

Im using mininet ubuntu 32 bit on virtual machine. Checked the version and its 14.04 
What is the problem ?

**Comment by cpaasch** [comment]
I recommend you install the packages from our bintray repository, as this contains the latest release:
https://multipath-tcp.org/pmwiki.php/Users/AptRepository has instructions how to configure the bintray repository.
