### ISSUE TITLE
[RST] was sent on the second subflow immediately after [SYN, ACK] was received

### ISSUE THREAD

**Issue by fengjim** [multipath-tcp/mptcp#164]
Hi,

We're using MPTCP for a small project. It was observed that [RST] was sent on the second subflow immediately after [SYN, ACK] was received. Here are the configuration and collected log:

1. Linux 
   Ubuntu 16.04.1 LTS - VM using Virtualbox on Windows 7
2. MPTCP Version:
   Installed the latest apt package as recommended at https://multipath-tcp.org/pmwiki.php/Users/AptRepository
   the installed package label is 20161105044139, for kernel 4.1.35.

3. MPTCP configuration:
  net.mptcp.mptcp_checksum=1
  net.mptcp.mptcp_debug=1
  net.mptcp.mptcp_enabled=1
  net.mptcp.mptcp_path_manager=fullmesh
  net.mptcp.mptcp_scheduler=default
  net.mptcp.mptcp_syn_retries=3
  net.mptcp.mptcp_version=0

4. Network Configuration 
  two network interfaces are created on the guest OS and both of them are using 'Bridge Adapter' as the back-end to make traffic go through host Windows' network adapter 
  NIC-1:  147.214.99.142
  NIC-2:  147.214.99.148
  (Yes, this is different from MPTCP recommended routing configuration, but the issue being reported does not seem to be related to the routing settings rather than MPTCP protocol handling)

5. Open Firefox in guest OS and access web page (http://amiusingmptcp.de) and using Wireshark capturing the packets on both network interfaces.

6. It was observed that MPTCP stack in guest OS established the primary subflow perfectly and it tried to establish the second subflow. However, [RST] was sent from MPTCP stack immediately after [SYN, ACK] was received.
Please find Wireshark packet capture and dmesg of mptcp debug log as attached.
[packet_and_dmesg.zip](https://github.com/multipath-tcp/mptcp/files/739133/packet_and_dmesg.zip)

Please help check if that was caused by any incorrect configuration or something surprised MPTCP stack.

Thanks in advance!

Regards/Jim Feng

**Comment by cpaasch** [comment]
Can you show us the output of "netstat -s" before and after you did such an experiment.

And, has the packet-trace been taken on the client guest-system?

**Comment by fengjim** [comment]
@cpaasch thanks a lot for your reply.

Please kindly find the output of 'netstat -s' as attached below:
(in order to make all the logs match, I re-collect dmesg and pcap files together with 'netstat -s'.)
[mptcp_log.zip](https://github.com/multipath-tcp/mptcp/files/741448/mptcp_log.zip)

Regarding your question "And, has the packet-trace been taken on the client guest-system?",
Here is the general steps during experiment: installed MPTCP stack in Ubuntu (Guest OS) and then in guest OS open Firefox to access MPTCP test server (http://amiusingmptcp.de), meanwhile use Wireshark in guest OS to capture packets in and out. So the packet-trace was taken from guest system.

**Comment by cpaasch** [comment]
Can you also take a before/after of "cat /proc/net/mptcp_net/snmp" ?

**Comment by fengjim** [comment]
Please find the new log as attached:
[mptcp_log.zip](https://github.com/multipath-tcp/mptcp/files/745451/mptcp_log.zip)

**Comment by cpaasch** [comment]
You have the counter MPCapableFallbackSYNACK that is increasing.
```
MPCapableFallbackSYNACK         	24
```

This means that the MP_JOIN SYN/ACK that comes back does not have an MPTCP-option, and that ```mptcp(tp)``` on the new subflow is not set. This is really surprising... I will have to prepare a debug-patch for you to analyze this issue.

**Comment by fengjim** [comment]
Thanks @cpaasch !. Interesting finding! That seems strange since pcap file is showing both MP_JOIN SYN and ACK had MPTCP Options and the keys looked correct.

Just let me know once you have the debug patch ready.

**Comment by madhanraj** [comment]
Hi Paasch, 
just eager about this case. In tcpdump syn/ack has mp_join , but dropped somehow . Does this mean it is happening in netfilter layer ? somewhere in the prerouting or input these options are stripped ?

**Comment by cpaasch** [comment]
Cleaning up some old tickets - if you are still having troubles, feel free to reach out again or reopen the issue.

**Comment by leidemon** [comment]
I also have this issue,any suggestions?

**Comment by leidemon** [comment]
> Cleaning up some old tickets - if you are still having troubles, feel free to reach out again or reopen the issue.

@fengjim @cpaasch    any suggestions?

**Comment by fengjim** [comment]
Hi @leidemon , sorry, I have left the related project for a long time. May @cpaasch help you on this.

**Comment by leidemon** [comment]
> You have the counter MPCapableFallbackSYNACK that is increasing.
> 
> ```
> MPCapableFallbackSYNACK         	24
> ```
> 
> This means that the MP_JOIN SYN/ACK that comes back does not have an MPTCP-option, and that `mptcp(tp)` on the new subflow is not set. This is really surprising... I will have to prepare a debug-patch for you to analyze this issue.

hi,cpaasch:
    do you have some suggestions about  this?

**Comment by leidemon** [comment]
> Hi @leidemon , sorry, I have left the related project for a long time. May @cpaasch help you on this.
hi, fengjim, ok, thank you for reply.

**Comment by cpaasch** [comment]
Digging further through this!

My hint on ```MPCapableFallbackSYNACK``` was wrong. However, what I see is that the incoming SYN/ACK is simply being considered as incorrect and thus results in a RST. But, the TCP-socket is still there.

I think what is happening is that the outgoing traffic goes out on a different interface than the incoming one. If you do a pcap on each interface, I am sure you will see that the SYN + MP_JOIN leaves on one interface, while the SYN/ACK + MP_JOIN comes back on a different one.

Can you check that? That means that there is some routing configuration issue.

**Comment by leidemon** [comment]
> Digging further through this!
> 
> My hint on `MPCapableFallbackSYNACK` was wrong. However, what I see is that the incoming SYN/ACK is simply being considered as incorrect and thus results in a RST. But, the TCP-socket is still there.
> 
> I think what is happening is that the outgoing traffic goes out on a different interface than the incoming one. If you do a pcap on each interface, I am sure you will see that the SYN + MP_JOIN leaves on one interface, while the SYN/ACK + MP_JOIN comes back on a different one.
> 
> Can you check that? That means that there is some routing configuration issue.
hi,cpaasch：
thank you for reply,I pcap the data，and check the pcap,I found SYN/ACK + MP_JOIN comes from eth0 and eth1,but they are all RST by client,.
The env is:
eth0:192.168.9.43
eth1:192.168.9.199
ip route:
default via 192.168.9.1 dev eth0  proto static 
192.168.9.0/24 dev eth1  proto kernel  scope link  src 192.168.9.199  metric 1 
192.168.9.0/24 dev eth0  proto kernel  scope link  src 192.168.9.43  metric 1 
eth0 and eth1 are different interface but bridged with the same wired network and as you said ,ip route seems something wrong,
I will try to dig it, the pcap files as attached, can you give me some suggestions?
[pcap.zip](https://github.com/multipath-tcp/mptcp/files/4017899/pcap.zip)

**Comment by leidemon** [comment]
add more:
I check the eth0.pcap,I found SYN/ACK + MP_JOIN comes to different one,
372:
Ethernet II, Src: Vmware_c6:84:18 (00:0c:29:c6:84:18), Dst: Vmware_bb:c9:0d (00:0c:29:bb:c9:0d)
373：
Ethernet II, Src: Vmware_bb:c9:0d (00:0c:29:bb:c9:0d), Dst: Vmware_c6:84:22 (00:0c:29:c6:84:22)
 seems SYN/ACK + MP_JOIN send wrong diretion, so I think the issue is to correct this?

**Comment by leidemon** [comment]
I try the other scene:
client:
I use one wired network:192.168.9.43
use another wireless network:192.168.43.199
server: 192.168.9.42
and also use ss-local+privoxy to ss-server agent test;
and I can see 43 have send the ADD Address packets,but 43.199 no work,can not see any packets from 43.199 in pcap.In my opintion, 43.199 should send the JOIN CONNECT even through it can not reach the dst?
@cappsch Can you help me for it ? Thanks.

**Comment by cpaasch** [comment]
Without using MPTCP, first try to do ICMP-pings from the different interfaces and make sure that things are routable. It seems like your server does not know how to reach 192.168.43.199 through the wireless interface.

**Comment by leidemon** [comment]
> 在不使用MPTCP的情况下，首先尝试从不同的接口执行ICMP ping操作，并确保可路由。看来您的服务器不知道如何通过无线接口到达192.168.43.199。

I have modified the route,I use the iptables to set some rules for eth1 to use the nat to 9.42:
route add -net 192.168.43.0/24 gw 192.168.9.1
iptables -F 
iptables -P INPUT ACCEPT 
iptables -P FORWARD ACCEPT
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE 
 and 43.199 can reach the  192.168.9.42
but I test the mptcp,the 192.168.43.199 still do not send the JOIN CONNECT.
![718bfe66c3db4c68a63f70db1b1479ad](https://user-images.githubusercontent.com/56546433/71809697-92e14880-30ab-11ea-9138-d3dec1a98ab3.jpg)

[tmp.zip](https://github.com/multipath-tcp/mptcp/files/4025509/tmp.zip)

**Comment by leidemon** [comment]
> 在不使用MPTCP的情况下，首先尝试从不同的接口执行ICMP ping操作，并确保可路由。看来您的服务器不知道如何通过无线接口到达192.168.43.199。
debug log of client
[ 7617.520511] mptcp_alloc_mpcb: created mpcb with token 0x50e75bc
[ 7617.521221] mptcp_add_sock: token 0x50e75bc pi 1, src_addr:192.168.9.43:17840 dst_addr:192.168.9.42:8388
[ 7617.523164] mptcp_add_sock: token 0x50e75bc pi 2, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0
[ 7617.523241] __mptcp_init4_subsockets: token 0x50e75bc pi 2 src_addr:192.168.43.199:0 dst_addr:192.168.9.42:8388 ifidx: 3
[ 7629.614041] mptcp_close: Close of meta_sk with tok 0x50e75bc
[ 7629.621274] mptcp_del_sock: Removing subsock tok 0x50e75bc pi:2 state 7 is_meta? 0
[ 7631.419321] mptcp_del_sock: Removing subsock tok 0x50e75bc pi:1 state 7 is_meta? 0
[ 7631.419505] mptcp_sock_destruct destroying meta-sk token 0x50e75bc

**Comment by cpaasch** [comment]
Please show us the full configuration so we can get the full picture. I think we are missing something.

```ip link show``` ```ip addr show``` ```ip rule list``` ```ip route show table all``` And all of your iptables config,...

On both, client and server.

**Comment by leidemon** [comment]
> Please show us the full configuration so we can get the full picture. I think we are missing something.
> 
> `ip link show` `ip addr show` `ip rule list` `ip route show table all` And all of your iptables config,...
> 
> On both, client and server.

I use two ubuntu 16.04 and install mptcp 0.95 ,shadowsocks-libev-3.3.3
client: ss-local+privoxy, two interface: wired network:192.168.9.43 wireless network:192.168.43.199
server: ss-server one interface:wired network:192.168.9.42(can reach the network)
I add one route rule in server:
route add -net 192.168.43.0/24 gw 192.168.9.42 for they can reach to dst
but it still not send the join connect packet as I see in the pcap.
more info:
server:
ss-server:
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"123456",
    "timeout":600,
    "method":"aes-256-cfb",
    "verbose":2,
    "mode":"tcp_and_udp",
    "mptcp":true
}
ip link show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:bb:c9:0d brd ff:ff:ff:ff:ff:ff

ip addr show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:0c:29:bb:c9:0d brd ff:ff:ff:ff:ff:ff
    inet 192.168.9.42/24 brd 192.168.9.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::250f:bc31:e1d9:3403/64 scope link
       valid_lft forever preferred_lft forever

ip rule list
0:    from all lookup local
32766:    from all lookup main
32767:    from all lookup default

ip route show table all
default via 192.168.9.1 dev ens33  proto static  metric 100
169.254.0.0/16 dev ens33  scope link  metric 1000
192.168.9.0/24 dev ens33  proto kernel  scope link  src 192.168.9.42  metric 100
192.168.43.0/24 via 192.168.9.42 dev ens33  scope link
broadcast 127.0.0.0 dev lo  table local  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  table local  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  table local  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  table local  proto kernel  scope link  src 127.0.0.1
broadcast 192.168.9.0 dev ens33  table local  proto kernel  scope link  src 192.168.9.42
local 192.168.9.42 dev ens33  table local  proto kernel  scope host  src 192.168.9.42
broadcast 192.168.9.255 dev ens33  table local  proto kernel  scope link  src 192.168.9.42
fe80::/64 dev ens33  proto kernel  metric 256  pref medium
local ::1 dev lo  table local  proto kernel  metric 0  pref medium
local fe80::250f:bc31:e1d9:3403 dev ens33  table local  proto kernel  metric 0  pref medium
ff00::/8 dev ens33  table local  metric 256  pref medium




client:
ss-local:
{
    "server":"192.168.9.42",
    "server_port":8388,
    "local":"0.0.0.0",
    "local_port":1080,
    "password":"123456",
    "timeout":600,
    "method":"aes-256-cfb",
    "mode":"tcp_and_udp",
    "verbose":2
}
privoxy:modify as follow,more info can find in config
listen-address  127.0.0.1:8118
forward-socks5t   /               127.0.0.1:1080 .

ip link show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:b1:7f:2d brd ff:ff:ff:ff:ff:ff
3: ens38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:b1:7f:37 brd ff:ff:ff:ff:ff:ff

ip addr show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:b1:7f:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.9.43/24 brd 192.168.9.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::7bc9:f0a5:8d5f:5f2e/64 scope link
       valid_lft forever preferred_lft forever
3: ens38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:b1:7f:37 brd ff:ff:ff:ff:ff:ff
    inet 192.168.43.199/24 brd 192.168.43.255 scope global ens38
       valid_lft forever preferred_lft forever
    inet6 2408:805f:e209:5c70:ea28:f6aa:5e67:818a/64 scope global noprefixroute dynamic
       valid_lft 3132sec preferred_lft 3132sec
    inet6 fe80::3411:6f02:a2da:e591/64 scope link
       valid_lft forever preferred_lft forever

ip rule list:
0:    from all lookup local
32766:    from all lookup main
32767:    from all lookup default

ip route show table all:
default via 192.168.43.195 dev ens38  proto static  metric 100
default via 192.168.9.1 dev ens33  proto static  metric 101
169.254.0.0/16 dev ens33  scope link  metric 1000
192.168.9.0/24 dev ens33  proto kernel  scope link  src 192.168.9.43  metric 100
192.168.43.0/24 dev ens38  proto kernel  scope link  src 192.168.43.199  metric 100
broadcast 127.0.0.0 dev lo  table local  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  table local  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  table local  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  table local  proto kernel  scope link  src 127.0.0.1
broadcast 192.168.9.0 dev ens33  table local  proto kernel  scope link  src 192.168.9.43
local 192.168.9.43 dev ens33  table local  proto kernel  scope host  src 192.168.9.43
broadcast 192.168.9.255 dev ens33  table local  proto kernel  scope link  src 192.168.9.43
broadcast 192.168.43.0 dev ens38  table local  proto kernel  scope link  src 192.168.43.199
local 192.168.43.199 dev ens38  table local  proto kernel  scope host  src 192.168.43.199
broadcast 192.168.43.255 dev ens38  table local  proto kernel  scope link  src 192.168.43.199
2408:805f:e209:5c70::/64 dev ens38  proto ra  metric 100  pref medium
fe80::/64 dev ens33  proto kernel  metric 256  pref medium
fe80::/64 dev ens38  proto kernel  metric 256  pref medium
default via fe80::6e39:7c9a:c720:b9e3 dev ens38  proto static  metric 100  pref medium
local ::1 dev lo  table local  proto kernel  metric 0  pref medium
local 2408:805f:e209:5c70:ea28:f6aa:5e67:818a dev ens38  table local  proto kernel  metric 0  pref medium
local fe80::3411:6f02:a2da:e591 dev ens38  table local  proto kernel  metric 0  pref medium
local fe80::7bc9:f0a5:8d5f:5f2e dev ens33  table local  proto kernel  metric 0  pref medium
ff00::/8 dev ens33  table local  metric 256  pref medium
ff00::/8 dev ens38  table local  metric 256  pref medium

[privoxy_conf_and_pcap.zip](https://github.com/multipath-tcp/mptcp/files/4038290/privoxy_conf_and_pcap.zip)

**Comment by leidemon** [comment]
> Please show us the full configuration so we can get the full picture. I think we are missing something.
> 
> `ip link show` `ip addr show` `ip rule list` `ip route show table all` And all of your iptables config,...
> 
> On both, client and server.
mptcp conf：
root@demon-virtual-machine:/home/demon# sysctl net.mptcp.mptcp_path_manager 
net.mptcp.mptcp_path_manager = fullmesh
root@demon-virtual-machine:/home/demon# sysctl net.mptcp.mptcp_enabled 
net.mptcp.mptcp_enabled = 1
root@demon-virtual-machine:/home/demon# sysctl net.mptcp.mptcp_scheduler 
net.mptcp.mptcp_scheduler = redundant

**Comment by leidemon** [comment]
@cpaasch 
I update the ubuntu to 18.04.3 and install the lastest linux-mptcp test,it still not working.192.168.43.199 still no send the join connect;
client ping:
root@lwd-virtual-machine:/home/lwd# ping -I 192.168.43.199 192.168.9.42
PING 192.168.9.42 (192.168.9.42) from 192.168.43.199 : 56(84) bytes of data.
64 bytes from 192.168.9.42: icmp_seq=1 ttl=64 time=1.70 ms
64 bytes from 192.168.9.42: icmp_seq=2 ttl=64 time=1.32 ms
server ping:
root@lwd-virtual-machine:~# ping 192.168.43.199
PING 192.168.43.199 (192.168.43.199) 56(84) bytes of data.
64 bytes from 192.168.43.199: icmp_seq=1 ttl=64 time=1.67 ms
64 bytes from 192.168.43.199: icmp_seq=2 ttl=64 time=1.05 ms

the attach files include netstat(rule,route...) and the pcap data.
[18.04.3-linux-mptcp-0.95.zip](https://github.com/multipath-tcp/mptcp/files/4052452/18.04.3-linux-mptcp-0.95.zip)

**Comment by leidemon** [comment]
@cpaasch 
any suggestion？

**Comment by leidemon** [comment]
I update the ubuntu to 18.04.3 and install the lastest linux-mptcp(4.19.55) test,I set the rule in server
(route add -net 192.168.43.0/24 gw 192.168.9.42 )to let the 192.168.43.199 can reach 192.168.9.43;
but it still not working.192.168.43.199 still no send the join connect;
attach files include pcap and the netstat(route.rule,add,link)
[pcap-and-netstat(add,rule,route,link).zip](https://github.com/multipath-tcp/mptcp/files/4058844/pcap-and-netstat.add.rule.route.link.zip)

client:
ss-local + two interface(192.168.9.43(wired)    192.168.43.199(wireless))
server:
ss-server+ one interface(192.168.9.42 wired)
expectation：
client can link to server with two interface at the same time.

is it wrong setup in my env? I confuse.

**Comment by cpaasch** [comment]
You need to configure the ip-rules to make sure that your outgoing traffic leaves on the right interface. Have a look at http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting.

The problem in your config is that the subflow with source 192.168.9.43 leaves the host on ens38. That's because of the missing ip-rule. By default Linux will route solely based on destination-IP, which in your case will match on the first rule in ip route ```default via 192.168.43.195 dev ens38 proto static metric 100```.

So, please take a look at the above link. That is the missing piece in your configuration.

**Comment by leidemon** [comment]
@cpaasch 
The problem in your config is that the subflow with source 192.168.9.43 leaves the host on ens38. That's because of the missing ip-rule. By default Linux will route solely based on destination-IP, which in your case will match on the first rule in ip route default via 192.168.43.195 dev ens38 proto static metric 100.
--------sorry,I can not understand clearly,can you explan more?
Do you mean I should use ens33 for 192.168.43.199 route?
I have saw the http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting. and setup like manual configuration:
client:
ip rule add from 192.168.9.43 table 1
ip rule add from 192.168.43.199 table 2
ip route add 192.168.9.0/24 dev ens33 scope link table 1
ip route add default via 192.168.9.1 dev ens33 table 1
ip route add 192.168.43.0/24 dev ens38 scope link table 2
ip route add default via 192.168.43.174 dev ens38 table 2
ip route add default scope global nexthop via 192.168.9.1 dev ens33

netstat as follow:
root@lwd-virtual-machine:/home/lwd/shadowsocks-libev-3.3.4# ip route
default via 192.168.9.1 dev ens33
192.168.9.0/24 dev ens33 proto kernel scope link src 192.168.9.43
192.168.43.0/24 dev ens38 proto kernel scope link src 192.168.43.199
root@lwd-virtual-machine:/home/lwd/shadowsocks-libev-3.3.4# ip rule
0:    from all lookup local
32764:    from 192.168.43.199 lookup 2
32765:    from 192.168.9.43 lookup 1
32766:    from all lookup main
32767:    from all lookup default
root@lwd-virtual-machine:/home/lwd/shadowsocks-libev-3.3.4# ip route show table 2
default via 192.168.43.174 dev ens38
192.168.43.0/24 dev ens38 scope link
root@lwd-virtual-machine:/home/lwd/shadowsocks-libev-3.3.4# ip route show table 1
default via 192.168.9.1 dev ens33
192.168.9.0/24 dev ens33 scope link

but it still do not send  join connect

**Comment by cpaasch** [comment]
Can you again take separate pcaps on each interface and share them? Just to see what is going on now.

**Comment by leidemon** [comment]
> 您可以在每个界面上再次使用单独的pcap并共享它们吗？只是看看现在发生了什么。

I dump the pcap from both interfaces,and found the join connect sent from ens38;
and 192.168.43.199 seems do not know the route to 192.168.9.42, and send failed.
so maybe I should add some route to deal with it. In my opinion it would pass through the agent.But it seems wrong.
[client-and-pcap.zip](https://github.com/multipath-tcp/mptcp/files/4070900/client-and-pcap.zip)

**Comment by cpaasch** [comment]
Ok, now the packets are leaving the client from the right interface. So we fixed that part! :-)

However it seems like the server does not know how to reply to the client as the SYN/ACK never reaches the server.

Can you show us now all the info from the server? ip addr show, ip link show, ip route show all,...
And also reproduce while taking a pcap.

Thanks!

**Comment by leidemon** [comment]
> 好的，现在数据包正从正确的接口离开客户端。因此，我们修复了该部分！:-)
> 
> 但是，由于SYN / ACK从未到达服务器，因此服务器似乎不知道如何回复客户端。
> 
> 您现在可以向我们显示服务器上的所有信息吗？ip addr show，ip link show，ip route show all，...
> 并且在进行pcap时也可以重现。
> 
> 谢谢！

hi.cpaasch
thank you for reply,it seems I need add some rule in server side，so 192.168.43.199 can reach 192.168.9.42,;
in  my origin designed, the client use two interface link to server agent through the agent,
like this :
-----9.43-------|---------------------------------------- |--------
----(client) --->agent(127.0.0.1)<----mptcp----->9.42-->(server)--tcp->network
-----43.199----|-----------------------------------------|---------
But now it seems wrong,because I can not found the packets from 192.168.43.199 in server side.(it should be sent through the agent,right?) I think the wireless interface should find some ways to reach the server.Maybe you have some guide for this?

[s-netstat-and-pcap.zip](https://github.com/multipath-tcp/mptcp/files/4074929/s-netstat-and-pcap.zip)

thank you very much for help

**Comment by leidemon** [comment]
> Ok, now the packets are leaving the client from the right interface. So we fixed that part! :-)
> 
> However it seems like the server does not know how to reply to the client as the SYN/ACK never reaches the server.
> 
> Can you show us now all the info from the server? ip addr show, ip link show, ip route show all,...
> And also reproduce while taking a pcap.
> 
> Thanks!

I change use the ss-redir conect to ss-server，and dump the pcap. I find the client send the join connect packet, but it seems server do not accpet to deal;
I look up in the internet,try to add some rule in server side,but failed.
![Image](https://user-images.githubusercontent.com/56546433/72611336-c69e5700-3964-11ea-8bae-4296027f09d1.png)
[client-ens38-and-server-ens33.zip](https://github.com/multipath-tcp/mptcp/files/4076688/client-ens38-and-server-ens33.zip)

**Comment by cpaasch** [comment]
I don't understand what the agent represents in your picture:

> -----9.43-------|---------------------------------------- |--------
> ----(client) --->agent(127.0.0.1)<----mptcp----->9.42-->(server)--tcp->network
> -----43.199----|-----------------------------------------|---------

If the server is not receiving the SYN+MP_JOIN, something in the routing between client and server is wrong.

**Comment by leidemon** [comment]
> 我不了解代理商在您的照片中所代表的意思：
> 
> > ----- 9.43 ------- | ------------------------------------ ---- | -------- 
> > ----（客户端）--->代理（127.0.0.1）<---- mptcp -----> 9.42->（服务器）- -tcp->网络
> > ----- 43.199 ---- | ---------------------------------- ------- | ---------
> 
> 如果服务器未接收到SYN + MP_JOIN，则客户端和服务器之间的路由中有问题。
Simple network topology。
use ss-redir for client,I can find the pcaket sent to 127.0.0.1:1080(agent listen port)，but can not find in the server side,means the packets do not reach the ens33 in server side ,I search in the net and get the info : network data flows from interface(ens33) to iptables, so if it can not reach the ens33. And check the packets,the mac address of server(192.168.9.42) is different from 192.168.43 sent and 192.168.43.199 sent,so the case of this issue is route rule? 192.168.43.199 get the wrong dst?Maybe I
can try gre tunnel to link 192.168.43.199 and 192.168.9.42?

**Comment by cpaasch** [comment]
Do you still have this problem? If yes, please reopen.
