### ISSUE TITLE
TSQ causes MPTCP stalls 

### ISSUE THREAD

**Issue by hlavnjak** [multipath-tcp/mptcp#167]
Hi,

We are using MPTCP on embedded platform for two flows paired with relatively fast server. I observed the following issue on the server side: When sending data from server to client, the TCP flow stops for a 0.5 s in every few seconds. After a week of studying of protocol fundamentals and logging with a lot of printk functions, I've found the reason. When the send buffer on the server is full or it is waiting for slow ACKs from client and the **TSQ** is throttled, **mptcp_is_temp_unavailable**  scheduler function refuses to select any flow. Even when all ACKs was recieved, protocol has to wait until the window probe timeout occurs (**tcp_probe_timer**) and after that, the TSQ tasklet is called, **TSQ_THROTTLED** is unset and MPTCP can work normally for a while (few seconds). I think that MPTCP cannot call **mptcp_write_space** when send buffers are freed, because of **TSQ** throttle (**mptcp_write_space** causes scheduler functions to be called).

My solution of the problem was applying the kernel patch similar to this one https://www.spinics.net/lists/netdev/msg204870.html - disabling TCP TSQ via setting **sysctl_tcp_limit_output_bytes** to negative value. It has completely resolved the issue, but unfortunately, I am not able to correct it in the sources..

Thank you,

Jacob

**Comment by cpaasch** [comment]
Hello Jacob, which version of MPTCP are you using?

**Comment by hlavnjak** [comment]
Sorry for an incomplete question. I'am using **Stable release v0.91.2** and multiplexing over LTE channels.

**Comment by VMatrix1900** [comment]
Is this bug fixed in v0.92?

**Comment by cpaasch** [comment]
Cleaning up some old issues. The code related to the tsq-handling has gone through quite some changes. If you are still seeing the issue, please let us know.
