### ISSUE TITLE
MPTCP LTE/WiFi RTT Impact on TP

### ISSUE THREAD

**Issue by madhanraj** [multipath-tcp/mptcp#168]
Hi , 
I have been doing TP test with different simulation . I found that when rtt difference is higher the aggr% is getting worse . 
In few case , the MPTCP TP is less than TCP TP in one interface (which violates the MPTCP RFC which states that the thumb rule is at MPTCP should be greater than or equal to the Legacy TCP)

WiFi/ LTE (Almost same rtt 95.51% aggr)
135.539 Mbps/ 146.529 Mbps     
MPTCP : 269.4 Mbps

WiFi/ LTE (Almost  2xrtt 67.51 % aggr)
304.707 Mbps/146.529 Mbps
MPTCP: 304.584 Mbps

I tested with different version , still the problem looks same. 
had enough room for rwnd , rmem buffer , tcp_limit_output_queue 

What should be the checkpoints ? Is there any change in the server scheduler required ?

**Comment by cpaasch** [comment]
Can you try the very latest mptcp_v0.91, which includes https://github.com/multipath-tcp/mptcp/commit/d77a2b41654e4f284d21d9ea06e21d4f810846e2 .

It might have quite an impact.

**Comment by madhanraj** [comment]
i tried changing the tcp_enter_quickack_mode in v0.89.4 (Samsung S6 kernel) . However there wasnt much impact . Let me try with the latest version and update you with the same.

**Comment by madhanraj** [comment]
Hi Paasch, 
with the old kernel , made lil extra buffer and changes the tcp_limit_output_queue . The aggr % was close to 90%
Avg WiFi 311.182 Mbps LTE 146.529 Mbps 
MPTCP 1 FTP 440.713 Mbps 
MPTCP 2 FTP 402.611 Mbps 
MPTCP Iperf 437. Mbps 

Problem solved with user space tuning

**Comment by cpaasch** [comment]
Ok. Closing then.

**Comment by nnovoice** [comment]
Does it matter which of the links was the default route?

**Comment by leotian111** [comment]
hi, madhanraj 
"made lil extra buffer and changes the tcp_limit_output_queue . The aggr % was close to 90%"
where is the tcp_limit_output_queue, i can find it in proc/sys/net/ipv4;  and how to make lil extra buffer!
please help me, thank u a lot!

**Comment by leotian111** [comment]
i tested in 2 ltes using the verion v0.92; but i can't get the aggre throughtout, only get 50% bandwidth; just like 1 plus 1 equal 1
