### ISSUE TITLE
Using VPN with MPTCP - is it a good idea?

### ISSUE THREAD

**Issue by opensourcegeek** [multipath-tcp/mptcp#169]
I've a router (linux box) which I've configured to use mptcp and I've a server which is mptcp enabled. I've a scenario where I need connectivity back from mptcp server to client (linux box). Running just SOCKS5 proxy takes care of traffic one way using all interfaces and works out of the box. However given I need to get to the client, I'm wondering if VPN is a good option. 

I'm not sure if running VPN just like SOCKS proxy would work if I make VPN to run over TCP instead of UDP. But this has it's own arguments (TCP over TCP) on why not to do it. I could possibly run VPN after mptcp, in which case mptcp just balances external interfaces leaving tunnel to still run over UDP. 

Any suggestions or comments will be really helpful.

**Comment by cpaasch** [comment]
Have you checked out redsocks? http://darkk.net.ru/redsocks/

**Comment by opensourcegeek** [comment]
I've used shadowsocks which runs on libev and it does work fine. However I need access from this proxy server back to client(or router) to remotely debug etc. This is why I was contemplating on using a VPN still to get back. But once I bring VPN in and run it over TCP so that all traffic leaving tunnel interface can make use of mptcp, I'm not sure if it will be degrading performance as these are mobile routers not over a stable connection. 

I can in theory create a tunnel for each interface in router and expose that as possible paths to mptcp - this will add significant overhead I think on server but at least it will use all the WANs without having TCP over TCP sort of over head. 

Any suggestions would be really useful - thanks.

**Comment by shavenne** [comment]
Do you know that you can use SSH as SOCKS proxy?
I'm using it and redirect all HTTP(S) traffic via iptables and redsocks through it. Works fine!

Maybe you don't even need VPN.

**Comment by opensourcegeek** [comment]
@shavenne Interesting - I haven't looked into  it but I have established reverse tunnels via SSH and they drop all the time. That's when IPSec made more sense to create site to site VPN. 

If you're using SSH as SOCKS proxy, is it performing well? Especially when they are like mobile routers the connections will drop. Do you create a reverse tunnel via SSH to get back to clients in this setup?

**Comment by shavenne** [comment]
I'm just using it to boost my internet connection at home. I'm not using it for site to site VPN.
It uses 2x VDSL, 1x LTE connection and sometimes a wireless hotspot in the neighborhood. 
Performance is very good even with that different latencies.
Unfortunately when one uplink drops and comes back I have to reconnect the SSH connection to use this uplink again. So far it runs fine with the other uplinks, no complete drop.
For site to site VPN you may interested in the TUN/TAP-capabilities of SSH.

**Comment by N3XTSTEP** [comment]
I'm using it to bond two 4G connections. MP-TCP works really well for this because the bandwidth and latency on each path is a constantly changing unknown variable. However because not all web servers support MPTCP I have to use a REDSOCKS to redirect all the traffic back to a "hub" on the internet running Dante "sockd". I'm currently looking at securing this connection with OpenVPN or vtun (a site-to-site over each 4G path) and having a hard time getting MPTCP to use these paths. Does MPTCP work with the linux tuntap driver and are there any additional steps or considerations required?

**Comment by cpaasch** [comment]
Yes, using MPTCP with OpenVPN works as well. You can check out http://gfdsa.gfdsa.org/2013/05/18/using-2-connections-4/ (and the other parts of this series of blog-posts).

**Comment by N3XTSTEP** [comment]
Managed to make this work by using a loopback on the hub (with socks5 daemon listening on this loopback) and creating separate routing tables on each tap interface, each with a route to the loopback on the hub. Then from the remote box using curl it's possible to specify to use socks5 along with the hub loopback when downloading a file off the internet (for incoming LAN traffic, a transparent proxy can point to this IP as well). It's important to have a more generic default route like "ip route add default nexthop via TAP-GW-IP dev tap1 nexthop via TAP-GW-IP dev tap2" as well for ICMP, UDP and the first TCP flow to work with per destination load balancing and then MPTCP will kick in and create sub flows to perform per-packet load balancing for TCP traffic.

**Comment by opensourcegeek** [comment]
@slenpree Interesting, how does it scale? So on the remote box if you have multiple 4G modems do you have a tunnel over each of those modem interfaces? Also if you need to get back to your remote box (via SSH) from hub, can you use any of the tunnel interfaces available on hub?

**Comment by N3XTSTEP** [comment]
@opensourcegeek yeah MP-TCP has some security issues in relation to the creation of sub flows so it’s a good idea to use a secure VPN tunnel over each path. SSH back to any tunnel interface is fine, depending on if you match the tunnels 1to1 with same source routing on each side or use multipoint VPN with source routing on the remote side only will decide if you get subflows or not.
