### ISSUE TITLE
Kernel 3.11 + MPTCP - infinite loop

### ISSUE THREAD

**Issue by okias** [multipath-tcp/mptcp#17]
![20131005_002](https://f.cloud.github.com/assets/2457435/1275197/a16266a6-2deb-11e3-86d7-5bd8087b9f06.jpg)
It stop working _only_ if is ethernet cable connected at boot time. When is disconnected and connected afterwards, its ok. 
Patch is from here: https://bugs.gentoo.org/show_bug.cgi?id=477786

Testing it with 3.10.4 and it look fixed. So, maybe it was 3.10 bug. Anyway, I didnt yet find any piece of code from .4 which could affect mptcp. So, for now it seems good. Can be closed.

**Comment by okias** [comment]
So, I accidentally someway disabled mptcp on 3.10.4, so problem persist.

**Comment by okias** [comment]
when is kernel compiled with debug options and framepointers enabled, it look fine. For me, seems there is something called too early (before something else initialize, in 3.11 was some part near mptcp code reworked, so maybe they did some optimalization, for which isn't mptcp ready). I'll try someway trigger it, but it appears only when eth0 interface is set to up.

**Comment by cpaasch** [comment]
We can close this now.
https://bugs.gentoo.org/show_bug.cgi?id=477786#c12

**Comment by okias** [comment]
Confirmed - compiled without kernel debug and it works without infinite loop when cable is connected.
