### ISSUE TITLE
mptcp installation

### ISSUE THREAD

**Issue by JohnWejin** [multipath-tcp/mptcp#171]
I'm new to linux, and working on mptcp project. i tried installing the mptcp kernel implementation, on ubuntu 14.04 and got this message

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-mptcp : Depends: linux-headers-3.18.20-90-mptcp but it is not installable
               Depends: linux-image-3.18.20-90-mptcp but it is not installable
E: Unable to correct problems, you have held broken packages.

Please how can i fix this

**Comment by cpaasch** [comment]
Please use the packages from our bintray repository instead. See https://multipath-tcp.org/pmwiki.php/Users/AptRepository
