### ISSUE TITLE
mptcp support for Ubuntu Xenial?

### ISSUE THREAD

**Issue by thusharams** [multipath-tcp/mptcp#174]
Hello,
I have been trying to enable `mptcp` on Ubuntu `Xenial` and found some patches from http://multipath-tcp.org/patches/, tried applying these patches to` 4.4.0` but ended up with huge number of merge conflicts! I have also checked from [this ](https://multipath-tcp.org/pmwiki.php/Users/AptRepository) link there was a release of mptcp on Trusty and I didn't found the same for the Ubuntu's subsequent releases.
So, Please do let me know if there are any such releases for Ubuntu Xenial or any hints to merge mptcp patches for Xenial!
Thanks in advnance!

**Comment by cpaasch** [comment]
You should grab the source from branch mptcp_v0.92, which is based on v4.4.x

**Comment by thusharams** [comment]
@cpaasch : Thanks for the response! Yes I got the sources from `mptcp_v0.92` branch! It includes the merges from upstream v4.4x but it doesn't include the Ubuntu patches. And trying to merge `mptcp_v0.92` on Ubuntu Xenial kernel ends up with lot of conflicts!
