### ISSUE TITLE
Kernel Panic when using redundant scheduler and linux trafic control

### ISSUE THREAD

**Issue by suhrm** [multipath-tcp/mptcp#177]
Hi, I am currently in the progress of some performance testing for MPTCP in cellular networks for that I use netem (tc) to emulate some conditions of the cellular connection. However when using the redundant scheduler I sometimes get the following kernel panic (sorry for the picture, do not know how else to capture it).
![18159515_10155243833752760_1690014033_o](https://cloud.githubusercontent.com/assets/13349058/25398491/9b3957ac-29ec-11e7-8a22-1ab9e71448a5.jpg)

Any help is really appreciated!

Regards.

Rasmus Suhr Mogensen

**Comment by MukeshYadav1984** [comment]
I have seen mptcp crash while using redundant .Not sure whether it was exactly same.

Fix for this is in atttached file

--- a/net/mptcp/mptcp_output.c
+++ b/net/mptcp/mptcp_output.c
@@ -652,7 +655,7 @@ bool mptcp_write_xmit(struct sock *meta_sk, unsigned int mss_now, int nonagle,
        struct mptcp_cb *mpcb = meta_tp->mpcb;
        struct sk_buff *skb;
        int reinject = 0;
      -       unsigned int sublimit;
      +        unsigned int sublimit = 0;
        __u32 path_mask = 0;

**Comment by cpaasch** [comment]
Thanks, @MukeshYadav1984 for the fix. I will submit it to upstream.

**Comment by matttbe** [comment]
Closing: patch now in `mptcp_trunk`, `mptcp_v0.92` and `mptcp_v0.91` branches

Thank you for the bug report and the two patches!

**Comment by amazing-discoveries** [comment]
Hello,
I have here the same issue. The thing is, in a VM everything works with the redundant scheduler  but on real machine I get a kernel panic.

**Comment by cpaasch** [comment]
@amazing-discoveries - do you get the same crash-trace? If yes, please update to the most recent kernel. Otherwise, you should submit a new bug-report with the crash-trace. Thanks!

**Comment by amazing-discoveries** [comment]
Thank you, the update has fix the issue!
