### ISSUE TITLE
Why most of coupled ccs developed here (like LIA and OLIA) is based on TCP Reno?

### ISSUE THREAD

**Issue by lwins-lights** [multipath-tcp/mptcp#178]
Have you tried to develop coupled cc based on more popular cc algorithm, like, TCP Cubic? I am just interested with this. There is no doubt that OLIA is a nice cc (with mathematical elegance).

**Comment by cpaasch** [comment]
There has been work on MPCubic (http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6082546), but the authors never published patches to include it in our kernel.
