### ISSUE TITLE
4G bonding

### ISSUE THREAD

**Issue by sjtosco** [multipath-tcp/mptcp#180]
Hi! I'm using mptcp for 4G bonding. I mixing 4 connections for video streaming. I using nginx-rtmp as relay. I use a middle server (MPTCP compatible) for join flows and resend video to womza server.

Everything looks like well, but frequently i have cuts in video and freezes... And every time, the use change in modems is correlated with the video freezes. **I ask if the mptcp is suitable for video streaming** or if possible or necessary put a buffer in middle server for mitigate the cuts before re-stream.
Thanks in advance!

**Comment by sjtosco** [comment]
I comment that i can use mptcp for video streaming, with some problems that i'm resolving step by step. :-)
Thanks! Regards!!!

**Comment by ByteArrayException** [comment]
Hi! I run into the same issue, how did you fixed (or "workaround") it?
