### ISSUE TITLE
Problems with changing scheduler

### ISSUE THREAD

**Issue by suhrm** [multipath-tcp/mptcp#182]
Hi, I am currently testing the performance of the different schedulers given different network conditions. However I am having some troubles with changing the schedulers.

When I use the following command:

  sysctl -w net.mptcp.mptcp_scheduler="some other scheduler"

It accepts the change, however when confirming with Wireshark it still uses the previous scheduler.

Am I doing something wrong when changing the scheduler or is there a certain amount of time that has to pass before the change happens?

MPTCP kernel: 4.1.38 on Ubuntu 16.04 LTS
MPTCP version: 0.91

**Comment by cpaasch** [comment]
Hello,

can you give more details? Like what scheduler are you setting, and how are you checking with wireshark whether it worked, or not?

**Comment by suhrm** [comment]
I am using all of them i.e. default, redundant and round robin. To verify the scheduler I have made traces and examined. I check sub flow traffic for each interface when sending a fixed file size and see how much they send individually.

**Comment by suhrm** [comment]
The issue has resolved itself, It seems that it was due to our way of doing the network emulation.
