### ISSUE TITLE
How to know my current kernel support mptcp？

### ISSUE THREAD

**Issue by ttc0419** [multipath-tcp/mptcp#184]
I install kernel form epel，and I don't know if it support mptcp，please help me if you know😁

**Comment by matttbe** [comment]
Hi,
There are many ways, e.g.:

    ls /proc/net/mptcp_net
    dmesg | grep MPTCP

**Comment by matttbe** [comment]
http://multipath-tcp.org/pmwiki.php/Users/RPM
http://multipath-tcp.org/pmwiki.php/Users/UseMPTCP
http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP
