### ISSUE TITLE
How can I control which interfaces I am going to use for MPTCP

### ISSUE THREAD

**Issue by ghostli123** [multipath-tcp/mptcp#185]
Hello, 

My machines have many interfaces and VLAN configured. How can I ask MPTCP to use just two of them, but not all of them? Thank you very much!

Best,
Yang

**Comment by cpaasch** [comment]
Check out https://multipath-tcp.org/pmwiki.php/Users/Tools. It shows how to disable an interface for MPTCP when the fullmesh path-manager is used.

**Comment by ghostli123** [comment]
Wonderful! Thanks!
