### ISSUE TITLE
Any restriction on the interfaces used by MPTCP fullmesh path manager

### ISSUE THREAD

**Issue by ghostli123** [multipath-tcp/mptcp#186]
I have several multiple-interface machines and I setup vlan to make them communication with each other. The communication may go through some gateways, but gateways will keep TCP option fields. 

In my experiment, I use iperf to generate connection. My **observation** is that for some destination IPs, multiple MPTCP subflows are generate; but for some other destination IPs, only a single MPTCP flow is generated (the connection between the master pair of IPs). 

Note that I use tcpdump to check whether any subflows try to join the connection. If the destination IP is set to IPs bound to some interfaces, only one MPTCP flow will try to be established (the connection between the master pair of IPs), rather than fullmesh.

Thus, I want to know whether there is any restriction on the interfaces used by MPTCP **fullmesh** path manager?

Thank you very much!

Best,
Yang

**Comment by cpaasch** [comment]
What do you mean with "If the destination IP is set to IPs bound to some interfaces" ?

Can you show your config? (ifconfig, ip addr show, ip route ,...)

**Comment by ghostli123** [comment]
Thanks for the reply!

server side: iperf -s -p 22222
client side: iperf -c 10.10.13.35 -p 22222 -t 999 -i 1

The confused statement in the above question is about the parameter fed after _-c_ in _iperf_ command which indicates server IP. 

My observation is for 10.10.13.35 (which is bound to eth8, see below configuration), multiple subflows are established (only eth8 interface and eth4 interfaces are used). For management IP (which is bound to eth4), multiple subflows are established (only eth8 interface and eth4 interfaces are used). However, for all other IPs, they are using MPTCP to communication, BUT only one subflow (master flow) is established, and other interfaces do not intended to send out tcp syn packet at all. **Looks like except eth4 and eth8, other interfaces are not added into _a potential MPTCP fullmesh group_.**    


=================Server Side=================
ifconfig result
> eth4  _(management port with Internet connection)_   Link encap:Ethernet  HWaddr 00:24:81:c4:de:da  
>           inet addr: a.b.c.d Bcast:a.b.c.255  Mask:255.255.254.0
>           inet6 addr: fe80::224:81ff:fec4:deda/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:418428 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:162680 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:553223604 (527.5 MiB)  TX bytes:32241934 (30.7 MiB)
>           Interrupt:17 
> 
> eth8      Link encap:Ethernet  HWaddr 3c:fd:fe:9d:4a:18  
>           inet addr:10.10.13.35  Bcast:10.10.13.255  Mask:255.255.255.0
>           inet6 addr: fe80::3efd:feff:fe9d:4a18/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:15616020 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:7623333 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:23586873744 (21.9 GiB)  TX bytes:565746978 (539.5 MiB)
> 
> eth9      Link encap:Ethernet  HWaddr 3c:fd:fe:9d:4a:19  
>           inet addr:10.10.14.35  Bcast:10.10.14.255  Mask:255.255.255.0
>           inet6 addr: fe80::3efd:feff:fe9d:4a19/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:1856336 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:745934 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:2799522358 (2.6 GiB)  TX bytes:55792885 (53.2 MiB)
> 
> eth8.67   Link encap:Ethernet  HWaddr 3c:fd:fe:9d:4a:18  
>           inet addr:10.10.67.35  Bcast:10.10.67.255  Mask:255.255.255.0
>           inet6 addr: fe80::3efd:feff:fe9d:4a18/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:172637 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:86873 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:257837034 (245.8 MiB)  TX bytes:6465646 (6.1 MiB)
> 
> eth9.68   Link encap:Ethernet  HWaddr 3c:fd:fe:9d:4a:19  
>           inet addr:10.10.68.35  Bcast:10.10.68.255  Mask:255.255.255.0
>           inet6 addr: fe80::3efd:feff:fe9d:4a19/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:939 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:763 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:110442 (107.8 KiB)  TX bytes:93413 (91.2 KiB)
> 
> lo        Link encap:Local Loopback  
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:24203 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:24203 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1 
>           RX bytes:19912121 (18.9 MiB)  TX bytes:19912121 (18.9 MiB)

ip addr show
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth4:  _(management port with Internet connection)_ <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 00:24:81:c4:de:da brd ff:ff:ff:ff:ff:ff
>     inet a.b.c.d/23 brd a.b.c.255 scope global eth4
>        valid_lft forever preferred_lft forever
>     inet6 fe80::224:81ff:fec4:deda/64 scope link 
>        valid_lft forever preferred_lft forever
> 3: eth6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether 00:1b:21:33:0f:73 brd ff:ff:ff:ff:ff:ff
> 4: eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfe9d4a18 state UP group default qlen 1000
>     link/ether 3c:fd:fe:9d:4a:18 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.13.35/24 brd 10.10.13.255 scope global eth8
>        valid_lft forever preferred_lft forever
>     inet6 fe80::3efd:feff:fe9d:4a18/64 scope link 
>        valid_lft forever preferred_lft forever
> 5: eth5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether 00:1b:21:0f:06:a1 brd ff:ff:ff:ff:ff:ff
> 6: eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfe9d4a19 state UP group default qlen 1000
>     link/ether 3c:fd:fe:9d:4a:19 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.14.35/24 brd 10.10.14.255 scope global eth9
>        valid_lft forever preferred_lft forever
>     inet6 fe80::3efd:feff:fe9d:4a19/64 scope link 
>        valid_lft forever preferred_lft forever
> 7: eth8.67@eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 3c:fd:fe:9d:4a:18 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.67.35/24 brd 10.10.67.255 scope global eth8.67
>        valid_lft forever preferred_lft forever
>     inet6 fe80::3efd:feff:fe9d:4a18/64 scope link 
>        valid_lft forever preferred_lft forever
> 8: eth9.68@eth9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 3c:fd:fe:9d:4a:19 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.68.35/24 brd 10.10.68.255 scope global eth9.68
>        valid_lft forever preferred_lft forever
>     inet6 fe80::3efd:feff:fe9d:4a19/64 scope link 
>        valid_lft forever preferred_lft forever

ip route
> 10.10.13.0/24 dev eth8  proto kernel  scope link  src 10.10.13.35 
> 10.10.14.0/24 dev eth9  proto kernel  scope link  src 10.10.14.35 
> 10.10.62.0/24 via 10.10.67.42 dev eth8.67 
> 10.10.66.0/24 via 10.10.67.42 dev eth8.67 
> 10.10.67.0/24 dev eth8.67  proto kernel  scope link  src 10.10.67.35 
> 10.10.68.0/24 dev eth9.68  proto kernel  scope link  src 10.10.68.35 
> a.b.c.0/23 dev eth4  proto kernel  scope link  src a.b.c.e (management port gateway)

=================Client Side=================

ifconfig

> eth4      Link encap:Ethernet  HWaddr 00:24:81:c4:de:c2  
>           inet addr:a.b.c.f  Bcast:a.b.c.255  Mask:255.255.254.0
>           inet6 addr: fe80::224:81ff:fec4:dec2/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:160 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:235 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:27354 (26.7 KiB)  TX bytes:33180 (32.4 KiB)
>           Interrupt:17 
> 
> eth6      Link encap:Ethernet  HWaddr 00:15:17:8f:d6:66  
>           inet addr:10.10.11.33  Bcast:10.10.11.255  Mask:255.255.255.0
>           inet6 addr: fe80::215:17ff:fe8f:d666/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:5 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:174 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:456 (456.0 B)  TX bytes:33945 (33.1 KiB)
>           Interrupt:16 Memory:f8000000-f8020000 
> 
> eth6.66   Link encap:Ethernet  HWaddr 00:15:17:8f:d6:66  
>           inet addr:10.10.66.33  Bcast:10.10.66.255  Mask:255.255.255.0
>           inet6 addr: fe80::215:17ff:fe8f:d666/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:2 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:86 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:132 (132.0 B)  TX bytes:16256 (15.8 KiB)
> 
> lo        Link encap:Local Loopback  
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:7 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1 
>           RX bytes:517 (517.0 B)  TX bytes:517 (517.0 B)

ip addr show

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 00:24:81:c4:de:c2 brd ff:ff:ff:ff:ff:ff
>     inet a.b.c.f/23 brd a.b.c.255 scope global eth4
>        valid_lft forever preferred_lft forever
>     inet6 fe80::224:81ff:fec4:dec2/64 scope link 
>        valid_lft forever preferred_lft forever
> 3: eth8: <BROADCAST,MULTICAST> mtu 1500 qdisc noop portid 3cfdfe9d4bd8 state DOWN group default qlen 1000
>     link/ether 3c:fd:fe:9d:4b:d8 brd ff:ff:ff:ff:ff:ff
> 4: eth6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>     link/ether 00:15:17:8f:d6:66 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.11.33/24 brd 10.10.11.255 scope global eth6
>        valid_lft forever preferred_lft forever
>     inet6 fe80::215:17ff:fe8f:d666/64 scope link 
>        valid_lft forever preferred_lft forever
> 5: eth5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether 00:15:17:19:a3:fc brd ff:ff:ff:ff:ff:ff
> 6: eth9: <BROADCAST,MULTICAST> mtu 1500 qdisc noop portid 3cfdfe9d4bd9 state DOWN group default qlen 1000
>     link/ether 3c:fd:fe:9d:4b:d9 brd ff:ff:ff:ff:ff:ff
> 7: eth6.66@eth6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 00:15:17:8f:d6:66 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.66.33/24 brd 10.10.66.255 scope global eth6.66
>        valid_lft forever preferred_lft forever
>     inet6 fe80::215:17ff:fe8f:d666/64 scope link 
>        valid_lft forever preferred_lft forever

ip route
> default via a.b.c.1 dev eth4 
> 10.10.11.0/24 dev eth6  proto kernel  scope link  src 10.10.11.33 
> 10.10.62.0/24 via 10.10.66.43 dev eth6.66 
> 10.10.66.0/24 dev eth6.66  proto kernel  scope link  src 10.10.66.33 
> 10.10.67.0/24 via 10.10.66.43 dev eth6.66 
> 10.10.68.0/24 via 10.10.66.43 dev eth6.66 
> a.b.c.0/23 dev eth4  proto kernel  scope link  src a.b.c.e

=====================================================================

There are two gateway in the middle to ensure the connectivity between the client and the server. 

I debug the kernel, and look like all interfaces are recognized by MPTCP Fullmesh path manager when the kernel is started. A kernel printk is inserted in line 1021 of the file (https://github.com/multipath-tcp/mptcp/blob/b47be2ff07584d52a331607856841feffcbf8cc3/net/mptcp/mptcp_fullmesh.c). 

server side kernel log
```
[    2.773636] version 1.1, lo: scope:254, loop:1, running:0, nomulti:0, up=0
[    2.773850] version 1.1, lo: scope:254, loop:1, running:1, nomulti:0, up=1
[    8.111133] version 1.1, eth4: scope:0, loop:0, running:0, nomulti:0, up=0
[    8.186882] version 1.1, eth4: scope:0, loop:0, running:1, nomulti:0, up=1
[   11.201584] version 1.1, eth4: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.723660] version 1.1, eth8: scope:0, loop:0, running:0, nomulti:0, up=0
[   15.729478] version 1.1, eth8: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.730111] version 1.1, eth8: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.730782] version 1.1, eth8: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.786444] version 1.1, eth9: scope:0, loop:0, running:0, nomulti:0, up=0
[   15.792581] version 1.1, eth9: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.794881] version 1.1, eth9: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.864030] version 1.1, eth8.67: scope:0, loop:0, running:0, nomulti:0, up=0
[   15.865909] version 1.1, eth8.67: scope:0, loop:0, running:1, nomulti:0, up=1
[   15.957081] version 1.1, eth9.68: scope:0, loop:0, running:0, nomulti:0, up=0
[   15.961968] version 1.1, eth9.68: scope:0, loop:0, running:1, nomulti:0, up=1
[   16.734814] version 1.1, eth9: scope:0, loop:0, running:1, nomulti:0, up=1
[   16.735600] version 1.1, eth8.67: scope:0, loop:0, running:1, nomulti:0, up=1
[   16.736306] version 1.1, eth9.68: scope:0, loop:0, running:1, nomulti:0, up=1
```

**Comment by cpaasch** [comment]
Hmmm... Ok, that's quite a complex setup. But, are you sure that the routing-tables are correct?

Drawing your setup on a whiteboard and intended routing might help.

Also, take a packet-trace on the client-side and look at which SYNs are going out of which interface and reaching the server over which interface?
