### ISSUE TITLE
MPTCP isn't using multiple connections

### ISSUE THREAD

**Issue by Kylechang122** [multipath-tcp/mptcp#187]
Hi all, 

Sorry in advance since this is kind of long and I don't have much experience working with linux or networking. I will try my best to provide additional information if requested. I have been trying to use mptcp over a wireless and ethernet interface. However, when I run ifstat while downloading snapshots  from http://multipath-tcp.org/snapshots/, only one interface is being used at a time. The "amiusingmptcp.de" also tells me I'm not using mptcp but I feel like I configured the routing correctly.

 I'm using a linux mint 18.1 Serena machine and I installed following the instructions on the [mptcp website](http://multipath-tcp.org/pmwiki.php/Users/AptRepository). I've also been following this slightly outdated [tutorial](https://www.youtube.com/watch?v=uS0QwLFjl8M) for configuring. 
This is what my ifconfig and netstat yield:

> enp5s0    Link encap:Ethernet  HWaddr d0:67:e5:e8:d9:46  
          inet addr:192.168.88.247  Bcast:192.168.88.255  Mask:255.255.255.0
          inet6 addr: fe80::4826:d5eb:ffb9:c006/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14228 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12553 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:15198423 (15.1 MB)  TX bytes:1366867 (1.3 MB)
          Interrupt:17 

> lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1281 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1281 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:115140 (115.1 KB)  TX bytes:115140 (115.1 KB)

> wlx00265ac23c08 Link encap:Ethernet  HWaddr 00:26:5a:c2:3c:08  
          inet addr:192.168.0.103  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::88bd:d8e7:1f52:4cb5/64 Scope:Link
          inet6 addr: fe80::f568:25ea:1408:c2ee/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:103 errors:0 dropped:16 overruns:0 frame:0
          TX packets:85 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:33306 (33.3 KB)  TX bytes:13338 (13.3 KB)

> Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.88.1    0.0.0.0         UG        0 0          0 enp5s0
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 wlx00265ac23c08
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 enp5s0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 wlx00265ac23c08
192.168.88.0    0.0.0.0         255.255.255.0   U         0 0          0 enp5s0

I've been using these instructions to configure routing: 
`sudo ip rule add from 192.168.88.247 table 1`
`sudo ip rule add from 192.168.0.103 table 2`

`sudo ip route add 192.168.88.0/24 dev enp5s0 scope link table 1`
`sudo ip route add default via 192.168.88.1 dev enp5s0 table 1`

`sudo ip route add 192.168.0.0/24 dev wlx00265ac23c08 scope link table 2`
`sudo ip route add default via 192.168.0.1 dev wlx00265ac23c08 table 2`

`sudo ip route add default scope global nexthop via 192.168.88.1 dev enp5s0`

In addition, mptcp is enabled since when I run
` cat /proc/sys/net/mptcp/mptcp_enabled` 
`1`

Is there a step that I'm missing or forgetting? Any advice is greatly appreciated. Thanks a lot in advance.

**Comment by enigmaro** [comment]
can you enable debug=1 and see what the output is after you download a snapshot ? Just to confirm are you sure you're on the right kernel? if so which version of mptcp are you using?

**Comment by Kylechang122** [comment]
I believe I'm using the right kernel and version, since when I run `uname -r`, I get `4.4.70_mptcp`. 
I've enabled debug=1 but I don't see any debug messages pertaining to mptcp using dmesg while downloading the snapshot. When I do `dmesg | grep mptcp`, the only values I get are 

> [    0.000000] Linux version 4.4.70.mptcp (root@debian-amd64) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 SMP Sun Jun 4 21:51:14 UTC 2017
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.4.70.mptcp root=UUID=2c86686a-3b6a-4443-aaa7-138bd1526815 ro quiet splash
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.70.mptcp root=UUID=2c86686a-3b6a-4443-aaa7-138bd1526815 ro quiet splash
[    1.219652] usb usb1: Manufacturer: Linux 4.4.70.mptcp uhci_hcd
[    1.220390] usb usb2: Manufacturer: Linux 4.4.70.mptcp uhci_hcd
[    1.221097] usb usb3: Manufacturer: Linux 4.4.70.mptcp uhci_hcd
[    1.223453] usb usb4: Manufacturer: Linux 4.4.70.mptcp uhci_hcd
[    1.244115] usb usb5: Manufacturer: Linux 4.4.70.mptcp ehci_hcd
[    1.363917] usb usb6: Manufacturer: Linux 4.4.70.mptcp ehci_hcd
[    1.388654] usb usb7: Manufacturer: Linux 4.4.70.mptcp uhci_hcd
[    1.389377] usb usb8: Manufacturer: Linux 4.4.70.mptcp uhci_hcd

Sorry for the dumb question but where can I get more helpful output? Thanks so much again. 

edit 1: I ran wireshark without downloading the snapshot and got  a lot of black TCP Retransmission, TCP Out of Order. 
![screenshot from 2017-07-07 10-25-55](https://user-images.githubusercontent.com/17348460/27969418-9902a06e-62ff-11e7-8e7e-0af0a4079aca.png)

**Comment by enigmaro** [comment]
Ok, I've encountered this 'Spurious Retransmissions' of SYNs before too but that was with a server running mptcp and I could not figure out why exactly. Did you install MPTCP from the debian packages on the mptcp website? 

If you did, try building the kernel from source instead because building from source worked for me. In case you are unfamiliar with building kernels from source, they should be relatively simple if you just look it up on google for your distro and follow the instructions on the site for help building mptcp from source.

Can you also run wireshark while downloading a snapshot and posting it here?

**Comment by cpaasch** [comment]
Just to double-check, can you do:
```dmesg | grep -i mptcp``` (note the added ```-i```).


Thanks!
