### ISSUE TITLE
mptcp and ubuntu 32-bit

### ISSUE THREAD

**Issue by peterjlegg** [multipath-tcp/mptcp#190]
Looking at the downloads section it states that there is no binary for ubuntu 32-bit. Please can someone confirm this. I set up a Ubuntu32 VM and mininet on VirtualBox and was hoping to install mptcp there.

thanks, Peter

**Comment by matttbe** [comment]
Hi Peter,

There is no build for Ubuntu 32-bit but one for 64-bit. Is it a problem to use a 64-bit VM?
If yes, then there is no other possibilities than compiling the kernel: http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

**Comment by peterjlegg** [comment]
Thanks. I had an issue that my virtualbox only supported 32-bit Ubuntu. This morning, I found that my virtualization support in my CPU was disabled, and after switching it on (via BIOS), 64-bit is now an option. I will use this, and the MPTCP to match.

Peter.

Dr Peter Legg
Senior MAC Designer
Blu Wireless Technology Ltd
+44 77 618 378 18
Skype : peter.legg.bwt
peter.legg@bluwirelesstechnology.com<mailto:mark.barrett@bluwirelesstechnology.com>
www.bluwirelesstechnology.com<http://www.bluwirelesstechnology.com/>
