### ISSUE TITLE
Kernel panic: 2-4 times per day, random?

### ISSUE THREAD

**Issue by invokablegmbh** [multipath-tcp/mptcp#191]
Hi,

we are experiencing kernel panics on our mptcp-enabled linux gateway. We installed mptcp via apt-repo. Those panics occured with the old 0.9.1-release aswell as with 0.92.
I attached the kern.log-file, so you can see all the stack traces and also can see how often they appear.
I am wondering wether all these panics relate to the same bug, as there are different call stacks.
Please have a look at the attached file.

uname -a:
`Linux debian 4.4.70.mptcp #1 SMP Sun Jun 4 21:51:14 UTC 2017 x86_64 GNU/Linux`

[kern.log.txt](https://github.com/multipath-tcp/mptcp/files/1165891/kern.log.txt)

**Comment by cpaasch** [comment]
Hello,

can you enable KASAN in the kernel-config for debugging purposes? It should give more information as to where the memory corruption happens.


Thanks!

**Comment by invokablegmbh** [comment]
I am compiling a new kernel now with KASAN enabled. Keep you updated...

**Comment by cpaasch** [comment]
Thanks!

**Comment by cpaasch** [comment]
Do you have an update?

**Comment by invokablegmbh** [comment]
Hi, sorry for my late answer, but I wanted to do some advanced testing before coming back to you.
After compiling the kernel myself, all the crashes went away. It rebooted once, but this was very likely a power failure. So the self-compiled version is OK now.

However, I retested the version from your apt-repo and it crashed again and again. Those crashes only appear, if the mptcp-server has traffic (on a typical office-day we have > 300GB traffic which is routed through our experimental mptcp-gw). In idle state there are no crashes.

Then, I tested three different servers and it seemed that those crashes only appear on "supermicro"-server hardware. Using the self-compiled version on other supermicro-servers did solve the issue.
I also tested one non-supermicro server and there your apt-version seems to be running fine.

So, maybe you want to write onto your website that people should try to compile by themselves, if they face problems with the apt-repo-version of the kernel?

**Comment by invokablegmbh** [comment]
Issue is resolved for me by using a self-compiled version of the kernel.

**Comment by invokablegmbh** [comment]
Yeah. I wrote this on saturday - and voila: Today the server crashed two times. However, KASAN was enabled now. Find two crashdumps in the zip-file I uploaded here: https://jar.media/static_download/crashdumps.zip

**Comment by invokablegmbh** [comment]
And we had the next crash. Besides the dump you can find above, here is  only the log from the last crash:

[dmesg.201708071433.txt](https://github.com/multipath-tcp/mptcp/files/1204811/dmesg.201708071433.txt)

Additional Infos:

```
net.mptcp.mptcp_checksum = 0
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 10
net.mptcp.mptcp_version = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.tcp_congestion_control = reno

root@debian:~# cat /sys/module/mptcp_fullmesh/parameters/create_on_err
1
root@debian:~# cat /sys/module/mptcp_fullmesh/parameters/num_subflows
3
```

**Comment by cpaasch** [comment]
Thanks for the coredumps and all the info. I'm looking into it.

**Comment by cpaasch** [comment]
Hmmm... the dump-files you have in the archive don't seem to be coredumps of the panic. What kind of files are these? What do you get when you do ```gdb -c dump.201708070912 kernel_link``` ?

Also, does the kernel has any customizations?

**Comment by invokablegmbh** [comment]
No, the kernel does not have any customizations. I followed your instructions at http://multipath-tcp.org/pmwiki.php/Users/DoItYourself and then used the buildsteps described at the debian page.

**Comment by cpaasch** [comment]
I see - what about ```gdb -c dump.201708070912 kernel_link``` ?

**Comment by invokablegmbh** [comment]
And for your question: GDB sais that this is not a dump file. Why? I used this howto: https://www.bentasker.co.uk/documentation/linux/312-installing-and-configuring-kdump-on-debian-jessie

**Comment by cpaasch** [comment]
Ok - thanks. I will keep on digging :)

**Comment by invokablegmbh** [comment]
![screen](https://user-images.githubusercontent.com/3168086/29058067-b53c1684-7c0e-11e7-9ab7-9c0ccba9ed42.jpg)
Using a current version of the "crash" utility, I am able to open the crash dump. If you cannot open it, I can offer you to give you ssh-access to our testing server.

**Comment by cpaasch** [comment]
Ok, figured it out. Was using the wrong command-line... :-) As you say, ```crash``` is the right tool to use.

**Comment by cpaasch** [comment]
Ok, found the reason for the first crash. Will post a patch soon on mptcp-dev.

**Comment by invokablegmbh** [comment]
Nice! :) If there is anything I can do, please cycle back.

**Comment by cpaasch** [comment]
As for the other crash. Are you using CIPSO? There seems to be a bug unrelated to MPTCP.

**Comment by invokablegmbh** [comment]
No. I do not know what that is. If I am using it - I am unaware of it. Maybe it is enabled by default?

**Comment by cpaasch** [comment]
I see - looks like something in the network is sending you a bogus packet, which makes the stack do an out-of-bounds memory read.

Anyways, I sent the patch to mptcp-dev for review. If you want to try it out, feel free.

**Comment by invokablegmbh** [comment]
> I see - looks like something in the network is sending you a bogus packet, which makes the stack do an out-of-bounds memory read.
How should I go on with debugging? Do you have futher infos about the source of this packet?

> Anyways, I sent the patch to mptcp-dev for review. If you want to try it out, feel free.
Thanks a lot. I am compiling a new kernel version right now. Will test it and come back with the results. :) 
However: Thanks for your help & work on mptcp!

**Comment by cpaasch** [comment]
As for debugging the other issue:

We could do something aggressive and I give you patch that makes your host panic when this happens. That gives me a coredump I can analyze to see what brought you in this kind of state.

**Comment by matttbe** [comment]
Applied in both mptcp_trunk and mptcp_v0.92!
