### ISSUE TITLE
Setting interface for primary subflow

### ISSUE THREAD

**Issue by enigmaro** [multipath-tcp/mptcp#192]
I am using MPTCP v0.92 on a Linux machine with fedora 24.

I was wondering if there was a way in which I can explicitly set which interface should be used for the primary subflow at all times? 

Can someone let me know how this can be done if it is possible or point me to the right resource?

**Comment by matttbe** [comment]
Hi!

The kernel will select the interface depending of your IP rules.
Changing your default route should be enough.

Matth

**Comment by enigmaro** [comment]
Thanks Matth, 
I was only wondering if there was some other way to do it apart from changing the default route. If that is how the kernel selects the interface, I will change the default route.

**Comment by hoang-tranviet** [comment]
I think one way to explicitly select the interface without changing the default route is to use the MPTCP socket API by Benjamin.

**Comment by matttbe** [comment]
You can also play with `ip rule` and `ip route` and have more than one routing table.
