### ISSUE TITLE
tcpprobe congestion window

### ISSUE THREAD

**Issue by enigmaro** [multipath-tcp/mptcp#194]
Hi,

I ran the tcpprobe module to look at the congestion window for an iperf3 mptcp session with 2 subflows. I have a few questions regarding the format.

1. Usually tcpprobe has 9 fields, but the tcpprobe that comes with the 4.4.70 mptcp kernel source, logs 11 fields. Were these changes added specifically for the mptcp kernel? If so is there a documentation which specifies what the extra fields that are logged are?

2. I read cpaasch's comment in issue #173 that iperf does not query the right API for the cwnd.  Does tcpprobe give the right information? I do see different window sizes for each of the flows, I just want to know if the information is reliable.

**Comment by cpaasch** [comment]
Hello,

wrt. to your first question: We don't have any changes in tcp_probe made for MPTCP. There were some additions made to tcp_probe in 2013 by upstream Linux.

Yes, the info in tcp_probe is reliable. (on a side-note, might be cool if someone publishes an iperf-fork with proper support for MPTCP.
