### ISSUE TITLE
Transparent MPTCP Gateway Box for NAT Clients

### ISSUE THREAD

**Issue by BuyMeMumACaravan** [multipath-tcp/mptcp#195]
Please mark this issue as a question.

Goal: Encapsulate MPTCP in a router and transparently share the aggregated links to NATed clients

I'm trying to set-up a NAT behind an MPTCP enabled router.

Normally I'd use CONMARK in the iptables to load balance multiple WAN links in the router, but I don't think this will work in an MPTCP scenario.

My question is on how to configure the router so that the NATed clients can leverage MPTCP transparently.
Has anyone been successful in setting up a NAT that can use MPTCP transparently?

![2017-08-09 14_20_35-clipboard](https://user-images.githubusercontent.com/30875741/29140856-ff2cd178-7d19-11e7-884a-ab5a23e1059b.png)

**Comment by cpaasch** [comment]
You will need to configure a transparent proxy, so that the TCP-connections created by the clients will be terminated on the Ubuntu Box and transformed into MPTCP.
