### ISSUE TITLE
How does MPTCP pass the information to the application layer?

### ISSUE THREAD

**Issue by huangchihyang** [multipath-tcp/mptcp#197]
Hi,all
I want to modify the information MPTCP passes to the application layer so that my application can know that MPTCP is running. If it is possible, I would like to know where is it? (mptcp/net/ipv4/tcp.c) or (mptcp/net/mptcp/mptcp_input.c) or other  place?

Thanks.

**Comment by cpaasch** [comment]
You can use the socket-option MPTCP_ENABLED, described at https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP to see if the connection is using MPTCP or not.
