### ISSUE TITLE
Only redundant scheduler works as fallback solution?

### ISSUE THREAD

**Issue by jb-alvarado** [multipath-tcp/mptcp#198]
Hello everyone, 
first I have to say sorry - I'm very new in this material and I have not so deep knowledge in the tcp stuff.

We plan a live stream from a place where we have no stable internet connection, I have test a bit 3g/4g/lte connections and they where not so stable that I trust in them, that they will hold two hours of streaming. 

Now I play a bit with your mptcp, to be able to use two lte sticks as a fallback solution, when one connection goes down the stream continue on the other connection. 
First I had a setup: streaming from a vm to another server, with the redundant scheduler. The test looked good, but then I move from vm to a physical computer and there I always got a kernel panic. So I switch to the default scheduler, but here I had no success with a fallback solution. 

Now I compile the newest Kernel from you on my home pc and I can use again the redundant scheduler. The roundrobin scheduler I can not try at all - I always get the message: "file not found".

My question is now: I'm right, that for my case I only can use the redundant scheduler? And is this scheduler stable enough for live streaming?

And by side maybe a other question to: why I'm always see only one connection with your modified version netstat -m? Is this normal, because it show only one IP. But on the server side I see with tcpdump two different IPs coming in and with iptables I can block one connection and it still continue streaming.

Regards

Jonathan

**Comment by cpaasch** [comment]
@jb-alvarado Wrt to using the default-scheduler, falling back does not work? Can you take a packet-trace? For the round-robin scheduler, that looks like you didn't compile the round-robin scheduler as a module. You should change your kernel-config.

I would recommend you use the default-scheduler. This is the best. The redundant one is for very specific use-cases where you have a thin stream and want to achieve extremely low latency at the cost of high cellular data usage.

netstat -m only shows the MPTCP-connections, not the subflows associated to them.

**Comment by jb-alvarado** [comment]
Thank you for your replay!
No the falling back with the default scheduler is not working. I have done now some tcpdump tests on sender and receiver side. First I found out that when I stream I only get traffic on the default gateway. When I block to default gateway with:
`iptables -A OUTPUT -o wlo1 -j DROP`
as I say the stream breaks, but when I try to re-stream with only the second connection up, I get an DNS error. So I switch my streaming address to IP, open again the first connection and stream again, but this time to the IP, not the DNS name. Now I only get:

```
RTMP_ReadPacket, failed to read RTMP packet header
rtmp://ip:port:/target/mp: Unknown error occurred
```
On  sender side I capture with this tcpdump command:
`tcpdump -i any tcp and dst host example.org and dst port 1234 -nq`

And on receiver side I capture with this:
`tcpdump -i ens3 tcp and dst host localIP and port 1234 -nq`

On both I see that most connection goes over the default gateway from my sender, and after the first connection from my second connection the stream breaks.

**The funniest thing I found out now is: When I switch back to the redundant scheduler and try to stream to the IP address I get the same error. But if I stream to the DNS name it works.**

Is there more infos, you need?

I check also many times, that I have enable the roundrobin module, and it is. You can see my config here:
[mptcp config](https://gist.github.com/jb-alvarado/36c863ec8e82de359c1ff07556884891) 
Can it be that when I clone the repo with **--depth 1** that I don't get all necessary files?

Thank you to for the information about netstat. So I guess I only see my subflow in **/proc/net/mptcp_net/mptcp**?

Jonathan

Edit: I also need to say, that my server to them I stream is a vm on a host where on it runs a firewall. I don't know that this can make problems?! But I don't think it mess something with DNS names...

**Comment by jb-alvarado** [comment]
Finally I found the issue, and the problem was my unknowing... The DNS problem was because my rtmp server only accept specific dns names. That is why I was not able to stream over IP and other DNS names. 

The second problem what related to multipath tcp is, that the default scheduler needs a correct revers dns entry. I didn't know this. 

I correct my rtmp server settings and I also tried a DNS name with correct revers entry and  now both works: streaming over IP and a domain name. 

When this a normal behavior, maybe is good to write it on the mptcp web page, for noobs like me :).

**Comment by jb-alvarado** [comment]
The problem with the missing roundrobin module I could fix to, with:

`sudo insmod /lib/modules/4.4.83.mptcp/kernel/net/mptcp/mptcp_rr.ko`

How come is not available before? Anyway it looks like the the roundrobin is reacting faster when one connection goes down, so maybe is better in my case.
