### ISSUE TITLE
Debian download fails at final step

### ISSUE THREAD

**Issue by barry-zed** [multipath-tcp/mptcp#201]
apt-get install linux-mptcp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-mptcp
root@debian:~#

**Comment by matttbe** [comment]
Hi,

Did you follow all steps from there? http://multipath-tcp.org/pmwiki.php/Users/AptRepository
The file is correctly referenced there: https://dl.bintray.com/cpaasch/deb/dists/jessie/main/binary-amd64/:Packages

Except if you use a i386 OS?

**Comment by barry-zed** [comment]
I am using i386!

Sent from my iPod

On Sep 5, 2017, at 11:25 AM, Matthieu Baerts <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Did you follow all steps from there? http://multipath-tcp.org/pmwiki.php/Users/AptRepository
The file is correctly referenced there: https://dl.bintray.com/cpaasch/deb/dists/jessie/main/binary-amd64/:Packages

Except if you use a i386 OS?

**Comment by matttbe** [comment]
I am going to close this ticket because the APT repo only supports x86_64 arch. (I will add this info in the wiki if it is missing)

For the moment, the only way for you is to switch to x86_64 or compile it manually (not difficult).

**Comment by matttbe** [comment]
(just added a note on the wiki)
