### ISSUE TITLE
Where is the data of the MPTCP pass to the application layer?

### ISSUE THREAD

**Issue by huangchihyang** [multipath-tcp/mptcp#202]
Hi all,
Sorry, the previous question is not clear.
I would like to change the data of MPTCP which will be passed to the application layer, hoping to attach the information of the path's RTT to the application to use, so I would like to ask  where is the upload data of MPTCP ?

Thanks.

**Comment by matttbe** [comment]
Hi @huangchihyang

Sorry I am not sure I understand your question. What is the _data of MPTCP_? The header?

The application doesn't need to be aware about using multiple paths. But it is possible to get some data by using `MPTCP_INFO` getsockopt and also select the PM and scheduler by other setsockopt's: https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP .
https://github.com/obonaventure/mptcp-doc/blob/master/mptcp.rst#socket-api

**Comment by huangchihyang** [comment]
Hi @matttbe 

Sorry for my bad expression

Data of MPTCP refers to the data that MPTCP will send to the application layer.

In general, the application does not have to use two paths. My current research is that the application will make different behaviors on the different paths' condition.

So I hope that some of the MPTCP information, in the data to the application layer transmission, can follow the pass to the application to make judgments.

**Comment by matttbe** [comment]
Hi @huangchihyang

For the moment, it is not possible to control that from the userspace. You can change the PM for one connection, that could help but that's it.
Note that an API socket has been developed[1]. This one can allow you to open and close subflows. Maybe what you need.

[1]
- https://irtf.org/anrw/2016/anrw16-final16.pdf
- http://blog.multipath-tcp.org/blog/html/2016/11/13/multipath_tcp_projects_during_the_ietf97_hackathon.html
- https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2016-10/msg00033.html

**Comment by huangchihyang** [comment]
Hi @matttbe
My research does not  want to control the MPTCP's scheduler, just want to get RTT information from MPTCP, and according to RTT and other network conditions to  send different files.

Thanks for your reply!

**Comment by matttbe** [comment]
If you want to only want to get some info like the RTT, you can use a getsockopt: TCP_INFO for plain TCP and MPTCP_INFO for MPTCP → https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP (_Get detailed information of your subflows_ section)
Then you can look at the info you got from the kernel (mainly the `tcp_info` structures)

**Comment by matttbe** [comment]
I am closing the ticket now because you should have all info you need. Feel free to re-open it if there is a bug ;-)
