### ISSUE TITLE
Measuring MP-TCP Packet Receiving Latency in the Linux Kernel

### ISSUE THREAD

**Issue by ghost** [multipath-tcp/mptcp#204]
I am trying to measure the latency at the MP-TCP receiver side as a difference between the time a packet has entered into the TCP stack and the time it is ready to be consumed by the application. To accomplish this task, I added a new field in the `struct sk_buff` to record the current time stamp in microsecond resolution. I assign a value to this field at the beginning of `tcp_data_queue` function in tcp_input.c file. Then in the `mptcp_data_ready` function in mptcp_input.c file I obtain the current time stamp when the `mptcp_queue_skb` function returns either -1 or -2 (Either the mapping has been put in the meta-receive-queue or the mapping has been eaten by the application). The difference between these two values is the receiving latency which compromises the out-of-order delay or HOL delay. So my question is the location where I get the time stamps is correct for my purpose? I am asking this because sometimes, I get strange values of latency around 800 ms. My setup compromises both Ethernet and Wifi interfaces (Single hop). 

I am particularly interested in measuring the out-of-order delay in different scenarios in my setup. I log my data using printk which I later read from `/var/log/syslog`.

**Comment by matttbe** [comment]
Hi @thegreatencoder

I guess @cpaasch will give you more details about that but could it be possible to share a patch (e.g. you can open a pull request), it is easier to understand what you did.

Note that it could be interesting to compare info using `ss` tools, e.g. to see what is the value of the RTT/RTO. It could be "that slow" if you have losses/bufferbloat.

**Comment by ghost** [comment]
Hi @matttbe,

I have prepared a patch that shows where I put my timestamps and where I am printing them. Attached is the patch file. The patch is done with respect to commit "9400dd6633e20c07212ce2dab92a67ce8b5647ed"

Regarding comparing the values with respect to what is reported by ss. In my case, I am trying to eliminate the buffering effect at the transmitter side and I am just focusing on the latency on the receiver side. More precisely, I want to check how much packets remain in the out-of-order buffer in case one of the links is broken which will have an impact on the latency of the following packets.

[timestamp.patch.tar.gz](https://github.com/multipath-tcp/mptcp/files/1278350/timestamp.patch.tar.gz)

**Comment by cpaasch** [comment]
@thegreatencoder : I think printk can add significant latency to your system and screw your results.

A better way, would be to use perf with dynamic tracing: http://www.brendangregg.com/perf.html#DynamicTracingEg There are some good examples on this website.

As to your other question: By checking on the return-value of ```mptcp_queue_skb```, you won't take the time the data spends in the MPTCP-level reordering queue into account. And I'm guessing that you are particularly interested by this value. A simple way to do this, would be to take a packet-trace (only the TCP-headers) and just compute the difference of the timestamps between when the packet arrives and when the MPTCP ```DATA_ACK``` acknowledges it. I think, ```mptcptrace``` allows to track this. https://bitbucket.org/bhesmans/mptcptrace
