### ISSUE TITLE
uapi: compilation error when user apps include tcp.h

### ISSUE THREAD

**Issue by hoang-tranviet** [multipath-tcp/mptcp#206]
With the addition of struct mptcp_sub_info in include/uapi/linux/tcp.h (commit 0b4d84dffa), when an application uses this header, it also need to include <netinet/in.h>, or the compiler would complain of struct sockaddr as incomplete type.

I don't know if it is better to add this  <netinet/in.h> into include/uapi/linux/tcp.h?

Thanks,
Hoang

**Comment by matttbe** [comment]
Hi Hoang!

I don't know if it is a good idea to add this include to a userspace header in the kernel source. This `netinet/in(6).h` is provided by your libc.

In the kernel, we could maybe add this:

```c
#include <linux/in.h>
#include <linux/in6.h>
```

But I also know that some drivers asked userspace devs to add `<netinet/in.h>` and `<netinet/in6.h>` in their header.

Maybe someone has more experiences with that.

**Comment by cpaasch** [comment]
In ```if.h```, they do:

```
#include <linux/socket.h>               /* for "struct sockaddr" et al  */
```

We can probably do the same. @hoang-tranviet, does this fix the issue if you do this?

**Comment by hoang-tranviet** [comment]
Hi Matthieu, 
You are right. If the user app has included `<netinet/in.h>`, `<netdb.h>`... from libc, then they will conflict with `<linux/in.h>` and `<linux/in6.h>`.

Hi Christoph,
I don't really understand your solution. If you mention about linux/tcp.h, I see it already has
    `#include <linux/socket.h>`
There is a recent patch and discussion for upstreaming Linux [https://lkml.org/lkml/2017/2/21/698](https://lkml.org/lkml/2017/2/21/698), but when I add sys/socket.h to linux/tcp.h, it only fixes sockaddr compiler warning, but not sockaddr_in{6}.

    #ifndef __KERNEL__
    #include <sys/socket.h>			/* for struct sockaddr.		*/
    #endif

Thanks,
Hoang

**Comment by cpaasch** [comment]
@hoang-tranviet, I now did this:

```
diff --git a/include/uapi/linux/tcp.h b/include/uapi/linux/tcp.h
index 6660b87c1aad..1fb9b4af6e40 100644
--- a/include/uapi/linux/tcp.h
+++ b/include/uapi/linux/tcp.h
@@ -17,9 +17,15 @@
 #ifndef _UAPI_LINUX_TCP_H
 #define _UAPI_LINUX_TCP_H

-#include <linux/types.h>
+#ifndef __KERNEL__
+#include <sys/socket.h>
+#endif
+
 #include <asm/byteorder.h>
+#include <linux/in.h>
+#include <linux/in6.h>
 #include <linux/socket.h>
+#include <linux/types.h>

 struct tcphdr {
        __be16  source;
```

This seems to work for me. Can you confirm? I will submit a patch.

**Comment by cpaasch** [comment]
The conflict with ```netinet/in.h``` is fine IMO. Because, there is the same conflict if one include ```netinet/tcp.h``` and ```linux/tcp.h```. As soon as an implementation chooses to include a header from ```linux```, it decides to go the GPL-route and so should not include the ```netinet``` (aka BSD-licensed) headers anymore.

**Comment by hoang-tranviet** [comment]
Hi Christoph,
Your patch worked with my test app.
Thanks for your clarification. It is unfortunate that many existing programs cannot leverage linux facilities.

**Comment by cpaasch** [comment]
Thanks, @hoang-tranviet. I will submit the patch.

**Comment by matttbe** [comment]
Closing: fix now in mptcp_trunk, mptcp_v0.93 and mptcp_v0.92.

Please re-open it if the referenced commit does not fix this issue!
