### ISSUE TITLE
fullmesh path manager

### ISSUE THREAD

**Issue by gyheo** [multipath-tcp/mptcp#211]
I installed MPTCP to Ubuntu 14.04LTS with 4.4.83+ and MPTCP version MPTCP version is 0.92 by kernel build up and install. After that, I can change MPTCP parameter such as net.mptcp.mptcp_debug=1, net.mptcp.mptcp_enabled=1. However, it doesn't work when I change mptcp_path_manager or mptcp_scheduler. I checked net/mptcp and I can find that there are no mptcp_fullmesh.o and mptcp_rr.o. Would someone let me know how can I change the parameter(such as scheduler or path_manager)? Thank you.

**Comment by cpaasch** [comment]
You need to enable these schedulers in your kernel-config. You can find the knobs to enable these next to the option to enable MPTCP in the kernel-config.
