### ISSUE TITLE
Low Latency / RT Kernel Functions

### ISSUE THREAD

**Issue by jb-alvarado** [multipath-tcp/mptcp#212]
Hello,
I just wanted to ask, that somebody have try mptcp in combination with RT features? Or is it risky to apply the RT patch?

I'm interested in this, because of a live streaming setup. I the past we always had a delay between audio and video, coming from decklink sdi cards. And maybe this gets better with an RT kernel. 

When you see no problem in applying the patch, does the patch 4.4.86-rt99 works with mptcp v4.4.83?

Regards,
Jonathan

**Comment by cpaasch** [comment]
As far as I know, nobody has tried MPTCP with the RT-patch. Feel free to try it out and let us know how things go :)
