### ISSUE TITLE
how to use mptcp in user space

### ISSUE THREAD

**Issue by sukkhi** [multipath-tcp/mptcp#217]
I am pretty new to MPTCP & have successfully installed mptcp v-0.92 from multipath-tcp.org.
But I am unable to use MPTCP in user applications.
I am unable to find any of examples or APIs in C programming.

kind help will be appreciated.

**Comment by matttbe** [comment]
Hi sukkhi,

You don't need to modify your apps, MPTCP option will be used by default: http://multipath-tcp.org/pmwiki.php/Users/UseMPTCP

Simply use this command to check you are using MPTCP:

    curl multipath-tcp.org

More info:
http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting
http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

Cheers,
Matt

**Comment by sukkhi** [comment]
Hi matt,
Thanks for reply, need some help again

using command **curl multipath-tcp.org** shows : "Nay, Nay, Nay, your have an old computer that does not speak MPTCP. Shame on you!"

using command **dmesg | grep MPTCP** shows: "MPTCP: Stable release v0.92.2"

also when I try to use "setsockopt(fd, SOL_TCP, MPTCP_ENABLED, &enable, sizeof(enable));"  in c application it shows " error: ‘MPTCP_ENABLED’ undeclared"

**Comment by matttbe** [comment]
Hi Sukkhi,

Please verify that MPTCP is not blocked on your network and you didn't disable it using `sysctl net.mptcp.mptcp_enabled` → http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP
If you take traces with Wireshark / TCPDump, you should see MPTCP option is added in the SYN. Maybe not in the SYN+ACK.
You can also do a `cat /proc/net/mptcp_net/snmp` to get more information.

> also when I try to use "setsockopt(fd, SOL_TCP, MPTCP_ENABLED, &enable, sizeof(enable));" in c application it shows " error: ‘MPTCP_ENABLED’ undeclared"

You are maybe not importing the right header from the new kernel. You can also replace it by the value "42".

> Since release 0.89, you can set mptcp_enabled to 2. In this case MPTCP will be enabled if the application has set the socket-option MPTCP_ENABLED (value 42) to 1. MPTCP_ENABLED is part of SOL_TCP:
> int enable = 1;
> setsockopt(fd, SOL_TCP, 42, &enable, sizeof(enable));

**Comment by sukkhi** [comment]
Hi mattbe,

After installing MPTCP :  "**/usr/src/linux-headers-4.4.88.mptcp**" directory was created and after using **grep** command "MPTCP_ENABLED" was found in tcp.h in linux-headers-4.4.88.mptcp.

no user space headers were found in /usr/include

C code compiled successfully after replacing MPTCP_ENABLED with 42. But I want to use exact header file in my C code so that all macros can be used. How could I get the exact header file???

**Comment by matttbe** [comment]
Hi Sukkhi,

I guess you need to configure your CFLAGS to add `-I/usr/src/linux-headers-4.4.88.mptcp/include/uapi` and add `#include <linux/tcp.h>` in your code but that's a common "problem" when testing new kernel features (refs that are not in netinet's libC).
