### ISSUE TITLE
How to use the socket-option ?

### ISSUE THREAD

**Issue by huangchihyang** [multipath-tcp/mptcp#222]
I use the MPTCPv0.92, want to get the RTT of each path,to the application to judge to make a different behavior, the previous answer is to use socket-option, but how to use socket-option ?
Is there a detailed instructions for use? 
Is the code to be added here?  net / mptcp / mptcp_ctrl.c

I have seen the instructions in http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP, but I still have no idea...

**Comment by matttbe** [comment]
Hi,

The application has to use getsockopt option to get info about the subflows.

There is an example on the weblink you shared, see section _Get detailed information of your subflows_.
Of course you need to `#include` the right file. Example there: https://github.com/multipath-tcp/mptcp/issues/217#issuecomment-339590732
