### ISSUE TITLE
Low download bandwidth

### ISSUE THREAD

**Issue by virus-atl** [multipath-tcp/mptcp#223]
systems params:
net.mptcp.mptcp_checksum = 0
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 15
net.mptcp.mptcp_version = 0
net.ipv4.tcp_congestion_control = olia/lia/balia/cubic/veno (tested all)

mptcp_versions: 0.93 rc, 0.92.2 tested both.

client:
lte0: upload/download:6/9 mbps, ping(to server): 45 ms
lte1: upload/download:4/6 mbps, ping(to server): 21 ms
lte2: upload/download:5/6 mbps, ping(to server): 38 ms
eth0: upload/download:85/85 mbps, ping(to server): 5 ms

server:
eth0: upload/download:100/100 mbps

iperf with 3x lte:

(download from server)
iperf3 -c 91.237.189.18 -P 1 -i 5 -t 60 -R
Connecting to host 91.237.189.18, port 5201
Reverse mode, remote host 91.237.189.18 is sending
[  4] local 100.104.200.222 port 52822 connected to 91.237.189.18 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-5.00   sec  10.1 MBytes  16.9 Mbits/sec
[  4]   5.00-10.00  sec  12.1 MBytes  20.2 Mbits/sec
[  4]  10.00-15.00  sec  8.90 MBytes  14.9 Mbits/sec
[  4]  15.00-20.00  sec  9.25 MBytes  15.5 Mbits/sec
[  4]  20.00-25.00  sec  10.6 MBytes  17.8 Mbits/sec
[  4]  25.00-30.00  sec  12.5 MBytes  20.9 Mbits/sec
[  4]  30.00-35.00  sec  13.7 MBytes  22.9 Mbits/sec
[  4]  35.00-40.00  sec  14.4 MBytes  24.2 Mbits/sec
[  4]  40.00-45.00  sec  14.8 MBytes  24.9 Mbits/sec
[  4]  45.00-50.00  sec  15.1 MBytes  25.3 Mbits/sec
[  4]  50.00-55.00  sec  15.5 MBytes  26.0 Mbits/sec
[  4]  55.00-60.00  sec  14.7 MBytes  24.6 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec   162 MBytes  22.6 Mbits/sec    0   sender
[  4]   0.00-60.00  sec   152 MBytes  21.2 Mbits/sec        receiver

(upload to server)
iperf3 -c 91.237.189.18 -P 1 -i 5 -t 60
Connecting to host 91.237.189.18, port 5201
[  4] local 100.104.200.222 port 52826 connected to 91.237.189.18 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-5.00   sec  12.6 MBytes  21.2 Mbits/sec    0   13.8 KBytes
[  4]   5.00-10.00  sec  10.0 MBytes  16.8 Mbits/sec    0   13.8 KBytes
[  4]  10.00-15.00  sec  11.2 MBytes  18.9 Mbits/sec    0   13.8 KBytes
[  4]  15.00-20.00  sec  10.0 MBytes  16.8 Mbits/sec    0   13.8 KBytes
[  4]  20.00-25.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  25.00-30.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  30.00-35.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  35.00-40.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  40.00-45.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  45.00-50.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  50.00-55.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
[  4]  55.00-60.00  sec  8.75 MBytes  14.7 Mbits/sec    0   13.8 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec   114 MBytes  15.9 Mbits/sec    0    sender
[  4]   0.00-60.00  sec   110 MBytes  15.4 Mbits/sec         receiver

As we see, all ok and lte speed aggregate.

iperf with 3x lte + eth0:
I expect speed minimum as eth0.

(download from server)
 iperf3 -c 91.237.189.18 -P 1 -i 5 -t 60 -R
Connecting to host 91.237.189.18, port 5201
Reverse mode, remote host 91.237.189.18 is sending
[  4] local 100.104.200.222 port 52840 connected to 91.237.189.18 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-5.00   sec  31.2 MBytes  52.3 Mbits/sec
[  4]   5.00-10.00  sec  35.1 MBytes  58.9 Mbits/sec
[  4]  10.00-15.00  sec  31.5 MBytes  52.9 Mbits/sec
[  4]  15.00-20.00  sec  30.9 MBytes  51.9 Mbits/sec
[  4]  20.00-25.00  sec  24.8 MBytes  41.5 Mbits/sec
[  4]  25.00-30.00  sec  29.0 MBytes  48.6 Mbits/sec
[  4]  30.00-35.00  sec  30.0 MBytes  50.4 Mbits/sec
[  4]  35.00-40.00  sec  31.2 MBytes  52.4 Mbits/sec
[  4]  40.00-45.00  sec  25.7 MBytes  43.1 Mbits/sec
[  4]  45.00-50.00  sec  27.7 MBytes  46.5 Mbits/sec
[  4]  50.00-55.00  sec  27.7 MBytes  46.4 Mbits/sec
[  4]  55.00-60.00  sec  40.0 MBytes  67.0 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec   377 MBytes  52.6 Mbits/sec    0    sender
[  4]   0.00-60.00  sec   365 MBytes  51.0 Mbits/sec         receiver

(upload to server)
iperf3 -c 91.237.189.18 -P 1 -i 5 -t 60
Connecting to host 91.237.189.18, port 5201
[  4] local 100.104.200.222 port 52848 connected to 91.237.189.18 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-5.04   sec  52.4 MBytes  87.2 Mbits/sec    0   13.8 KBytes
[  4]   5.04-10.00  sec  43.8 MBytes  73.9 Mbits/sec    0   13.8 KBytes
[  4]  10.00-15.03  sec  47.5 MBytes  79.2 Mbits/sec    0   13.8 KBytes
[  4]  15.03-20.02  sec  51.2 MBytes  86.2 Mbits/sec    0   13.8 KBytes
[  4]  20.02-25.04  sec  50.0 MBytes  83.6 Mbits/sec    0   13.8 KBytes
[  4]  25.04-30.00  sec  51.2 MBytes  86.6 Mbits/sec    0   13.8 KBytes
[  4]  30.00-35.08  sec  51.2 MBytes  84.6 Mbits/sec    0   13.8 KBytes
[  4]  35.08-40.08  sec  53.8 MBytes  90.2 Mbits/sec    0   13.8 KBytes
[  4]  40.08-45.06  sec  51.2 MBytes  86.2 Mbits/sec    0   13.8 KBytes
[  4]  45.06-50.01  sec  51.2 MBytes  86.9 Mbits/sec    0   13.8 KBytes
[  4]  50.01-55.02  sec  50.0 MBytes  83.8 Mbits/sec    0   13.8 KBytes
[  4]  55.02-60.05  sec  53.8 MBytes  89.7 Mbits/sec    0   13.8 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.05  sec   607 MBytes  84.9 Mbits/sec    0   sender
[  4]   0.00-60.05  sec   602 MBytes  84.1 Mbits/sec        receiver

Results: Upload speed looks ok, but download not! Why?

tcpdumps and sysctl attached.

[sysctl.zip](https://github.com/multipath-tcp/mptcp/files/1430016/sysctl.zip)
tcpdump.rar - http://rgho.st/6qkVttLh7

**Comment by suyuan168** [comment]
me too https://github.com/multipath-tcp/mptcp/issues/334

**Comment by matttbe** [comment]
For those here who are using more than 2 subflows and see issues when one subflow is bad, could you please look at my last message in #334 ?

**Comment by cpaasch** [comment]
No feedback - closing.
