### ISSUE TITLE
Can not establish connection when the default route is blocked

### ISSUE THREAD

**Issue by jiqi1987** [multipath-tcp/mptcp#224]
Hi,
I am using MPTCP on some of our datacenters which has three interfaces on three different ISPs. The use case is sometimes one or two of the ISPs will block all traffic to our datacenters in other countries (yes I am in China), so I want MPTCP to dynamically pick a path that is not blocked. It works like dream except for one major issue, if the default route is blocked, the connection can not be established in the first place, because the first SYC packet won't arrive.
One possible solution is maybe when establishing connections, try not only from the default route but from all subflows?
Does MPTCP have this option?

Thanks,
Qi Ji

**Comment by matttbe** [comment]
Hi @jiqi1987 

> Does MPTCP have this option?

No, MPTCP (or TCP, UDP, any other protocols on top of IP) will look at your routing tables to know where to send packets. Note that you can also play with different routes and different metrics.
I don't know how some IPs are blocked, maybe adding different _default_ routes with different metrics is not enough.

Matt
