### ISSUE TITLE
Lot's of mptcp_fallback_infinite in kernel log

### ISSUE THREAD

**Issue by ualtinok** [multipath-tcp/mptcp#225]
Hello,

We're using 4.9.60.mptcp kernel instaled on ubuntu 16.04 with apt install mptcp,

We're using the box as a router and it has 3 interface, 2 for uplink 1 for local network. The routes are set properly but we're not seeing any traffic going other than the default route. 

In kernel logs of both client and server there's a constant flow of logs like:
**Client:**
TCP: mptcp_fallback_infinite 0xe409f6b4 will fallback - pi 1, src 58.x.x.x:36990 dst 27.x.x.x:443 rcv_nxt 3842296416 from tcp_rcv_established+0x109/0x620
**Server:**
TCP: mptcp_fallback_infinite 0x3edbdbbd will fallback - pi 1, src 27.x.x.x:443 dst 58.x.x.x:45432 rcv_nxt 3451123255 from tcp_rcv_established+0x109/0x620

What can be the cause of this?

Thanks

**Comment by cpaasch** [comment]
Hello @ualtinok.

Can you grab a packet-trace and capture one of these? The port-numbers should allow to easily idenitfy the flow. Please share this packet-trace (you can anonymize it if you want).

Thanks,
Christoph

**Comment by ualtinok** [comment]
I've sent pcap file to your gmail, I hope that is ok.

**Comment by cpaasch** [comment]
Closing as of e-mail discussion.
