### ISSUE TITLE
Fast Path Burst behavior when RTT is different

### ISSUE THREAD

**Issue by VMatrix1900** [multipath-tcp/mptcp#229]
Hi:
I found a weird behavior when RTT of 2 subflows are different. The topology setup is as follows:
![topology_setup](https://user-images.githubusercontent.com/3964947/32823335-738ce7b8-c9a2-11e7-9a15-28aecb3dff0c.jpg)

both receiver and sender runs mptcp 0.92, default scheduler, cubic congestion control. Using iPerf3 to test the throughput.
I use TC in router to configure the latency and bandwidth of path1 and path2.
Path1: 30Mbit, 20ms, 0.01%(Fast path)
Path2: 30Mbit, 200ms, 0.01%(Slow path)
The receive buffer and send buffer is set to 6M

Then I find packets sent from fast path is bursty when the Path2's RTT is bigger than Path1. See burst-20-200.png and no-burst-20-20.png.
![burst_20-200](https://user-images.githubusercontent.com/3964947/32823346-7e01ec02-c9a2-11e7-8b86-f4a65034e49b.png)
![no-bust-20-20](https://user-images.githubusercontent.com/3964947/32823367-8e67b8c4-c9a2-11e7-9489-6c600622ff24.png)
Digging in, I find that the burst sending pattern is caused by ACK from fast path. Sometimes, ACK from fastpath will acknowledge many packets. See below, the ACK jumps from 64577054(Packet No. 106269) to 64689866(Packet No. 106275).
<img width="1436" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/3964947/32823408-bbae4096-c9a2-11e7-9611-6fa9abf7f95d.png">

From the pcap file captured on receiver side, there is no ack between 64577054 and 64689866 sent from fastpath(see noack1.jpg and noack2.jpg)
![noack1](https://user-images.githubusercontent.com/3964947/32823432-cd95a48e-c9a2-11e7-8fc5-e80ca92f494b.jpg)

![noack2](https://user-images.githubusercontent.com/3964947/32823433-ce499f8e-c9a2-11e7-8e5d-f66ae921ea2d.jpg)

As you can see from the screenshots, between 64577054 and 64689866, there are many packets from the fastpath arrives but no ACK is generated. This violates the ack-every-two-segement requirement specified by RFC 5861:

> The delayed ACK algorithm specified in [RFC1122] SHOULD be used by a
 TCP receiver.  When using delayed ACKs, a TCP receiver MUST NOT
 excessively delay acknowledgments.  Specifically, an ACK SHOULD be
 generated for at least every second full-sized segment, and MUST be
 generated within 500 ms of the arrival of the first unacknowledged
 packet.

Why is that happening?

When I change the path2 RTT to 20ms, then there is no burst,no ACK jump, etc.

And I also find that the ACK jump on fast path always follows the data ACK jump when RTT of 2 path is different.

It seems like the fast path delays the ACK until the MP-level window slides. But the MP-level window and subflow-level window should slide separately. So the subflow ACK behavior shouldn't change when another path RTT changes, right? But that is not what I see.

The pcap files captured in sender and receiver are in https://www.dropbox.com/sh/amo6vbiaez702dw/AAD94xsNoOZkNagdPgMWR9usa?dl=0.

**Comment by cpaasch** [comment]
Closing - let's discuss on the mptcp-dev mailing list.
