### ISSUE TITLE
a simple startup guide

### ISSUE THREAD

**Issue by rijujohnx** [multipath-tcp/mptcp#232]
Is there a simple guide to test out mptcp on a virtualbox?
I tried following on 
https://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP?

mptcp is enabled.  Copied the rt_table scripts.  I still haven't managed to use mptcp according to the http://amiusingmptcp.de/ website.

**Comment by cpaasch** [comment]
Hello,

Virtual box typically sets up the networking in NAT mode. In NAT mode, the host will strip the MPTCP options.

You have to set things up in bridge-mode.


Christoph

**Comment by rijujohnx** [comment]
@cpaasch   Thank you.  That worked.
