### ISSUE TITLE
create_on_err =1  reset after reboot

### ISSUE THREAD

**Issue by kapook007** [multipath-tcp/mptcp#233]
hello
i have some problem .
when i set nano /sys/module/mptcp_fullmesh/parameters/create_on_err to 1.
after reboot create_on_err reset to 0 !!!.

How to permanent fix create_on_err=1 at startup ?

debain 64bit .
thanks.

**Comment by madhanraj** [comment]
static int create_on_err __read_mostly = 1;

in mptcp_fullmesh.c would do .. or else u can add in the init script ..

**Comment by kapook007** [comment]
thank you  >> madhanraj
