### ISSUE TITLE
patch version for mptcp changes over linux 4.4.x

### ISSUE THREAD

**Issue by rijujohnx** [multipath-tcp/mptcp#234]
is there a diff I can use as a patch over the linux baseline for mptcp changes alone?
I intend to patch two variants on top of linux baseline 4.4.x
I already have patch A on top of 4.4.x
I intend to apply mptcp patch on top of this change.

**Comment by matttbe** [comment]
Hi @rijujohnx 

Current MPTCP v0.92 version is based on v4.4.110: https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.92/Makefile

You can then create a MPTCP patch using:

```bash
git diff v4.4.110..mptcp_v0.92
```

You can also find patches there: http://multipath-tcp.org/patches/

(closing the ticket, feel free to re-open if needed)
