### ISSUE TITLE
please add Debian stretch

### ISSUE THREAD

**Issue by colttt** [multipath-tcp/mptcp#235]
Hello,

it would be nice if you add a Debian Stretch repo

**Comment by cpaasch** [comment]
Indeed. I will deprecate Jessie and instead do a Stretch repo.

**Comment by D4rk4** [comment]
Any progress?

**Comment by cpaasch** [comment]
Yes - v0.94 is now built on Stretch (https://bintray.com/cpaasch/deb/mptcp/v0.94?sort=&order=)

**Comment by D4rk4** [comment]
@cpaasch 
```
E: Failed to fetch https://dl.bintray.com/cpaasch/deb/dists/stretch/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by cpaasch** [comment]
Hmm... works for me.

**Comment by cpaasch** [comment]
You are on debian stretch ?

**Comment by D4rk4** [comment]
```
root@route-gra:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
root@route-gra:~# 

```

**Comment by berezoka** [comment]
for me no any problems with Stretch repo

**Comment by cpaasch** [comment]
@D4rk4 maybe do an ```apt-get autoremove```, ```apt-get autoclean``` to make sure there are no caches messing things up.

**Comment by D4rk4** [comment]
@cpaasch Now I test on fresh installed server, all working fine.
