### ISSUE TITLE
TCP throughput stalls when the Sender uses fullmesh path manager (mptcp_verif_dss_csum csum is wrong)

### ISSUE THREAD

**Issue by kpeletidis** [multipath-tcp/mptcp#236]
The following issue was seen when testing mptcp release 0.93. When the Sender uses the fullmesh path manager the Receiver reports checksum errors and TCP throughput stalls (i.e. the server and client instances of nc do not exit as they normally do when the connection is closed). This can happen as soon as the traffic starts but it usually happens within the first minute of TCP activity. After running tens of tests, only once the traffic was not affected by the reported errors. In that case two of the interfaces went idle and all traffic was routed through the remaining interface. In all cases throughput was a stable 1Gbps and both machines were connected to the same 1Gbps switch.

This error was not seen whenever the default path manager was used by the Sender.

**Dmesg output on the Receiver side (mptcp_debug = 1)**
---------------------------------------------
[  569.536009] net/mptcp/mptcp_ctrl.c: mptcp_alloc_mpcb: created mpcb with token 0x48857427
[  569.536027] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0x48857427 pi 1, src_addr:10.99.99.93:9090 dst_addr:10.99.99.110:36964, cnt_subflows now 1
[  569.536720] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0x48857427 pi 2, src_addr:10.99.99.93:9090 dst_addr:10.99.99.133:46649, cnt_subflows now 2
[  569.536978] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0x48857427 pi 3, src_addr:10.99.99.93:9090 dst_addr:10.99.99.132:37467, cnt_subflows now 3
**[  680.216061] mptcp_verif_dss_csum csum is wrong: 0x100 data_seq 3410980118 dss_csum_added 1 overflowed 0 iterations 1**
[  680.216108] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0x48857427 pi:1 state 7 is_meta? 0
**[  680.216229] mptcp_verif_dss_csum csum is wrong: 0x100 data_seq 1781035747 dss_csum_added 1 overflowed 0 iterations 1
[  680.216271] mptcp_verif_dss_csum csum is wrong: 0x100 data_seq 1501106925 dss_csum_added 1 overflowed 0 iterations 1**
[  680.216382] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0x48857427 pi:3 state 7 is_meta? 0
[  680.216385] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0x48857427 pi:2 state 7 is_meta? 0
[  707.169584] net/mptcp/mptcp_ctrl.c: mptcp_close: Close of meta_sk with tok 0x48857427
[ 1041.372151] net/mptcp/mptcp_ctrl.c: mptcp_sock_destruct destroying meta-sk

**Dmesg output on the Sender side (mptcp_debug = 1)**
--------------------------------------------
[  530.449310] net/mptcp/mptcp_fullmesh.c: addr4_event_handler created event for 10.99.99.110, code 1 prio 0
[  530.449316] net/mptcp/mptcp_fullmesh.c: addr4_event_handler created event for 10.99.99.133, code 1 prio 0
[  530.449318] net/mptcp/mptcp_fullmesh.c: addr4_event_handler created event for 10.99.99.132, code 1 prio 0
[  530.449321] fullmesh registered
[  565.609338] net/mptcp/mptcp_ctrl.c: mptcp_alloc_mpcb: created mpcb with token 0xa6fc17e6
[  565.609362] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6fc17e6 pi 1, src_addr:10.99.99.110:36964 dst_addr:10.99.99.93:9090, cnt_subflows now 1
[  565.609695] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6fc17e6 pi 2, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 2
[  565.609704] net/mptcp/mptcp_ipv4.c: mptcp_init4_subsockets: token 0xa6fc17e6 pi 2 src_addr:10.99.99.133:0 dst_addr:10.99.99.93:9090 ifidx: 3
[  565.609775] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6fc17e6 pi 3, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 3
[  565.609779] net/mptcp/mptcp_ipv4.c: mptcp_init4_subsockets: token 0xa6fc17e6 pi 3 src_addr:10.99.99.132:0 dst_addr:10.99.99.93:9090 ifidx: 4
[  676.288036] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0xa6fc17e6 pi:1 state 7 is_meta? 0
[  676.288317] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0xa6fc17e6 pi:3 state 7 is_meta? 0
[  676.288495] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0xa6fc17e6 pi:2 state 7 is_meta? 0
[  700.718439] net/mptcp/mptcp_ctrl.c: mptcp_close: Close of meta_sk with tok 0xa6fc17e6
[  785.362795] net/mptcp/mptcp_ctrl.c: mptcp_sock_destruct destroying meta-sk

**Test description**
-------------------
Start server on the Receiver

Start client on the Transmitter (Ctrl-c)

Receiver reports checksum errors like the following message:

mptcp_verif_dss_csum csum is wrong: 0x100 data_seq 3410980118 dss_csum_added 1 overflowed 0 iterations 1

Throughput stall occurs

Stop client on the Transmitter

Stop server on the Receiver (Ctrl-c)

**Receiver Setup**
-------------------
kp@fred:~$ cat /proc/sys/net/mptcp/mptcp_scheduler 
default

kp@fred:~$ cat /proc/sys/net/mptcp/mptcp_path_manager
default

kp@fred:~$ ip route show
default via 10.99.99.254 dev eth0 proto static 
10.99.99.0/24 dev eth0 proto kernel scope link src 10.99.99.93 
169.254.0.0/16 dev eth0 scope link metric 1000 

kp@fred:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:27:13:b1:59:ce brd ff:ff:ff:ff:ff:ff
    inet 10.99.99.93/24 brd 10.99.99.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::227:13ff:feb1:59ce/64 scope link 
       valid_lft forever preferred_lft forever
3: wwan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 02:80:37:ec:02:00 brd ff:ff:ff:ff:ff:ff

kp@fred:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:27:13:b1:59:ce brd ff:ff:ff:ff:ff:ff
3: wwan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 02:80:37:ec:02:00 brd ff:ff:ff:ff:ff:ff

$ nc -l -p 9090 >/dev/null

**Sender Setup**
-------------------
kp@bob:~$ cat /proc/sys/net/mptcp/mptcp_scheduler
default

kp@bob:~$ cat /proc/sys/net/mptcp/mptcp_path_manager
fullmesh

kp@bob:~$ ip route show
default via 10.99.99.254 dev eth0 
10.99.99.0/24 dev eth0 proto kernel scope link src 10.99.99.110 
10.99.99.0/24 dev eth1 proto kernel scope link src 10.99.99.132 
10.99.99.0/24 dev eth2 proto kernel scope link src 10.99.99.133 
169.254.0.0/16 dev eth0 scope link metric 1000 

kp@bob:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 74:85:2a:39:71:e4 brd ff:ff:ff:ff:ff:ff
    inet 10.99.99.110/24 brd 10.99.99.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7685:2aff:fe39:71e4/64 scope link 
       valid_lft forever preferred_lft forever
3: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 8c:ae:4c:ff:81:23 brd ff:ff:ff:ff:ff:ff
    inet 10.99.99.133/24 brd 10.99.99.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::8eae:4cff:feff:8123/64 scope link 
       valid_lft forever preferred_lft forever
4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:ee:22:aa:72:d2 brd ff:ff:ff:ff:ff:ff
    inet 10.99.99.132/24 brd 10.99.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::2ee:22ff:feaa:72d2/64 scope link 
       valid_lft forever preferred_lft forever

kp@bob:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 74:85:2a:39:71:e4 brd ff:ff:ff:ff:ff:ff
3: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 8c:ae:4c:ff:81:23 brd ff:ff:ff:ff:ff:ff
4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:ee:22:aa:72:d2 brd ff:ff:ff:ff:ff:ff

$ nc 10.99.99.93 9090 </dev/zero >/dev/null

More information can be provided if needed.

**Comment by cpaasch** [comment]
Does your build include the commit f2a4860dc697 ("mptcp: Update 64-bit receiver indexes after processing ofo-queue") ? It fixes the checksum-issue.

**Comment by kpeletidis** [comment]
Thank you Christoph. I switched from v0.93 to v0.93.1 which has the commit you mentioned. I then left the throughput test running for 16 hours and no csum errors were seen. Issue solved.
