### ISSUE TITLE
Cannot create subflow with MPTCP v0.93.1

### ISSUE THREAD

**Issue by yuecui** [multipath-tcp/mptcp#238]
Hi, all,
I'm doing an experiment with MPTCP v 0.93.1. I downloaded the kernel from git hub and compiled with the instruction (https://multipath-tcp.org/pmwiki.php/Users/DoItYourself). I have checked with both `dmesg | grep MPTCP` and `curl http://multipath-tcp.org`. Both indicated that I have successfully installed MPTCP.
The experiment is to send live video stream from a laptop to AWS using multipath tcp connection so that the video transmission will be consistent. 
I'm using a laptop with 3 interfaces and two of them are using  WiFi connections and one is using OLSR connection. And I have a host running on AWS with MPTCP v 0.92 installed. I use `bmon` to monitor the network flows. 
However, when I run the program, there's always only one connection created. If I disable the current connection, the transmission would fail. What I'm expecting is all three interfaces sending packets together and disabling one would not affect the transmission. I'm using a default path_manager and a default scheduler for MPTCP and I have set mptcp_enabled to be 1.

Attached are messages from `dmesg`, `ifconfig`, `ping` and` ip rule`. 
- `dmesg`: 
```
[ 6517.512446] net/mptcp/mptcp_ctrl.c: mptcp_alloc_mpcb: created mpcb with token 0xc80e66bb
[ 6517.512514] net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xc80e66bb pi 1, src_addr:192.168.3.71:45317 dst_addr:18.220.247.238:1883, cnt_subflows now 1
[ 6534.825372] net/mptcp/mptcp_ctrl.c: mptcp_close: Close of meta_sk with tok 0xc80e66bb
[ 6534.860095] net/mptcp/mptcp_ctrl.c: mptcp_del_sock: Removing subsock tok 0xc80e66bb pi:1 state 7 is_meta? 0
[ 6534.860106] net/mptcp/mptcp_ctrl.c: mptcp_sock_destruct destroying meta-sk
```
- `ifconfig`
```
lab@lab-VPCCW2DGX:$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:24:be:c4:a3:fe  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:18 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:24016 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24016 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1292299 (1.2 MB)  TX bytes:1292299 (1.2 MB)

wlan0     Link encap:Ethernet  HWaddr c0:25:e9:1c:e6:63  
          inet addr:192.168.3.71  Bcast:192.168.3.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2286 errors:0 dropped:452 overruns:0 frame:0
          TX packets:44 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:906815 (906.8 KB)  TX bytes:9397718 (9.3 MB)

wlan1     Link encap:Ethernet  HWaddr 00:0f:60:0a:24:8b  
          inet addr:192.168.43.55  Bcast:192.168.43.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8126 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8616 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6797083 (6.7 MB)  TX bytes:7597153 (7.5 MB)

wlan2     Link encap:Ethernet  HWaddr 00:0e:8e:39:af:7b  
          inet addr:172.17.68.79  Bcast:172.17.71.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9061 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11482 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3734744 (3.7 MB)  TX bytes:9963219 (9.9 MB)
```
- `ping`
```
lab@lab-VPCCW2DGX:~$ ping -c1 -I wlan0 www.google.com
PING www.google.com (216.58.217.132) from 192.168.3.71 wlan0: 56(84) bytes of data.
64 bytes from iad23s43-in-f4.1e100.net (216.58.217.132): icmp_seq=1 ttl=50 time=25.3 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 25.361/25.361/25.361/0.000 ms
```
```
lab@lab-VPCCW2DGX:~$ ping -c1 -I wlan1 www.google.com
PING www.google.com (216.58.217.132) from 192.168.43.55 wlan1: 56(84) bytes of data.
64 bytes from iad23s43-in-f132.1e100.net (216.58.217.132): icmp_seq=1 ttl=49 time=352 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 352.453/352.453/352.453/0.000 ms
```
```
lab@lab-VPCCW2DGX:~$ ping -c1 -I wlan2 www.google.com
PING www.google.com (209.85.201.103) from 172.17.68.79 wlan2: 56(84) bytes of data.
64 bytes from qu-in-f103.1e100.net (209.85.201.103): icmp_seq=1 ttl=46 time=18.2 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 18.221/18.221/18.221/0.000 ms
```
- `ip rule`
```
lab@lab-VPCCW2DGX:~$ ip rule
0:	from all lookup local 
32763:	from 172.17.68.79 lookup 3 
32764:	from 192.168.43.55 lookup 2 
32765:	from 192.168.3.71 lookup 1 
32766:	from all lookup main 
32767:	from all lookup default 

```
Please let me know if I miss any steps!  Any help would be appreciated!

**Comment by cpaasch** [comment]
Hello, can you collect a packet-trace of such a connection and share it with us? Thanks!

**Comment by yuecui** [comment]
@cpaasch Hi, thank you for your quick reply!
What tool should I use for packet-trace? Can I use wireshark?

**Comment by cpaasch** [comment]
tcpdump is probably best: "tcpdump -i any -n -w dump.pcap"

If you manage to capture the trace on wireshark and safe it, it's fine as well.

**Comment by yuecui** [comment]
[dump.pcap.zip](https://github.com/multipath-tcp/mptcp/files/1676392/dump.pcap.zip)

**Comment by yuecui** [comment]
@cpaasch I have attached the file.

**Comment by cpaasch** [comment]
Hmmm... This is weird... Have you configured the fullmesh path-manager? Can you show the output of "cat /proc/net/mptcp/fullmesh" ?

**Comment by yuecui** [comment]
@cpaasch I don't have this file. But I have done `sysctl -w net.mptcp.mptcp_path_manager = default`.

**Comment by cpaasch** [comment]
You need to choose the fullmesh path-manager:

```sysctl -w net.mptcp.mptcp_path_manager=fullmesh```. Make sure you compiled it in as well.

(under https://multipath-tcp.org/pmwiki.php/Users/DoItYourself, see "Choose a path-manager...")

**Comment by yuecui** [comment]
@cpaasch I think I have included path-manager when I complied it. But I will try again. Thank you for your help!

**Comment by yuecui** [comment]
Hello, I just compiled the kernel again and MPTCP is working now. Thank you for your help! But I still have some concerns.: 
1, When I first compiled the kernel, I compiled it with default path-manager and later I was not able to change it to fullmesh with `sysctl` in a running terminal which causing the above errors. Do I really have to set fullmesh as default when I compile it?  
2, Right now I can switch from different interfaces with no delay. But when I look at with `bmon`, which monitors the current bandwidth of all interfaces, only one interface has transmitting speed, the rest are no speed or with little speed. Is this the correct result? I think the sub-flows are correctly created. I remembered when I used MPTCP v0.89, all the interfaces are sending packets simultaneously and I could see that all the interfaces have a transmitting speed. I was using a pre-compiled kernel , so now I'm confused of which one should be the correct way of monitoring MPTCP connections?

**Comment by cpaasch** [comment]
Wrt. to comment 1): I just double-check on the mptcp_v0.94-branch and it is working correctly there. Did you compile the fullmesh path-manager as a module or statically into the kernel?

Wrt. to comment 2): It all depends on whether you hit a bottleneck. Can you take a pcap on the sender-side? That would allow to see more.

**Comment by yuecui** [comment]
Hi, I compiled it statically into the kernel. I didn't do it as a module.
And I have attached the latest `pcap`.  
[mptcp_0130.pcap.zip](https://github.com/multipath-tcp/mptcp/files/1680408/mptcp_0130.pcap.zip) 
Based on the performance in the experiment, I think this is what I expected. I'm just wondering if this is the correct result. 
I really appreciate your generous help. Thanks.

**Comment by cpaasch** [comment]
Ok, I can reproduce the issue. I will be working on a fix for you.

**Comment by cpaasch** [comment]
Hmmm... Can't reproduce anymore. Not sure what I was seeing late last night...

I wonder if there is some weird interaction when we bind the subflows to a device...

**Comment by yuecui** [comment]
Do you need me to provide more information?maybe another pcap file?

**Comment by cpaasch** [comment]
Can you apply the debug-patch I posted on mptcp-dev and then enable debugging with "sysctl -w net.mptcp.mptcp_debug=1", reproduce the problem and show the output of dmesg ? Thanks!

**Comment by yuecui** [comment]
[mptcp_0212.pcap.zip](https://github.com/multipath-tcp/mptcp/files/1718253/mptcp_0212.pcap.zip)
Hi, I have attached a new `pcap` file. Thanks.

**Comment by cpaasch** [comment]
As I mentioned above, for further debugging I would need the output of dmesg with mptcp_debug enabled and the debugging-patch (which has now been pushed to the git repos). Thanks!

**Comment by yuecui** [comment]
[dmesg.log.zip](https://github.com/multipath-tcp/mptcp/files/1718313/dmesg.log.zip)
Will this work?

**Comment by matttbe** [comment]
Hi @yuecui,

> Will this work?

Almost: that's the kind of output we want but we would need you to do the same steps after having installed the latest version.

Could you then recompile the kernel using the latest version of the branch `mptcp_v0.93`? https://github.com/multipath-tcp/mptcp/tree/mptcp_v0.93

If you downloaded the sources by cloning the repo with Git, simply launch `git pull`. You can also download the new version in a zip file using this link: https://github.com/multipath-tcp/mptcp/archive/mptcp_v0.93.zip

**Comment by cpaasch** [comment]
@yuecui - do you have an update? Thanks!

**Comment by yuecui** [comment]
Actually, I've been having trouble reinstalling mptcp onto my laptop. I have tried v0.93.0, 0.93.1,0.94. I 
can see that MPTCP is boosted from dmesg everytime, but when I curl http://multipath-tcp.org, it always says no.

**Comment by cpaasch** [comment]
You probably have a middlebox that is removing MPTCP options. You can check that by taking a packet-trace while creating an MPTCP connection and looking at the TCP-options in the headers.

**Comment by yuecui** [comment]
It was indeed caused by a middle box problem. I run the tests in a local environment with version v 0.94 and it was working fine. I can see all the interfaces with a transmitting speed. Thank you! Please close the issue.
By the way, do you know how to avoid this middle box problem?

**Comment by cpaasch** [comment]
@yuecui - you should take to your network operator and ask him to get rid of the middlebox :)
