### ISSUE TITLE
Use https link in repo description

### ISSUE THREAD

**Issue by unkaktus** [multipath-tcp/mptcp#240]
There is plain http:// one at the moment.

**Comment by cpaasch** [comment]
Thanks, updated!

**Comment by unkaktus** [comment]
@cpaasch, thanks, but I still see http:// on GitHub.

**Comment by matttbe** [comment]
@nogoegst : I just switched to https for the link https://multipath-tcp.org on top of this page https://github.com/multipath-tcp/mptcp
Were you talking about this one?

**Comment by unkaktus** [comment]
@matttbe, yes! thank you! :+1:
