### ISSUE TITLE
How to enable MPTCP on ARM64 architecture?

### ISSUE THREAD

**Issue by lonelyzerg** [multipath-tcp/mptcp#241]
I did make defconfig with ARCH=arm64 and see no MPTCP option in menuconfig. Is there anyway to enable it?

btw I am trying to compile the source code into a Rpi3 64-bit kernel, so any help on compiling MPTCP into rpi are welcom!

Thanks in advance!

**Comment by cpaasch** [comment]
Make sure that IPv6 is statically compiled in, and not a module.

**Comment by lonelyzerg** [comment]
Thanks! The default ipv6 config is compiled as module, and after I change it from M to * the MPTCP option shows up.

**Comment by cpaasch** [comment]
Perfect!
