### ISSUE TITLE
How to dynamically control the number of subflows?

### ISSUE THREAD

**Issue by Viomnice** [multipath-tcp/mptcp#247]
Hello：
  I've been researhing to promote the quality of transmission, so i hope that we can dynamically adjust the number of subflows according to the state of network during a mptcp connection. 
  The version of mptcp is v0.89, because the device only has one interface, we configure path manager as "ndiffports" , and want to control the number of subflows during a mptcp connection by change the value of /sys/module/mptcp_ndiffports/parameters/num_subflows. For example:  Before testing we set the value of /sys/mudule/mptcp_ndiffports/parameters/num_subflows as 2, then we start testing. and we setting the variable /sys/mudule/mptcp_ndiffports/parameters/num_subflows as 5 by using command(echo 5 | sudo dd of=/sys/module/mptcp_ndiffports/parameters/num_subflows) during the process of testing. we use wireshark record all packets of overall process of testing, We found that the number of sub-flows remains unchanged by observing the whole packets, but if you test again, you will find the number of sub-flows is 5. 
  So I would like to ask you the way of change the number of subflows during a mptcp connection while the path manager configured as "ndiffports". Could you please help me resolve this issue?

Thanks
Lei Liu

**Comment by cpaasch** [comment]
Right now, there is no way to achieve what you are describing. Code-changes are needed to do this.

There is a discussion about a netlink-steered path-manager that is starting now.
