### ISSUE TITLE
latest mptcp version installation bug

### ISSUE THREAD

**Issue by mgucc** [multipath-tcp/mptcp#253]
Hi, I've been using MPTCP 0.92 version until last week smoothly. 'm using MPTCP in a wireless testbed.. so I have to install it every time I want to do some experiments. I use the apt-repository for installing linux-mptcp AND iproute2.

That said, I'm having some troubles with the latest updating of the MPTCP. I updated the new repository in my sources.list file (deb https://dl.bintray.com/cpaasch/deb stretch main). It install linux-mptcp smoothly.
But here is what I got when I execute from terminal `sudo apt-get install iproute2`:

> sudo apt-get install iproute2
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following extra packages will be installed:
>   iproute2
> Suggested packages:
>   iproute2-doc
> Recommended packages:
>   libatm1
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> 

apt-get knows that a new package has to be installed.. but just doesn't do anything!
I see iproute2 (mptcp version) with apt-cache:

> Package: iproute2
> Version: 4.9.201803091921-stretch
> Architecture: amd64
> Maintainer: Christoph Paasch <christoph.paasch@gmail.com>
> Depends: libc6 (>= 2.14), libdb5.3, libelf1 (>= 0.131), libmnl0 (>= 1.0.3-4~), libselinux1 (>= 2.0.15)
> Conflicts: arpd, iproute
> Replaces: iproute
> Provides: arpd
> Section: net
> Priority: important
> Homepage: http://mulitpath-tcp.org
> Description: networking and traffic control tools
>  The iproute suite, also known as iproute2, is a collection of
>  utilities for networking and traffic control.
>  .
>  These tools communicate with the Linux kernel via the (rt)netlink
>  interface, providing advanced features not available through the
>  legacy net-tools commands 'ifconfig' and 'route'.
>  .
>  This tool is extended for MultiPath TCP!!!
> Description-md5: 2d98700700afec9a0a9d2fc3a4c732df
> Filename: pool/m/mptcp/iproute2.deb
> SHA1: 36991e9d614beb6c896d7f7a40696877a614d37b
> SHA256: 47c6fb50a626d2600464ac4089e4afb2f38bd85148bb89d93746c3eea6262582
> Size: 628534)
> 

I really need some help here.. multipath option in ip link is required for my experiments.
What am I missing?

Thanks,
Michele.

**Comment by matttbe** [comment]
Hi Michele,

This version of IPRoute2 would maybe need to be updated to a more recent version. The problem you have is certainly because this custom version is older than the one in your repo. By default, APT always takes the latest available version.

You can change the priority, maybe something like this:

```
sudo sh -c 'echo "Package: *
Pin: origin dl.bintray.com
Pin-Priority: 610' > /etc/apt/preferences.d/mptcp
```

(Please tell us if this solution work, we could add a hint in the wiki)

Or [download it](https://dl.bintray.com/cpaasch/deb/pool/m/mptcp/:iproute2.deb) and install it manually, then avoid updates using apt-mark:

    sudo apt-mark hold iproute2

**Comment by cpaasch** [comment]
@mgucc - the root-cause is probably because the new iproute package in the apt repo has dependencies that your distro can't satisfy.

What distribution are you running?

**Comment by matttbe** [comment]
Good point, I missed the output of the first command.

Could be good to also have the output of `apt-cache policy iproute2`, just to be sure it is the MPTCP version it tries to install, not another one.

Maybe good to also have: `apt-cache policy libc6 libdb5.3 libelf1 libmnl0 libselinux1 arpd iproute`

**Comment by mgucc** [comment]
@cpaasch I'm running an Ubuntu 14.04.1 LTS. 

@matttbe here's the output of `apt-cache policy iproute2` 

```
iproute2:
  Installed: 3.12.0-2
  Candidate: 4.9.201803091921-stretch
  Version table:
     4.9.201803091921-stretch 0
        500 https://dl.bintray.com/cpaasch/deb/ stretch/main amd64 Packages
     3.12.0-2ubuntu1.2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 3.12.0-2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

And here's the output of `apt-cache policy libc6 libdb5.3 libelf1 libmnl0 libselinux1 arpd iproute`

```
libc6:
  Installed: 2.19-0ubuntu6.6
  Candidate: 2.19-0ubuntu6.14
  Version table:
     2.19-0ubuntu6.14 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 2.19-0ubuntu6.6 0
        100 /var/lib/dpkg/status
     2.19-0ubuntu6 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
libdb5.3:
  Installed: 5.3.28-3ubuntu3
  Candidate: 5.3.28-3ubuntu3.1
  Version table:
     5.3.28-3ubuntu3.1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 5.3.28-3ubuntu3 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
libelf1:
  Installed: 0.158-0ubuntu5.2
  Candidate: 0.158-0ubuntu5.2
  Version table:
 *** 0.158-0ubuntu5.2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.158-0ubuntu5 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
libmnl0:
  Installed: (none)
  Candidate: 1.0.3-3ubuntu1
  Version table:
     1.0.3-3ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
libselinux1:
  Installed: 2.2.2-1ubuntu0.1
  Candidate: 2.2.2-1ubuntu0.1
  Version table:
 *** 2.2.2-1ubuntu0.1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.2-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
arpd:
  Installed: (none)
  Candidate: (none)
  Version table:
iproute:
  Installed: 1:3.12.0-2
  Candidate: 1:4.9.201803091921-stretch
  Version table:
     1:4.9.201803091921-stretch 0
        500 https://dl.bintray.com/cpaasch/deb/ stretch/main amd64 Packages
     1:3.12.0-2ubuntu1.2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 1:3.12.0-2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

I installed with apt-get libmnl0, which I saw was not installed, and then tried to install iproute2 but I got the same problem.
Here's the (new) output of `apt-cache policy libmnl0`

```
libmnl0:
  Installed: 1.0.3-3ubuntu1
  Candidate: 1.0.3-3ubuntu1
  Version table:
 *** 1.0.3-3ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by matttbe** [comment]
The problem I guess is that these packages are made for Debian Stretch. You would need libmnl0 version >= 1.0.3-4~ but you have 1.0.3-3. You will maybe have to download a newer version. I don't know the impact of upgrading this lib to a new macro version: https://packages.ubuntu.com/xenial/libmnl0

The other solution would be to switch to Ubuntu Xenial 16.04, Trusty 14.04 is a bit old.

**Comment by mgucc** [comment]
I temporarily solved the issue installing iproute2 from the source code. I will try in the future to upgrade libmnl0. Thanks for your help.

**Comment by matttbe** [comment]
Thanks for your message. I am going to close this ticket but feel free to add more comments later!
