### ISSUE TITLE
Error on modprobe olia

### ISSUE THREAD

**Issue by fmokt** [multipath-tcp/mptcp#254]
We have error after upgrade to lthe last kernel 4.14.24 on debian strech.

modprobe mptcp_olia
modprobe: ERROR: could not insert 'mptcp_olia': Invalid argument

What is the problem ?

**Comment by matttbe** [comment]
Hi @fmokt,

Could it be possible that these modules are already included in the kernel?
Can you see them with:

    sysctl net.ipv4 | grep congestion
    find /lib -name "mptcp*"

**Comment by fmokt** [comment]
264/5000
Hello

the module is present
/lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko

but I can not activate it with sysctl

sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory
net.ipv4.tcp_congestion_control = olia

**Comment by matttbe** [comment]
What do you have for these sysctl

```
net.ipv4.tcp_allowed_congestion_control
net.ipv4.tcp_available_congestion_control
net.ipv4.tcp_congestion_control
```

What error do you have when doing an insmod? 

```
insmod /lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko
dmesg | tail
```

**Comment by fmokt** [comment]
this sysctl 

net.ipv4.tcp_allowed_congestion_control = olia balia cubic
net.ipv4.tcp_available_congestion_control = olia balia cubic
net.ipv4.tcp_congestion_control = olia

and insmod

 insmod /lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko
insmod: ERROR: could not insert module /lib/modules/4.14.24.mptcp/kernel/net/mptcp/mptcp_olia.ko: Invalid parameters

dmesg | tail
[  207.144684] TCP: olia does not implement required ops

**Comment by zorun** [comment]
This looks like it is the same issue fixed by https://github.com/multipath-tcp/mptcp/commit/c2119e001dd45a4fa3cf2c33d513e84662dd030e

@cpaasch would it make sense to release 0.94.1 with this fix (and update upstream to 4.14.31) ?

**Comment by fmokt** [comment]
Yes, I think the update is a good idea.

I patch and rebuild the kernel

**Comment by cpaasch** [comment]
@zorun - yes, I will make a 0.94.1 release.
