### ISSUE TITLE
how to achieve real roundrobin?

### ISSUE THREAD

**Issue by Viomnice** [multipath-tcp/mptcp#255]
hello,
      I am doing some tests for mptcp. I want to set the path_scheduler as roundrobin via sysctl. but i find client always send packet via same subflow.  I found that we need set boolean tunable "cwnd_segments" to achieve real roundrobin from http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP. but i don't konw how to set "cwnd_segments" as false, could you give me some advices?
Thanks!

**Comment by cpaasch** [comment]
The tunables can be found at ```/sys/module/mptcp_roundrobinparameters/```.

Please note that the roundrobin scheduler should not really be used for performance measurements, as it is wasting a lot of resources.
