### ISSUE TITLE
TCP_MULTIPATH_ADD api

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [multipath-tcp/mptcp#257]
As per this [ietf draft](https://tools.ietf.org/id/draft-ietf-mptcp-api-01.html#sec_mptcp_bind) there is an api to choose the interfaces that you want to include in the MPTCP session.
I couldn't find it anywhere in the code.
Has it been depreciated or not going to be implemented?

Thanks,
Raj

**Comment by cpaasch** [comment]
The API is currently not implemented.
