### ISSUE TITLE
mptcp is not enabled after I do the install through apt on Ubuntu 18.04 server in virtualbox

### ISSUE THREAD

**Issue by jiananwa** [multipath-tcp/mptcp#262]
The installation I followed is http://multipath-tcp.org/pmwiki.php/Users/AptRepository

uname -a
![image](https://user-images.githubusercontent.com/38869830/40754039-f8f6591a-642b-11e8-8440-f84bdea8e9db.png)

I tried "dmesg | grep MPTCP" after rebooting the system and nothing is there.

**Comment by matttbe** [comment]
Can you try something like `journalctl -k | grep -i mptcp`

**Comment by jiananwa** [comment]
Hi matttbe, thanks for your response. I tried the above command, still nothing outputs

**Comment by matttbe** [comment]
Maybe some log issues, I don't know if you have the beginning of the logs.

Do you have some mptcp sysctl? `sysctl net.mptcp`

**Comment by jiananwa** [comment]
It complains "No such file or directory"...
![image](https://user-images.githubusercontent.com/38869830/40797441-fe3c4cf4-64bc-11e8-81c7-70afd5fd6406.png)
This is the linux-mptcp I installed:
![image](https://user-images.githubusercontent.com/38869830/40797495-3388ae3e-64bd-11e8-89a0-429492ab1775.png)

[Update]
Tried the same installation process on Ubuntu 16.04 server and everything works fine. I think this issue is specific to 18.04:
![image](https://user-images.githubusercontent.com/38869830/40799113-8ae62aea-64c1-11e8-9097-f1c9cd5d2ae4.png)

**Comment by matttbe** [comment]
I was disturbed by your `uname` containing mptcp but that's only the name of your host.
You have the issue because you didn't select this MPTCP kernel at boot time. By default, it takes the most recent version which is v4. 15, the one you already have, not the v4.14 mptcp.

Please look at your GRUB settings or maintain the shift key enabled when booting to select another kernel. I am sure you can easily find plenty of doc about GRUB on Internet ;)

**Comment by jiananwa** [comment]
Cool, thanx for your response. Does that mean mptcp has not been patched to v4.15 and provided in production? I think apt install should by default pickup the right patched kernel image to download instead of let user to choose it:)

**Comment by matttbe** [comment]
> Does that mean mptcp has not been patched to v4.15 and provided in production?

No, we only create packages for LTS versions now. That's there is no packages for v4.15 but compiling the sources is still possible ;-)

**Comment by T0mek** [comment]
> No, we only create packages for LTS versions now. That's there is no packages for v4.15 but compiling the sources is still possible ;-)

Isn't the version 18.04 the LTS version?

**Comment by matttbe** [comment]
@T0mek we are talking here about kernel LTS versions, not Ubuntu LTS versions →https://www.kernel.org/category/releases.html

**Comment by T0mek** [comment]
Sorry for my ignorance and thanks for the clarification.
