### ISSUE TITLE
Enjoy the benefits of both fullmesh and ndiffports

### ISSUE THREAD

**Issue by ghostli123** [multipath-tcp/mptcp#263]
Topology:
     -----
s1          s2
     -----
Two links are used to connect two servers, and there are two subnets. 

Kernel Version: 
Linux gen 4.9.60.mptcp #5 SMP Thu Nov 2 22:20:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Path Manager:
net.mptcp.mptcp_path_manager = fullmesh 
MPTCP works as expected to utilize two links. However, if the path manager is changed to "ndiffports". Then it only uses one link to transfer data. 

Questions: 
1) How can I make MPTCP still use two links, while path manager is ndiffports?
2) I could not use "sysctl net.mptcp.mptcp_ndiffports=10" to change the number of subflows (sysctl: cannot stat /proc/sys/net/mptcp/mptcp_ndiffports: No such file or directory). I can only change the value in this file "/sys/module/mptcp_ndiffports/parameters/num_subflows". After I change the value in this file, will the value be activated immediately, or I need to re-enable MPTCP?

Thank you very much!

**Comment by cpaasch** [comment]
> How can I make MPTCP still use two links, while path manager is ndiffports?

You can configure the full-mesh path-manager to establish multiple subflows per IP-address pair. Take a look at http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP, Section "Configure the path-manager:", by setting ```/sys/module/mptcp_fullmesh/parameters/num_subflows```.

> I could not use "sysctl net.mptcp.mptcp_ndiffports=10" to change the number of subflows (sysctl: cannot stat /proc/sys/net/mptcp/mptcp_ndiffports: No such file or directory). I can only change the value in this file "/sys/module/mptcp_ndiffports/parameters/num_subflows". After I change the value in this file, will the value be activated immediately, or I need to re-enable MPTCP?

It will be activated immediately.
