### ISSUE TITLE
if i want to utilize this , do i still need to change my application code after installation/configuration ?

### ISSUE THREAD

**Issue by c1ngular** [multipath-tcp/mptcp#264]
i am frequently in need of uploading large quantity of data from my mobile device to a remote server by using a small mobile application developed by my own , i am very excited by finding this project , i am thinking to aggregate LTE/Wifi bandwidth to achieve better upload speed and quality , so i am wondering:
1.  it is possible that i can combine LTE and Wifi bandwidth , to speed up uploading process,so i can get my upload speed as LTE + Wifi simultaneously ?
2. do i have to change my application code ?
3. to achieve my goal, do i need multiple network interfaces/ connections on my server as well , rather than just install/configure MPTCP on my server ?
4. this will fallback to traditional TCP if no MPTCP is supported by corresponding servers , so other applications from my mobile device will not be effected, am i correct ? 

thank you very much , and sorry if i am asking silly questions !

**Comment by matttbe** [comment]
Hi,

> it is possible that i can combine LTE and Wifi bandwidth , to speed up uploading process,so i can get my upload speed as LTE + Wifi simultaneously ?

yes

> do i have to change my application code ?

No as long as you use TCP

> to achieve my goal, do i need multiple network interfaces/ connections on my server as well , rather than just install/configure MPTCP on my server ?

No

> this will fallback to traditional TCP if no MPTCP is supported by corresponding servers , so other applications from my mobile device will not be effected, am i correct ?

Yes. All you need is a kernel with MPTCP.
For more info about MPTCP on smartphone: https://dial.uclouvain.be/memoire/ucl/en/object/thesis:366/datastream/PDF_01/view
If you cannot have a kernel with MPTCP: https://www.netdevconf.org/2.2/session.html?tazaki-mptcp-talk

**Comment by c1ngular** [comment]
@matttbe  thank you so much !!!
