### ISSUE TITLE
socket level option MPTCP_OPEN_SUB_TUPLE for mptcp support

### ISSUE THREAD

**Issue by jiananwa** [multipath-tcp/mptcp#265]
From the /usr/src/linux-headers-4.14.24.mptcp/include/uapi/linux/tcp.h, I can see there are only four MPTCP socket options provided:

#define MPTCP_ENABLED           42
#define MPTCP_SCHEDULER         43
#define MPTCP_PATH_MANAGER      44
#define MPTCP_INFO              45

which does not include MPTCP_OPEN_SUB_TUPLE and some others mentioned in https://tools.ietf.org/html/draft-hesmans-mptcp-socket-00. Not sure if I miss anything or this option is not supported yet.

If not, I would like to know if there is a good way to programmatically select ip/interface (fullmesh case) or port (ndiffports case) to connect to the mptcp server? It would be nice if lsrr support in binder option of path manager can be manually turned on for specific ip pairs.

I used the latest mptcp version v0.94.0. Thanks in advance.

**Comment by matttbe** [comment]
Hi,

This API has not been merged (yet). It is available in @bhesmans ' repo: https://github.com/bhesmans/mptcp

**Comment by jiananwa** [comment]
Thank Matttbe for your response! Btw, could you please help comment on the second part of my question? Are the operations mentioned above feasible only with those unmerged changes?

**Comment by matttbe** [comment]
If you have access to the app (or you can change a lib) you can select the PM you want per connection, see http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP (`setsockopt (fd, MPTCP_PATH_MANAGER, name)`)

**Comment by jiananwa** [comment]
Got your point on the PM selection part. Thanks!

For the binder option in PM, I only see there is one globally defined "net.mptcp.mptcp_binder_gateways" available after setting net.mptcp.mptcp_path_manager to binder, not the individual gateway setting for each subflow. Not sure how to achieve more finer granularity on the gateway selections per subflow.

**Comment by matttbe** [comment]
With the current kernel, it will be difficult to have a lot of modularities. There are some drafts available (socket API, Netlink API, MPTCP socket), to improve that but none of them have been merged here.

**Comment by WladimirDelaCadena** [comment]
So at the end, is it not possible to handle programmatically subflows? Is there at least any available api to manipulate the multipath socket? Or to manually decides routes?

**Comment by matttbe** [comment]
@WladimirDelaCadena : not for the moment. You can configure your server to send the ADD_ADDR you want but it is more like a workaround. Another solution is to wait for the Netlink PM to be ready. It is in project with: https://github.com/multipath-tcp/mptcp_net-next/wiki
