### ISSUE TITLE
mptcp default traffic scheduler behavior issue

### ISSUE THREAD

**Issue by jiananwa** [multipath-tcp/mptcp#267]
Recently I'm testing multipath tcp lastest version on a WAN network, where three hosts are used with the topology as the following:

```
                       LA vps (openvpn server)
        ___________________|____________
        |                                |
tokyo vps     <------------>      Seattle vps  (both are openvpn clients)
```

From the above topology, tokyo and seattle vps have two interfaces respectively, one interface with public ip and one with openvpn private ip. Tokyo and Seattle vps have both installed v0.94 through apt with fullmesh path-manager as well as default scheduler enabled.

When I tried to issue iperf from tokyo to seattle, the mptcp basic functionality works in a way that multiple connections are created and when I use iptables to setup firewall to drop one connection, other one picks up the traffic without performance degrading. From the netstat, I could see connection between pub ip and pub ip contributes most of the iperf traffic, since the RTT is lower compared to openvpn approach. This is expected in the explaination from official website:

https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP:

> "'default': This scheduler is the default one. It will first send data on subflows with the lowest RTT until their congestion-window is full. Then, it will start transmitting on the subflows with the next higher RTT."

However, when I tried to add extra latency on that public ip connection two times the original value, leading to better RTT in the other connection (priv ip to priv ip), I should expect the majority of the traffic flow through this private OpenVPN connection. However, this is not the case in my experiment, where the pub-to-pub link still takes the majority of the bandwidth.

So my questions are the following:
(1) What is the default scheduler actual policy to determine which path to use?
(2) By design of mptcp, does it support streaming traffic through multiple connections simultaneously, like link1(50%), link2(20%), link3(30%), and adjust the traffic dynamically according to the link status? Is this feature supported in current implementation?

Detailed information including tcpdump is attached. Thanks in advance.

[mptcp-test-data.tar.gz](https://github.com/multipath-tcp/mptcp/files/2082290/mptcp-test-data.tar.gz)

**Comment by cpaasch** [comment]
Hello,

> So my questions are the following:
> (1) What is the default scheduler actual policy to determine which path to use?

The default scheduler sends traffic first on the low-latency path as described on the website (the text-snipped you found)

> (2) By design of mptcp, does it support streaming traffic through multiple connections simultaneously, like link1(50%), link2(20%), link3(30%), and adjust the traffic dynamically according to the link status? Is this feature supported in current implementation?

Yes, it does support this. It will do this dynamically based on the congestion it experiences on each path.


I don't find the tcpdump files in the tar archive that you attached. Can you resend it? Thanks!

**Comment by jiananwa** [comment]
Hi Christoph, sorry for not specifying the tcpdump files clearly. The ens3.data as well as tun1.data are the tcpdump data I collected using "tcp dump -i xx -w output.data".

Regarding the answer you provide on the second question, does that mean it should fully saturate all the connections made by mptcp? I see there is a same issue #252 talking about it. Btw, it would be helpful if you could point me to the file where this logic is implemented since codebase is not trivial and I need some help to start:)

**Comment by AlexanderFroemmgen** [comment]
The packet scheduling code is at https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.94/net/mptcp/mptcp_sched.c#L381

**Comment by cpaasch** [comment]
@jiananwa  - these files don't seem to be of pcap format. I think they have been corrupted.

Can you reproduce and collect new pcaps? Thanks!

**Comment by jiananwa** [comment]
Hi Christoph, sorry for providing that truncated data. I have tested two data file, and I believe the truncated one is ens3.data. I have sent the correct pcap data (tested by Wireshark) as a gzip file to your email address because there is a 10MB limit for a file to be uploaded into the comment.

Thanks for your help!

**Comment by matttbe** [comment]
Feel free to use Google Drive, wetransfer, framadrop or others to share packet traces to everybody ;-)

**Comment by jiananwa** [comment]
Hi matttbe, you could access them through the following google drive link:)

https://drive.google.com/file/d/1pZC8kNkp2idN7hNSWlB_lFN3Nf_DGxR4/view?usp=sharing

**Comment by jiananwa** [comment]
Hi Christoph, is there any update on this issue?

**Comment by cpaasch** [comment]
@jiananwa  - sorry for the late reply. Looking at the trace, the RTT on the public IP is actually better than the one in the tunnel. The public IP has an RTT about 100ms while the tunnel's RTT is slightly above that. That's the reason why you still see most traffic on the public IP.
