### ISSUE TITLE
Configure "num_segments" in RR

### ISSUE THREAD

**Issue by GinesGarcia** [multipath-tcp/mptcp#268]
Hi, I woul like to know how to configure the number of segments to be sent through each subflow. 

Thanks in advance,
Ginés.

**Comment by matttbe** [comment]
Hi,
I guess it should be in `/sys/module/mptcp/parameters/<PARAM_NAME>`. Then as root, you can do:

    echo 2 > /sys/module/mptcp/parameters/num_segments

**Comment by GinesGarcia** [comment]
Thanks a lot!!

What is the maximum value allowed for this paramter?

Thanks in advance.

**Comment by matttbe** [comment]
> What is the maximum value allowed for this paramter?

The size of a byte: https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.94/net/mptcp/mptcp_rr.c#L7

**Comment by GinesGarcia** [comment]
Thanks a lot!!
