### ISSUE TITLE
Is it really useful mptcp without API?

### ISSUE THREAD

**Issue by WladimirDelaCadena** [multipath-tcp/mptcp#269]
Hello, I have spent hours looking for an API or a way to handle the MPTCP operation from a client/server developed by myself. My scenario is a bit different to what I found in other works. I want to use only one interface at client with multiple tcp connections to multiple hosts. These host should receive each a subflow of the same connection, and then forward to a end node capable to associate the subflows. As you see, I need to control the connections. Some suggestion for handling substreams with the mptcp kernel? Or my scenario is not suitable for mptcp

**Comment by cpaasch** [comment]
Yes, I think your scenario is not suitable for MPTCP. But maybe a little drawing would help to better understand what you are trying to achieve.

**Comment by WladimirDelaCadena** [comment]
Client eth0----| ---> Tcp 1 - Port A---->|-- Server 1 (ips1/eth0) --> Tcp s1 -->|---Server Y (eth0/ipsy) 
Client eth0----| ---> Tcp 2 - Port B---->|-- Server 2 (ips2/eth0) --> Tcp s2 -->|---Server Y (eth0/ipsy)
Client eth0----| ---> Tcp 3 - Port C---->|-- Server 3 (ips3/eth0) --> Tcp s3 -->|---Server Y (eth0/ipsy)

My idea is, the three tcp are mptcp subflows of the same MPTCP connection, Server 1, 2, 3 forward those flows to a final server that reads three connections and, since they are dependent it can merge ant receive all data. I think with appropriate tools from the MPTCP API from [https://tools.ietf.org/html/draft-hesmans-mptcp-socket-03](url) would be enough. I would handle each TCP with the same interface/ip but only changing the ports. 
Let me know any suggestion/observation to the idea, thanks.

**Comment by cpaasch** [comment]
Do you want different destination ports, and you will do the routing to the Servers 1,2,3 by checking the destination-port?

**Comment by WladimirDelaCadena** [comment]
Not necessary, they should be only three connection of the same flow

**Comment by matttbe** [comment]
(I replied this on the ML, I guess it is for the same discussion)

The fullmesh Path Manager on a server will announce all available addresses. Is it not enough to `ip addr add` these IPs (even if you don't own them)?

If your client also uses the fullmesh PM, by default it will try to establish a subflow per IP it will receive via an ADD_ADDR from the server.

Note: but in this situation, the client will try to establish subflows to the same dest port)

**Comment by WladimirDelaCadena** [comment]
@matttbe   yes I read it on the ML, thanks for the reply
