### ISSUE TITLE
Using tcp_snd_wnd_test in RR scheduler

### ISSUE THREAD

**Issue by GinesGarcia** [multipath-tcp/mptcp#270]
Hi,
I would like to run some experiments with a modified version of the RR scheduler where I need "tcp_snd_wnd_test" method available. In the default shceduler it is available and used without problems but I cannot use it from RR. Should I import something?

Thanks in advance for your help.
Regards,
Ginés.

**Comment by cpaasch** [comment]
What do you mean with "I cannot use it from RR" ?

**Comment by cpaasch** [comment]
You might need to add a ```EXPORT_SYMBOL(tcp_snd_wnd_test);``` at the end of tcp_snd_wnd_test().

**Comment by GinesGarcia** [comment]
thank you very much! this is exactly what I needed
