### ISSUE TITLE
MPTCP in the Router (NAT server)

### ISSUE THREAD

**Issue by brodnev** [multipath-tcp/mptcp#276]
I'm using MPTCP implementation in Gentoo Linux, 64 bit rpi3 kernel 4.14.59-v8+, running on raspberry pi 3 (RPI3).
This patch has been applied http://multipath-tcp.org/patches/mptcp-v4.14-559409607f41.patch
TCPv6 is in the kernel; default scheduler specified in the kernel is redundant.

RPI3 build in Ethernet interface (eth0) and build in Wi-fi interface (wlan0) are used as LAN interfaces. 
WAN interface in Single USB dongle (eth1).
* single WAN interface is used here because this router should access my remote MP-Capable server with two network cards, whereas all other WAN traffic may remain in regular TCP. 

The following software is used to make router to work.
net-firewall/shorewall as the firewall (front-end),
net-dns/dnsmasq to provide the DHCP and DNS services on the lan side,
net-wireless/hostapd to manage your WiFi adaptor as an access point,
net-misc/bridge-utils for tools to let us bridge the ethernet and WiFi interfaces together.
sys-apps/haveged to ensure we have sufficient entropy for the WiFi access point cryptography.
Config is done using this tutorial https://wiki.gentoo.org/wiki/Ethernet_plus_WiFi_Bridge_Router_and_Firewall

Router is able to deliver internet both to eth0 and wlan0.
When I access amiusingmptcp.de from RPI3 browser, it shows that MPTCP is implemented.
However, if I access amiusingmptcp.de via windows machine over eth0 or wlan0, the answer is NO, MPTCP is not enabled.

So is it possible to make MP-Capable Router in this way and I do something wrong, or it is impossible to use MPTCP on the router in such way (over shorewall)?

**Comment by matttbe** [comment]
Hi,

If your router only forward packets, it will not transform the "regular" TCP connections from a client to a server to MPTCP ones. MPTCP has to be supported by the two ends points of your connections.

If you want your router to "transform" connections by adding MPTCP, you need to end connections and start new ones from your router to Internet. In other words, you need a proxy.

I am going to close this issue. Feel free to react if the answer was not what you wanted.

**Comment by brodnev** [comment]
Yes, You are right. During this time I was understand this by myself. Also I was found a project, that supports MPTCP in router, and they also use proxy. The project name is openmptcp router, but I was not tested it.
Thank for the reply.
