### ISSUE TITLE
Big test... with not so good results...

### ISSUE THREAD

**Issue by pRiVi** [multipath-tcp/mptcp#283]
Hi cpaasch,

I am the guy reported sone month/years ago big problems by reporting all the time crashing mptcp kernels within minutes of using.

The good news: This crashings are not appearing anymore, so I can test some other things.

The bad news: It seems there are many many other bugs and problems.

I have a customer with 7 DSL lines, 16 Mbit/sek per line, and each with a router and IP 10.10.1.6x. I created a OpenVPN via TCP ( -> means MPTCP) and let the traffic of about 80 users on it.

1. mptcp only uses 4 routes (and so only 4 DSL lines), and varies about this, sometimes it uses much less 3...  I can see it on the other side, the server is only seening traffik for 4 ips and of 3 lines no paket at all over the whole testing time.

2. Sometimes it completely hangs over minutes, and then it resumes...

3. The performance is very bad, more than 20 Mbit/sek is not used in peaks, and this only in strange peaks. The normal throuthput is happening between 3 and 8 Mbit/sek. Without MPTCP, if I create a UDP based brdige with 7 OpenVPN tunnels and bound them (ifenslave), I get up to 95 Mbit/sek and with this amout of users nothing less than 40 Mbit/sek.

How can I debug this?

```
root@mptestbk:~# ip rule
0:	from all lookup local 
32759:	from 10.10.1.167 lookup 7 
32760:	from 10.10.1.166 lookup 6 
32761:	from 10.10.1.165 lookup 5 
32762:	from 10.10.1.164 lookup 4 
32763:	from 10.10.1.163 lookup 3 
32764:	from 10.10.1.162 lookup 2 
32765:	from 10.10.1.1 lookup 1 
32766:	from all lookup main 
32767:	from all lookup default 
root@mptestbk:~# ip route list table 1
default via 10.10.1.61 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 2
default via 10.10.1.62 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 3
default via 10.10.1.63 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 4
default via 10.10.1.64 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 5
default via 10.10.1.65 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 6
default via 10.10.1.66 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# ip route list table 7
default via 10.10.1.67 dev eth2 
throw 10.0.0.0/8 
throw 172.16.0.0/16 
throw 192.168.0.0/16 
root@mptestbk:~# # uname -a
Linux mptestbk 4.14.64+ #6 SMP Thu Sep 20 22:30:20 CEST 2018 x86_64 GNU/Linux
root@mptestbk:~# 
```
```
privi@cmmarkus:~/mptcp$ git status
On branch mptcp_v0.94
Your branch is up-to-date with 'origin/mptcp_v0.94'.
nothing to commit, working tree clean
privi@cmmarkus:~/mptcp$ 
```
Regards,
Markus

**Comment by matttbe** [comment]
Hi,

That's crazy, there are so many MPTCP users while there are apparently _many many other bugs and problems_. That's maybe because devs on this project don't receive enough encouragement and support for this very complex project :thinking: 

Anyway... regarding the performances, there are many reasons why you don't reach the throughput you want. There were many discussions about that. It could be because your client/server are using all the CPU, maybe doing too much (crypto, mptcp debug, mptcp checksum, fragmentation, etc.), maybe not having good conditions (tunnelling (TCP on top of TCP), bad network conditions, etc.).

Optimising the setup is not an easy part but after some changes, you can get good perfs: https://multipath-tcp.org/pmwiki.php?n=Main.50Gbps
There are also many resources everywhere about optimising a Linux kernel for network tasks.

>
```bash
privi@cmmarkus:~/mptcp$ git status
On branch mptcp_v0.94
Your branch is up-to-date with 'origin/mptcp_v0.94'.
nothing to commit, working tree clean
```

Please share the commit (sha). `git status` can say that you are up-to-date with a very old version of `origin/mptcp_v0.94`. Also feel free to try with different versions.

**Comment by pRiVi** [comment]
```
privi@cmmarkus:~/mptcp$ git log|head
commit a6e7fb2c1e8913eef906942f578e3ecc9602580e
Author: Christoph Paasch <cpaasch@apple.com>
Date:   Thu Sep 13 17:25:25 2018 -0700

    mptcp: Restart subflow-selection when we force a re-evaluation
    
    After setting the path-mask to 0, all subflows become eligible again.
    At that point, we should re-evaluate the subflow selection.
    
    Fixes: f9ca33df8007 ("mptcp: sched: Improve active/backup subflow selection")
privi@cmmarkus:~/mptcp$ 
```

If you have debug possibilities, then tell. Just closing this issue is not a sign that you want to find out where the cause is located.

Maybe the same behaviour as some years ago, as I posted kernel panics within minutes of using, which were just denied and now got mysteriously fixed.

**Comment by pRiVi** [comment]
Hi Mattbe,

> That's crazy, there are so many MPTCP users while there are apparently _many many other bugs and problems_. That's maybe because devs on this project don't receive enough encouragement and support for this very complex project 

By the currently status of the project, and so fundeamental problems with it, I just cannot name this project anything else than alpha software. It can show what can be reached, but this is just not a realy usable project.

> Anyway... regarding the performances, there are many reasons why you don't reach the throughput you want. There were many discussions about that. It could be because your client/server are using all the CPU, maybe doing too much (crypto, mptcp debug, mptcp checksum, fragmentation, etc.), maybe not having good conditions (tunnelling (TCP on top of TCP), bad network conditions, etc.).

Realy? I know how to debug this kind of connection problems. We just donnot have any problem like this here. If you monitor the behavoir of the latest version in a network monitor you can just see very strange behaviour, using 2 lines then no, making a peek of some secons and then no traffic at all.

If you cannot give hints how to debug your code, this is in my eyes just not debugable or ajustable, in my currently testes about two days now I can just say: Its badly broken at all.

> Optimising the setup is not an easy part but after some changes, you can get good perfs: https://multipath-tcp.org/pmwiki.php?n=Main.50Gbps
> There are also many resources everywhere about optimising a Linux kernel for network tasks.

Yeah, alphasoftware which can do something in YOUR labor, nothing else.

**Comment by cpaasch** [comment]
@pRiVi The best thing to do is to collect a packet-trace on the sender-side and from there on we can take a look at it.

**Comment by rstanislav** [comment]
Kernel panics not always result of bad code, often it can be a result of hardware failure - bad RAM module, or motherboard, or even CPU, are you using server grade hardware with ECC memory ?
