### ISSUE TITLE
Please update binary kernel builds for Debian

### ISSUE THREAD

**Issue by D4rk4** [multipath-tcp/mptcp#286]
Since this commit - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b21ebf2fb4cd
New modules can't build with 4.14.x kernels used by MPTCP. For example ZFS.
Now i must choose use ZFS or MPTCP

**Comment by cpaasch** [comment]
@D4rk4 - I'm actually not sure, what you need.

Because, we recently updated the images on the bintray. So, it should be fine, no? Or do you need a specific kernel-configuration to be enabled?

**Comment by D4rk4** [comment]
I'm talking about update linux kernel image to version 4.15+ in your binary repo.

**Comment by matttbe** [comment]
Hi @D4rk4 
I am sorry for you but I am going to close this ticket: we are only building "stable versions" (and building binaries) for LTS kernels. If you want a more recent kernel, you can use the branch "mptcp_trunk", currently in v4.18(.0).
Instructions to build a kernel is on our wiki: http://multipath-tcp.org/pmwiki.php/Users/DoItYourself
