### ISSUE TITLE
Debian Stretch iproute2 package : /sbin/ip instead of /bin/ip

### ISSUE THREAD

**Issue by FlorentCoppint** [multipath-tcp/mptcp#288]
Hi,

I had a problem using MPTCP packages on a Debian Stretch system.

It seems that iproute2 package provided by MPTCP installs the "ip" binary to /sbin/ip, instead of /bin/ip in official Debian iproute2 package.

It breaks some system when they use "bridge-utils" : boot script of bridge-utils needs /bin/ip.

Maybe others binary could be impacted...

**Comment by cpaasch** [comment]
I see... I uploaded new packages to the bintray repo. Can you update your packages and try again?

Please reopen if the issue persist.
