### ISSUE TITLE
Kernel panic on mptcp-0.94, 4.14.41

### ISSUE THREAD

**Issue by berezoka** [multipath-tcp/mptcp#289]
Hello, when I start download large(10GB) file over two LTE I allways got this error:

[Sun Oct 28 20:32:47 2018] ------------[ cut here ]------------
[Sun Oct 28 20:32:47 2018] WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:320 dev_watchdog+0x22c/0x230
[Sun Oct 28 20:32:47 2018] Modules linked in: tun macvlan ipt_MASQUERADE nf_nat_masquerade_ipv4 xt_REDIRECT nf_nat_redirect xt_dscp xt_comment iptable_nat nf_nat_ipv4 nf_nat xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_length xt_DSCP xt_connmark nf_conntrack libcrc32c xt_mark ip_set_hash_net binfmt_misc xt_set ip_set nfnetlink xt_multiport intel_rapl iptable_mangle i915 intel_powerclamp coretemp iptable_filter kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc nls_ascii nls_cp437 vfat aesni_intel fat aes_x86_64 snd_soc_sst_cht_bsw_rt5645 drm_kms_helper crypto_simd iTCO_wdt iTCO_vendor_support glue_helper cryptd drm intel_cstate gpio_keys cdc_ether usbnet r8152 efi_pstore efivars pcspkr snd_intel_sst_acpi snd_intel_sst_core snd_soc_rt5645 evdev snd_soc_sst_atom_hifi2_platform cdc_acm
[Sun Oct 28 20:32:47 2018]  snd_soc_sst_match snd_soc_rl6231 i2c_algo_bit snd_soc_core lpc_ich snd_compress processor_thermal_device mfd_core intel_soc_dts_iosf snd_pcm dw_dmac snd_timer intel_hid dw_dmac_core snd sparse_keymap goodix soundcore int3403_thermal int3400_thermal int3406_thermal int340x_thermal_zone acpi_thermal_rel video soc_button_array acpi_pad button sch_fq efivarfs ip_tables x_tables autofs4 hid_generic usbhid hid ext4 crc32c_generic crc16 mbcache jbd2 fscrypto mmc_block crc32c_intel xhci_pci xhci_hcd usbcore thermal i2c_designware_platform sdhci_acpi i2c_designware_core sdhci mmc_core
[Sun Oct 28 20:32:47 2018] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.41 #1
[Sun Oct 28 20:32:47 2018] Hardware name: Default string Default string/Cherry Trail CR, BIOS DF-BI-7-S70CR200-CC34E-004-C 03/23/2017
[Sun Oct 28 20:32:47 2018] task: ffffffff87a12480 task.stack: ffffffff87a00000
[Sun Oct 28 20:32:47 2018] RIP: 0010:dev_watchdog+0x22c/0x230
[Sun Oct 28 20:32:47 2018] RSP: 0018:ffff9af9fac03e80 EFLAGS: 00010246
[Sun Oct 28 20:32:47 2018] RAX: 0000000000000039 RBX: 0000000000000000 RCX: 0000000000000000
[Sun Oct 28 20:32:47 2018] RDX: 0000000000000000 RSI: 00000000000000f6 RDI: 0000000000000300
[Sun Oct 28 20:32:47 2018] RBP: ffff9af9ea59845c R08: 0000000000000001 R09: 00000000000002ac
[Sun Oct 28 20:32:47 2018] R10: ffff9af99efc84d8 R11: 00000000000002ac R12: ffff9af9c4a5d880
[Sun Oct 28 20:32:47 2018] R13: 0000000000000000 R14: ffff9af9ea598000 R15: 0000000000000001
[Sun Oct 28 20:32:47 2018] FS:  0000000000000000(0000) GS:ffff9af9fac00000(0000) knlGS:0000000000000000
[Sun Oct 28 20:32:47 2018] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[Sun Oct 28 20:32:47 2018] CR2: 00000000007a0800 CR3: 000000004b60a000 CR4: 00000000001006f0
[Sun Oct 28 20:32:47 2018] Call Trace:
[Sun Oct 28 20:32:47 2018]  <IRQ>
[Sun Oct 28 20:32:47 2018]  ? dev_deactivate_queue.constprop.29+0x60/0x60
[Sun Oct 28 20:32:47 2018]  call_timer_fn+0x30/0x130
[Sun Oct 28 20:32:47 2018]  run_timer_softirq+0x1e2/0x440
[Sun Oct 28 20:32:47 2018]  ? tick_sched_handle+0x23/0x60
[Sun Oct 28 20:32:47 2018]  ? tick_sched_timer+0x35/0x70
[Sun Oct 28 20:32:47 2018]  __do_softirq+0x112/0x2b2
[Sun Oct 28 20:32:47 2018]  irq_exit+0xb5/0xc0
[Sun Oct 28 20:32:47 2018]  smp_apic_timer_interrupt+0x70/0x130
[Sun Oct 28 20:32:47 2018]  apic_timer_interrupt+0x7d/0x90
[Sun Oct 28 20:32:47 2018]  </IRQ>
[Sun Oct 28 20:32:47 2018] RIP: 0010:cpuidle_enter_state+0xac/0x2e0
[Sun Oct 28 20:32:47 2018] RSP: 0018:ffffffff87a03e80 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff10
[Sun Oct 28 20:32:47 2018] RAX: ffff9af9fac21a00 RBX: 000023457fcb3e7f RCX: 000000000000001f
[Sun Oct 28 20:32:47 2018] RDX: 000023457fcb3e7f RSI: fffffff7c42fd4bb RDI: 0000000000000000
[Sun Oct 28 20:32:47 2018] RBP: 0000000000000004 R08: 00000000000011fb R09: 0000000000000000
[Sun Oct 28 20:32:47 2018] R10: 0000000000001933 R11: 0000000000000001 R12: ffffc76f7fc0afa0
[Sun Oct 28 20:32:47 2018] R13: ffffffff87aafe38 R14: 0000000000000004 R15: 000023457f4cdd6b
[Sun Oct 28 20:32:47 2018]  do_idle+0x19d/0x200
[Sun Oct 28 20:32:47 2018]  cpu_startup_entry+0x70/0x80
[Sun Oct 28 20:32:47 2018]  start_kernel+0x459/0x47a
[Sun Oct 28 20:32:47 2018]  secondary_startup_64+0xa5/0xb0
[Sun Oct 28 20:32:47 2018] Code: 63 8e 60 04 00 00 eb 8f 49 8d 3e c6 05 d1 87 b2 00 01 e8 88 4e fd ff 48 8d 10 8d 0b 49 8d 36 48 c7 c7 98 b3 87 87 e8 5f 69 b1 ff <0f> 0b eb bd 0f 1f 44 00 00 41 57 41 56 4c 8d 32 41 55 4c 8d 29 
[Sun Oct 28 20:32:47 2018] ---[ end trace d5474cbf154ac952 ]---

**Comment by cpaasch** [comment]
Hello,

v4.14.41 is fairly old. Can you try with the latest kernel and report if you still see the issue?

Thanks,
Christoph
