### ISSUE TITLE
MPTCP Error

### ISSUE THREAD

**Issue by jkhlouf** [multipath-tcp/mptcp#292]
![image](https://user-images.githubusercontent.com/42026457/47970046-dc3d9e80-e088-11e8-8fa8-f1103a34e6b4.png)
![image](https://user-images.githubusercontent.com/42026457/47970298-35f39800-e08c-11e8-8d7b-ec30a9a36225.png)

**Comment by cpaasch** [comment]
You probably have a firewall in your network that is removing the MPTCP-options out of the TCP-header.

You can check out http://www.tracebox.org to see which hop is doing that.

**Comment by jkhlouf** [comment]
![image](https://user-images.githubusercontent.com/42026457/47995118-016bf480-e0fd-11e8-9259-ba0e0abb643a.png)
![image](https://user-images.githubusercontent.com/42026457/47995131-092b9900-e0fd-11e8-8ffe-b54d0f2758d0.png)
