### ISSUE TITLE
anycast destroy issue

### ISSUE THREAD

**Issue by madhanraj** [multipath-tcp/mptcp#293]
Tests for IPv6 anycast addresses failed

Relevant kernel commits:
--
  | upstream net-next:
  | 381f4dc ipv6: clean up anycast when an interface is destroyed

Hi, 
I am trying to run https://android.googlesource.com/kernel/tests/+/master/net/test/anycast_test.py
but only in the MPTCP version (v0.94, v0.93) it fails 

version 4.14.77+ #1 SMP Mon Nov 5 15:22:41 KST 2018 x86_64 x86_64 x86_64 GNU/Linux

but it does not fail in the plain linux version of 4.14.79. 

This happens irrespective of  the mptcp_enabled value (0 or 1)

**Comment by cpaasch** [comment]
Hello!

So, I get this:

```
mptcp@mptcp:~/tests/net/test$ sudo python ./anycast_test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.124s

OK
```

What failure do you see?

**Comment by madhanraj** [comment]
The problem happens when mptcp_fullmesh module is loaded (irrespective of the current path manager)

May be in your test , the fullmesh is not loaded .. 

CONFIG_MPTCP_FULLMESH=y. 


I found that it is because of the eventq processing in the full mesh which introduces additional delay .

The same script (anycast.py), when fullmesh is loaded then 
1) thread.join 500ms --> FAIL 
2) thread.join 2s --> PASS 
The mptcp_fullmesh queue inteoduces additional 1.3s delay

**Comment by cpaasch** [comment]
Ah! Interesting! I am indeed able to repro with the fullmesh module.

**Comment by cpaasch** [comment]
Ok, the problem seems to be the duplicate address-timer that takes a refcount on the IPv6-address. Thus, prevents it from getting closed.

**Comment by cpaasch** [comment]
I wonder if we should simply remove the duplicate address detection in the path-manager. And simply use the address. If it is duplicate, it will be removed later on and our subflow-attempt will get canceled.

**Comment by cpaasch** [comment]
cfr.: https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2018-11/msg00010.html
