### ISSUE TITLE
question about issue #293, anycast destroy issue

### ISSUE THREAD

**Issue by cyclopes123** [multipath-tcp/mptcp#296]
I'm experiencing same issue with issue #293 , currently sicking the fix for this.

I read below mail thread discussing about this issue, and tested the potential patch for our build and failed.
https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2018-11/msg00019.html

MPTCP version is v0.94, and kernel version is 4.9.112+.
I tested the initial patch that Paasch suggested, but still the testcase was failed.

Do you have any further progress about this issue?

**Comment by cyclopes123** [comment]
I'm testing a few more times, and the TC is not always failed.
I've tested 5 times, and passed one time.

**Comment by cpaasch** [comment]
Hmmm... it all worked in my tests. Let me try out with the patch applied to v0.94.

**Comment by cpaasch** [comment]
I double-checked everything. And indeed, my patch makes it work on v0.94. Note, I had to fix a conflict when applying the patch.

**Comment by cyclopes123** [comment]
Thank you for the answer.
