### ISSUE TITLE
RR scheduler and wVegas CC

### ISSUE THREAD

**Issue by FiratA** [multipath-tcp/mptcp#298]
Hello,

i have a question regarding the wVegas congestion control and the Round Robin Scheduler.
How would these two work together?
We know that wVegas (coupled congestion conotrol) is shifting the traffic to less congested paths, but how does it work when i use the round robin scheduler which just iterates the streams in the order they appear.
so how would wVegas be able to shift the traffic?

Thanks in advance.

**Comment by matttbe** [comment]
Hello,

This scheduler was created for an academical purpose, mainly to check that it works and show that doing that is not a good idea from a performance point of view.
I guess then it doesn't make sense to use it with any coupled CC.

**Comment by FiratA** [comment]
this means when i select the round robin scheduler, wvegas would be not able to do its job correct?
so what kind of scheduler do i need to use for wvegas, because the once in the kernel config are the round robin and redundant scheduler.

**Comment by matttbe** [comment]
> this means when i select the round robin scheduler, wvegas would be not able to do its job correct?

I guess the TCP CC will give the information that the sending window is full (or similar) but I don't remember what the RR scheduler is doing with this info.

> because the once in the kernel config are the round robin and redundant scheduler.

You don't have the `default` scheduler? Which kernel are you using?

**Comment by FiratA** [comment]
I am using kernel version 4.14.77+.

I am using the RR scheduler for a test setup but i am not sure if it will work with the wVegas (coupled congestion control).

**Comment by cpaasch** [comment]
Closing inactive issues.
