### ISSUE TITLE
Not able to use all  paths 

### ISSUE THREAD

**Issue by swetheendra84** [multipath-tcp/mptcp#299]
As per instructions mentioned,
I tried to get latest code of mptcp kernel using command git clone --depth=1 git://github.com/multipath-tcp/mptcp.git. 
After compiling it and booting it I have configured Wireless and Ethernet interfaces. If I browse some page or play video, packets are always flowing through Ethernet interface. Wireless interface is idle all the time. I am not able to see this issue in normal linux versions (experiencing this problem only after installing mptcp). How can I resolve this ?

**Comment by matttbe** [comment]
Are both the clients and servers support MPTCP? (try with https://multipath-tcp.org , amiusingmptcp.de or tessares.net for the public servers)
If yes, no middlebox stripping MPTCP options? Tracebox can help for that, check "usage" section: http://www.tracebox.org/

**Comment by swetheendra84** [comment]
Hi Matthieu Baerts,
                               Thank you for your reply. Yes both Server and Client are supporting MPTCP and middlebox is not stripping MPTCP options. Using same set of interfaces,for normal linux with out MPTCP, packets are flowing through all interfaces. MPTCP enabled kernel is only generating this issue.

**Comment by matttbe** [comment]
I am still not sure to understand what you are comparing with and without MPTCP.
Do you mean that with a kernel without MPTCP, you can use the Wireless and the Ethernet interfaces separately (only WiFi and only Ethernet) but not with a kernel you compiled by yourself?

> Wireless interface is idle all the time.

So in other words, with the kernel with MPTCP support, you cannot use your Wireless interface, right?
Could it be due to a driver problem? Maybe you need proprietary drivers and they need to be enabled/compiled for this kernel?

**Comment by swetheendra84** [comment]
No. I am able to use Wireless interface individually, but if I enable both Wireless and Ethernet interfaces, then Wireless is becoming idle. So it should not be a problem with drivers right ?

**Comment by matttbe** [comment]
> if I enable both Wireless and Ethernet interfaces, then Wireless is becoming idle

How do you see that it is idle? Do you mean it is not used or a command is telling you it is idle?
Without MPTCP, what are you doing to use these two interfaces at the same time?
Which kernel versions (with/without MPTCP) are you using?

**Comment by swetheendra84** [comment]
I am running Wireshark in the background. I'm playing videos hosted on MPTCP server from my system.
MPTCP Kernel version : 4.14.79 , 4.4.70 (tested on two different versions)
Without MPTCP Kernel Version: 4.14.70

**Comment by matttbe** [comment]
Sorry, I am still a bit confused:
* without MPTCP, I guess you will use one network or the other, typically you use the wired network first and the wireless one when the other one is down (except if you play with the routing rules of course).
* with MPTCP, you would like to use the two at the same time but for that you need to setup routing rules: http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting

Then you don't compare the same thing: using networks separately without MPTCP and combining networks with MPTCP. Or did I misunderstood your problem?

When you say:

> Using same set of interfaces,for normal linux with out MPTCP, packets are flowing through all interfaces.

What does that mean? Packets are flowing through all interfaces but packets from different connections, right?

With MPTCP, if MPTCP is not blocked (check tcpdump/Wireshark), the routing is well configured on both the client and the server and the Path Manager can create multiple subflows or announce IP addresses (use the fullmesh path manager), then you should see the client is at least trying to establish new subflows. If not, check these three different points. Packet traces, IP configuration and `sysctl net.mptcp` might help debugging this problem ;-)

**Comment by swetheendra84** [comment]
Let me be more clear on this
I have two scenarios 
1) In first scenario I have a client and I configured MPTCP with **sudo apt-get install linux-mptcp**    as per instructions mentioned at https://multipath-tcp.org/pmwiki.php/Users/AptRepository.

2)In second scenario I have client and I configured MPTCP with the source code  **mptcp git clone --depth=1 git://github.com/multipath-tcp/mptcp.git** as mentioned at https://multipath-tcp.org/pmwiki.php/Users/DoItYourself.

I have wifi and ethernet interfaces. When I am playing a video, Only Ethernet is being used in second scenario and wifi is not used at all. But in first scenario packets are flowing through both ethernet and wifi. 

I want to know is there ant thing I'm missing out in configuration  when I am compiling mptcp code by myself and booting up as WIFI is not at all being used in second case.  I am not able to see this issue in first scenario.

**Comment by cpaasch** [comment]
Please double-check that the system you are booting into actually has MPTCP. (e.g., ```cat /proc/sys/net/mptcp/mptcp_enabled```).

If that's the case, check that MPTCP is being negotiated and actually used by taking a packet-trace.

**Comment by swetheendra84** [comment]
Its enabled and value is 1. I have also verified configuration of MPTCP by **http://amiusingmptcp.de/** web site.

**Comment by matttbe** [comment]
> I have two scenarios

Thank you, it is clearer now!

In both cases, do you have the same IP rules/routes and `sysctl` config?

    ip rule show
    ip route
    ip route show table 1
    ip route show table 2
    sysctl net.mptcp

**Comment by AlexanderFroemmgen** [comment]
I'm not sure if this is related. I had some problems to establish the paths as expected by the fullmesh pathmanager with the current trunk... But this might be due to some missconfigs in my Mininet script as well.

Using  4.14.70.mptcp:

```
[   93.638424] mptcp_alloc_mpcb: created mpcb with token 0xd21103fd
[   93.645426] mptcp_add_sock: token 0xd21103fd pi 1, src_addr:10.0.0.1:54640 dst_addr:10.0.0.2:5001, cnt_subflows now 1
[   93.697807] mptcp_alloc_mpcb: created mpcb with token 0xfdf3bf13
[   93.704149] mptcp_add_sock: token 0xfdf3bf13 pi 1, src_addr:10.0.0.2:5001 dst_addr:10.0.0.1:54640, cnt_subflows now 1
[   93.757700] mptcp_add_sock: token 0xd21103fd pi 2, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 2
[   93.767620] mptcp_init4_subsockets: token 0xd21103fd pi 2 src_addr:11.0.0.1:0 dst_addr:10.0.0.2:5001 ifidx: 3
[   93.776282] mptcp_add_sock: token 0xd21103fd pi 3, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 3
[   93.784557] mptcp_init4_subsockets: token 0xd21103fd pi 3 src_addr:10.0.0.1:0 dst_addr:11.0.0.2:5001 ifidx: 2
[   93.790231] mptcp_add_sock: token 0xd21103fd pi 4, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 4
[   93.795799] mptcp_init4_subsockets: token 0xd21103fd pi 4 src_addr:11.0.0.1:0 dst_addr:11.0.0.2:5001 ifidx: 3
[   93.926174] mptcp_add_sock: token 0xfdf3bf13 pi 2, src_addr:11.0.0.2:5001 dst_addr:11.0.0.1:53955, cnt_subflows now 2
```

and the same Mininet script with the current trunk:

```
[  258.131815] mptcp_alloc_mpcb: created mpcb with token 0xa95bfe
[  258.136340] mptcp_add_sock: token 0xa95bfe pi 1, src_addr:10.0.0.1:37194 dst_addr:10.0.0.2:5001
[  258.182076] mptcp_alloc_mpcb: created mpcb with token 0x84655eff
[  258.186434] mptcp_add_sock: token 0x84655eff pi 1, src_addr:10.0.0.2:5001 dst_addr:10.0.0.1:37194
[  258.234604] mptcp_add_sock: token 0xa95bfe pi 2, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0
[  258.241485] mptcp_init4_subsockets: token 0xa95bfe pi 2 src_addr:11.0.0.1:0 dst_addr:10.0.0.2:5001 ifidx: 3
[  268.442336] mptcp_close: Close of meta_sk with tok 0xa95bfe
```

**Comment by swetheendra84** [comment]
It was some configuration issue. I tried with different combinations while compiling MPTCP Linux Source code.
