### ISSUE TITLE
throughput and lossrate

### ISSUE THREAD

**Issue by FiratA** [multipath-tcp/mptcp#303]
Hello guys,

i have question.
I want to calculate the throughput and the packet loss rate on each path (on each socket), and currently i am using the following formula to calculae the throughput in Mbit/s: tcp_socket *tp: 

((tp->packets_out * MSS) / rtt) *8 ---> but this is not completely accurate, it is 2-3 Mbit/s higher.
when there is packet loss on pne path, then the packets_out increase so that also the throughput increases which is actually not correct. 

i am using iperf, and iperf shows me a goodput of around 9,5 Mbit/s on each path, but with my calculation i reach around 12 Mbit/s.

i also tried the following: instead of packets_out only i used tp->packets_out - tp->lost_out - tp->retrans_out, but nothing changed.

do you guys have any idea how i can calculate the throughput (from the acked packets) and the packet loss rate?

Thanks in advance.

**Comment by cpaasch** [comment]
You can probably rather track the progress of ```tp->snd_una``` at regular intervals. That should be more accurate.

Keep in mind that MPTCP might duplicate data over the subflows. So indeed, the aggregate of the speeds could be higher than the overall goodput.

**Comment by FiratA** [comment]
@cpaasch thank you for your fast reply.

I will try that.
Do you know of there is any parameter which is showing the acknowledged packets?
For the packet loss calculation i found the lost_out parameter --> lost packets, but not sure how to calculate the rate from that.

**Comment by cpaasch** [comment]
If you track snd_una, you would need at each interval substract the current value from the old value. That way you see the progress of how things are evolving.

**Comment by FiratA** [comment]
@cpaasch i just tested it.

The values are now between 3-7 Mbit/s but most of the time around 5 Mbit/s.

I am using two paths.
datarate 1 and datarate 2 are my old throughput calculation for path1 and path2 and suna1datarate and suna2datarate are the new once using the snd_una parameter.

[datarates.txt](https://github.com/multipath-tcp/mptcp/files/2690669/datarates.txt)
