### ISSUE TITLE
master socket and subsockets

### ISSUE THREAD

**Issue by FiratA** [multipath-tcp/mptcp#306]
Hello Guys, 

i have a question.
How can i see, which sockets are available for MPTCP (subsockets).
Is there a list?

When i use iperf, then i easly can find out the addresses through tp.
But before a  transmission, how can i find them out?

**Comment by matttbe** [comment]
Hi,

I am not sure the understand the question.

Are you talking about this list?

    /proc/net/mptcp_net/mptcp

**Comment by FiratA** [comment]
Thank you for your fast reply, i found out that they can be found in mpcb master_sk and mpcb->connection_list.
I have one more question, how can i assign them a IP address, because i know which ip address i am using on which interface, and i want to identify the socket based on the ip address?

**Comment by matttbe** [comment]
> Thank you for your fast reply, i found out that they can be found in mpcb master_sk and mpcb->connection_list.

OK, I didn't get you were asking where to find that in the source code.

> I have one more question, how can i assign them a IP address, because i know which ip address i am using on which interface, and i want to identify the socket based on the ip address?

Where do you want to do this assignment? From a userspace application using `bind`? Or from a new path manager using `mptcp_init[46]_subsockets`? Do not hesitate to share code because I guess you saw how big was the MPTCP implementation ;-)

**Comment by FiratA** [comment]
@matttbe thank you sir. i have chosen another approach :) but thank you for your help.
