### ISSUE TITLE
How to monitor subflows ?

### ISSUE THREAD

**Issue by vidsgr** [multipath-tcp/mptcp#314]
Is there any way, we can monitor different subflows, interface used by them and subflow specific congestion window, RTT without dumping PCAP

**Comment by vidsgr** [comment]
Is there any way, we can monitor different subflows, interface used by them and subflow specific congestion window, RTT without dumping PCAP

**Comment by teto** [comment]
you can use the linux utility called `ss` or inject some eBFP code that will push this in userspace.

**Comment by hoang-tranviet** [comment]
Also, if you have the source of your application, you can use socket-option MPTCP_INFO:
https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

**Comment by cpaasch** [comment]
Closing as the question has been answered.
