### ISSUE TITLE
[Q] Release cycle of MPTCP v0.93.x

### ISSUE THREAD

**Issue by lenormf** [multipath-tcp/mptcp#317]
Hi,

I guess this is a question to @matttbe.

Is there a release cycle in place for MPTCP v0.93.x (for Linux v4.9) ? Do you produce a new release after a certain amount of major changes have been pushed on `mptcp_trunk`, or depending on how ahead the upstream Linux v4.9.x branch is, or other?

I'm considering backporting commits from `mptcp_trunk` to my own kernel branch regularly (bugfxies), but knowing when the next v0.93.x MPTCP release is coming would allow me to plan things out better (e.g. not spend time backporting a patch if a release is made the next day).

Thanks!

**Comment by matttbe** [comment]
Hi Frank,

> Is there a release cycle in place for MPTCP v0.93.x (for Linux v4.9) ? Do you produce a new release after a certain amount of major changes have been pushed on `mptcp_trunk`, or depending on how ahead the upstream Linux v4.9.x branch is, or other?

For the stable release -1 (v0.93 then), we follow the +1 release cycle. So it means there is a new release when:
* there are important MPTCP bug fixes
* there are important (security) bug fixes coming from upstream
* but most importantly, when we have time :)

but any sync with upstream and backports are normally tested so it should be safe to use the git branch, not only the tags.

> I'm considering backporting commits from `mptcp_trunk` to my own kernel branch regularly (bugfxies), but knowing when the next v0.93.x MPTCP release is coming would allow me to plan things out better (e.g. not spend time backporting a patch if a release is made the next day).

Usually when there are new bug fixes in `mptcp_trunk`, they are also backported to stable branches too. But that's possible we missed some of them. If it is the case, please report this issue on the ML or on Github!

Please also note that Christoph should push a new `mptcp_v0.95` branch soon. Which means we will take less attention to this v0.93 branch.

Does it answer your questions?

**Comment by lenormf** [comment]
Thanks for the information.

>Please also note that Christoph should push a new `mptcp_v0.95` branch soon. Which means we will take less attention to this v0.93 branch.

Does that mean you won't be maintaining the v0.93 branch after v0.95 has been released?

**Comment by matttbe** [comment]
> Does that mean you won't be maintaining the v0.93 branch after v0.95 has been released?

We might continue to backport MPTCP fixes (if there was a bug introduced in an older version) but maybe stop the sync with upstream (except there are important security fixes maybe).

**Comment by lenormf** [comment]
Thanks!
