### ISSUE TITLE
linux-image-4.14.105.mptcp is not booting up

### ISSUE THREAD

**Issue by vidsgr** [multipath-tcp/mptcp#324]
I have tried installing this linux-image-4.14.105.mptcp through apt on ubuntu debian (stretch/testing). It failed to bootup even after trying to manually update initrd image and grub update.

**Comment by matttbe** [comment]
Hi,

By chance, do you have more information about the error (log, error message, etc.). Are you using it in a VM?

Could you try to reproduce the error using the latest `linux-mptcp-0.93`? It is based on the kernel v4.9.161. After the installation, you might have to select it manually at boot time in the grub menu.

Thanks

**Comment by cpaasch** [comment]
Hello,

I am regenerating new kernel-images and will announce the update on the mptcp-dev mailing-list.

Sorry for the hick-up.

**Comment by rootbdfy** [comment]
I see only 1 cpu with new image. May be acpi problem ?

**Comment by cpaasch** [comment]
Argh - more config-file issues. Trying to use the debian-process was definitely the wrong choice. We will get there, promised! ;-)

**Comment by rootbdfy** [comment]
Sorry, can't reboot into new kernel in the next month.
