### ISSUE TITLE
mptcp sk_buff->cb size problem

### ISSUE THREAD

**Issue by vmsearch** [multipath-tcp/mptcp#325]
when i back port the mptcp patch to 3.10.0 kernel，i get the error like this:
arch/x86/net/bpf_jit_comp.c:224:46: error: large integer implicitly truncated to unsigned type [-Werror=overflow

the problem code:
                                       EMIT4(0x4c, 0x8b, 0x47, offsetof(struct sk_buff, data));

how can i fix it?

**Comment by cpaasch** [comment]
You should take the patch from http://multipath-tcp.org/patches/ that is closest to the Linux Kernel version you want to apply it to.

But in general, I would not recommend backporting to such an old kernel.
