### ISSUE TITLE
mptcp change the kabi

### ISSUE THREAD

**Issue by vmsearch** [multipath-tcp/mptcp#329]
the mptcp change too much kabi of kernel.   This may impact the  3rd drivers？

**Comment by matttbe** [comment]
Hi
The current implementation should not change kABI impacting drivers behaviours. Did you notice something wrong with some drivers?

**Comment by vmsearch** [comment]
@matttbe    when i build the kernel, the kabi check report  some infos about the abi break.  such as

dev_get_stats
skb_copy_datagram_iovec
dev_addr_add
dev_mc_add
rtnl_link_register
eth_type_trans
fcoe_libfc_config
crypto_destroy_tfm
ethtool_op_get_link
nf_register_hooks
arp_send
kernel_getsockopt
skb_tstamp_tx
skb_queue_purge
icmpv6_send
eth_change_mtu
dev_get_by_name
skb_copy_expand
__dev_get_by_name
alloc_netdev_mqs
alloc_etherdev_mqs
fcoe_ctlr_recv
device_del
netdev_rx_handler_unregister
__netdev_alloc_skb
register_netdevice
xt_unregister_targets
dev_mc_del
fc_exch_mgr_alloc
free_netdev
eth_validate_addr
napi_get_frags
netif_napi_add
ipv6_skip_exthdr
fc_lport_config
skb_pad
fc_exch_mgr_free
set_cpus_allowed_ptr
dev_set_name
napi_gro_frags
netif_device_attach
skb_push
sock_create_kern
__napi_complete
dev_kfree_skb_irq
skb_dequeue
netlink_broadcast
__dynamic_dev_dbg
skb_copy
kfree_skb
dev_set_mac_address
device_remove_file
kernel_sock_shutdown
dev_open
napi_gro_receive
kernel_setsockopt
sk_free
kernel_bind
__ethtool_get_settings
consume_skb
sock_release
dev_addr_del
nla_put
fcoe_ctlr_link_down
device_register
fcoe_ctlr_init
skb_copy_bits
skb_make_writable
fc_fabric_login
netlink_unicast
skb_queue_head
skb_unlink
kernel_sendmsg
netdev_master_upper_dev_get
netif_rx
crypto_alloc_base
skb_trim
nf_unregister_hooks
dev_trans_start
dev_get_by_index
genlmsg_put
vlan_dev_vlan_id
__genl_register_family
skb_checksum
netif_device_detach
fc_fabric_logoff
lock_sock_nested
root_device_unregister
dev_err
kernel_recvmsg
vlan_dev_real_dev
__root_device_register
pskb_expand_head
genl_unregister_family
netdev_rx_handler_register

**Comment by matttbe** [comment]
@vmsearch Is it `make` which reported that when compiling the kernel? Or is it from another tool?
Which version of the kernel are you using? How did you compile it? What's your `.config` file?

**Comment by jansonzhou** [comment]
I use centos 7 3.10.0-862  kernel,  build the rpm like this 
rpmbuild -ba --with  kabichk  --target=x86_64  kernel.spec

**Comment by cpaasch** [comment]
We do not provide kABI compatibility for out-of-tree 3rd party drivers and modules.

That is in general the Linux Kernel’s philosophy.

**Comment by vmsearch** [comment]
@cpaasch    mptcp can give some tools to evaluate  the change of kabi?

**Comment by cpaasch** [comment]
I'm not aware of a tool. Usually, you just recompile the 3rd party module within the MPTCP-kernel's source. That should do the job.
