### ISSUE TITLE
When there is a wan network quality is bad, it will affect all download speeds, but the upload speed is still very good.

### ISSUE THREAD

**Issue by suyuan168** [multipath-tcp/mptcp#334]
When there is a wan network quality is bad, it will affect all download speeds, but the upload speed is still very good.
The correct  settings, I have wan1 and wan2 and wan3. 3 wan ports. The mptcp settings are enabled for all three wans. My wan1 is very good quality ADSL line, uploading 20M/S download has 50M/S, delay is 40ms. My wan2 is a usb 4g signal is very poor, upload 10M / S, download 2M / s, delay 1000ms. My wan3 is also adsl, upload 10M / S download has 20M / S delay 10ms.

Now the problem is that there are many ways to wan, when one of the wan download speed is very bad, it will make theoverall download speed slower, but does not affect the upload speed.
Is there any way to make a wan with a very bad download speed affect other wan speeds?
The same is true without affecting the upload speed. I think there is definitely a reason.
  1. If I follow the correct upload of 40M/S, the download has 72M/s. In theory, this is the case.
  2. But the problem is, if my wan2 signal is very bad, this will drag down the download speed of the entire openmptcprouter. The download speed will be reduced by half, which is about 30M/S. However, the upload speed does not affect 40M/S.
  3. If I am disconnecting the network cable of wan2 now. Then the upload speed is 30M/S. The download speed is 70M/S.

**Comment by matttbe** [comment]
Hi,

If one path is bad, it doesn't mean the whole MPTCP connections will be bad. It will depend on many things, mainly the size of the window (if you prefer to increase the BW but the latency as well) or how the packet scheduler will use the different paths. There are different schedulers, maybe some like BLEST could be better for this use-case.

**Comment by teto** [comment]
alternatively you could also use the ECF scheduler MPTCP ECF (Earliest
Completion First) Path Scheduler. <https://ylim.mybluemix.net/mptcp_ecf/>

Le mar. 23 avr. 2019 à 21:09, Matthieu Baerts <notifications@github.com> a
écrit :

**Comment by cpaasch** [comment]
@teto - Interesting! Someone should sometime somehow try to get this scheduler into mptcp_trunk ;-)

**Comment by dweb32** [comment]
@cpaasch - I am actually working on a ported version of ECF at the moment. But I still do not consider it stable enought. I still need to do some evaluation.

@matttbe - yes, I think BLEST can be more beneficial in this configuration.

@suyuan168 - do you need the extra capacity of the cellular path or can you just configure it as backup? Do you optimize for maximal throughput or minimal latency?

**Comment by teto** [comment]
@s6dlwebe is your work on ECF public ? I might be able to help.

**Comment by dweb32** [comment]
@teto not yet published, but I got it already working for 0.94 and mptcp_trunk so far. The only thing that bugs me is that I was still not able to proove a better performance compared to BLEST and minRTT in my testbed. So I just plan to do an extra integration before raising any pull request just to be sure.

**Comment by suyuan168** [comment]
I tried bbr/cubic/olia but the results are the same.

**Comment by suyuan168** [comment]
@s6dlwebe  Thanks for the answer I need the maximum throughput, with delay optimization. But there is currently no way to achieve it.
@matttbe  BLESTWhat is it? Is it a new scheduler? Is there in mptcp?
Thank you for your answer, I really hope that 4G LTE can add all the broadband to facilitate the outdoor network. Can reduce the delay. No improvement now. Very confused, because I can't effectively increase the bandwidth regardless of whether I use 2 4G or 5 4G.

**Comment by matttbe** [comment]
>  @matttbe BLESTWhat is it? Is it a new scheduler? Is there in mptcp?

Yes, it is a new scheduler, it is in MPTCP (`mptcp_trunk` branch): https://github.com/multipath-tcp/mptcp/pull/300

**Comment by matttbe** [comment]
For those here who are using more than 2 subflows and see issues when one subflow is bad, could you recompile the kernel after having applied this patch please?

```diff
diff --git a/net/mptcp/mptcp_sched.c b/net/mptcp/mptcp_sched.c
index 70b247be6509..18c3559b0d48 100644
--- a/net/mptcp/mptcp_sched.c
+++ b/net/mptcp/mptcp_sched.c
@@ -308,7 +308,6 @@ static struct sk_buff *mptcp_rcv_buf_optimization(struct sock *sk, int penal)

                                def_p->last_rbuf_opti = tcp_jiffies32;
                        }
-                       break;
                }
        }

```

So you need to remove this break: https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/net/mptcp/mptcp_sched.c#L311

(the code is similar in v0.95 and v0.94 if you prefer to compile a stable branch).

It seems the scheduler, in the optimisations, was penalised only one subflow, the first it found, maybe not the right one. With this modification, we will penalise all the slowest subflows that have sent the last data. That might improve the situation for you.
If someone can test, I can apply that in the code.
