### ISSUE TITLE
Transport the UDP traffic using MPTCP 

### ISSUE THREAD

**Issue by jeetu28** [multipath-tcp/mptcp#337]
We are using the MPTCP + shadowsocks to transport the TCP traffic from one Linux Box to another and is working pretty fine.
But there is another case where we have UDP stream that we want to send over to same MPTCP enabled Linux Machine.
We tried enabling enabling shadowsocks with options like -u (allow udp & tcp redirection) -U (allow only udp) on both client and server but no luck . 
Is there any way So that we can leverage the MPTCP enabled kernel while transporting the UDP traffic over multipaths .....?

**Comment by matttbe** [comment]
Hi,

> But there is another case where we have UDP stream that we want to send over to same MPTCP enabled Linux Machine.
> We tried enabling enabling shadowsocks with options like -u (allow udp & tcp redirection) -U (allow only udp) on both client and server but no luck .

Do you know what shadowsocks do with the UDP traffic? Does it encapsulate it in a TCP connection/tunnel?
Do you have the same behaviour when not using an MPTCP kernel?

>  Is there any way So that we can leverage the MPTCP enabled kernel while transporting the UDP traffic over multipaths .....?

By definition, MPTCP is an extension of TCP. If you want your UDP traffic to use MPTCP, you need to encapsulate it in TCP. I don't know if ShadowSocks can do that. OpenVPN can do that. Note that encapsulate TCP in (MP)TCP is not a good idea.

It depends what kind of UDP traffic you want to encapsulate in MPTCP but in theory, most services use UDP to have a short latency. (Some protocols like QUIC use UDP for other reasons.)
With a proxy TCP, you will for sure add delays, especially if there are losses.

**Comment by jeetu28** [comment]
Well, We have tried forwarding the UDP traffic through shadow socks but it didnt even worked, It did not do the proxy for UDP traffic like it does for TCP.
The UDP traffic is a L2TP Tunnel. 
Yes, another approach could be to use TCP openvpn Tunnel But as you mentioned that it will not be such a good idea to transport Encapsulated TCP under MPTCP, what else can be the option then to use multipath for a UDP traffic, When we are having 3-4 Links available at the same time in same Machine.

**Comment by matttbe** [comment]
could you use OpenVPN for UDP traffic (only) and ShadowSocks for TCP traffic (only)?

**Comment by jeetu28** [comment]
You mean TCP OpenVPN for UDP traffic  via the MPTCP?

**Comment by matttbe** [comment]
Yes, having one proxy for UDP (TCP OpenVPN) and one for TCP (*socks). Ideally without encryption.

**Comment by madhanraj** [comment]
there can be multiple ways 
1) UDP direct, TCP proxified 
2) UDP and TCP proxified with same Proxy Server (Same IP)
3) UDP and TCP proxified with a different Proxy server (Different IP)
4) UDP over TCP and TCP proxified 

I haven't seen many issues with 1, 2, 4
3 can be an issue with few applications. They expect TCP and UDP from the same hop or IP

**Comment by jeetu28** [comment]
Hi Madhanraj,
Thanks for responding on this.
1.With the option 1, we can not leverage the benefit of multipath.
2. we tried to proxy the traffic with the shadowsocks but no luck.
3. This we did not tried.
4. Yes, this is the one i have recently tried and thats what was decided in last post from mptcp dev. 
we used the TCP vpn to route the udp traffic and then proxified this tcp vpn traffic over shadowsocks. this way we are able to use the multipath feature of the kernel. 
But still we are under testing with this. Don't know how reliable is this. 
Do you forsee any issue in transporting udp over tcp tunnel and then proxified to the proxy server?
NOTE:- we are using proxy server and tcp vpn server on same server

**Comment by madhanraj** [comment]
1,2,3 It is expected that we cannot multipath UDP packet by multipathing TCP
UDP gets relayed as UDP packets. TCP binds as a new connection. That is how SOCKSv5 works. 
AFAIK, shadowshocks does not work for UDP. The iptables does not fetch destination IP of the actual server.

4) Have used TCP tunnel for UDP + TCP SOCKS. 
> Yes, it works and not much issue. However, adds delay to the UDP. You can tweak a little on the congestion control to make specific socket not to react to retransmission (Neither straight forward nor user space options available though). 
The probable use of UDP is to reduce the latency as much as possible. However, converting to TCP and proxying might add additional delays for sure. Up to your application design.

**Comment by jeetu28** [comment]
One more point,
if we dont proxify the tcp vpn traffic and let it go directly then it dont use the multipath. any idea why
