### ISSUE TITLE
netlink path manager: always fail when no source address specified

### ISSUE THREAD

**Issue by teto** [multipath-tcp/mptcp#338]
I wonder if there is not an issue here https://github.com/multipath-tcp/mptcp/blob/ea0df9906272456f6f72422606e89b5d12763114/net/mptcp/mptcp_netlink.c#L873
If you don't set if MPTCP_ATTR_SADDR4, then the code will try to find the source address from the loc_id but even if it does, it exits the loop (`break`) just to fail via the `goto create_failed;`.
The behavior is different if MPTCP_ATTR_SADDR4 is set. 
It seems the problem occurs for mptcp v6 as well.

**Comment by matttbe** [comment]
Hi Matthieu,

Good catch, I will have a look at this!

**Comment by matttbe** [comment]
Indeed, a `goto found` was missing.

I just sent a fix to mptcp-dev ML.
I preferred to add a boolean, it looked clearer and the compiler will certainly produce the same thing.

**Comment by cpaasch** [comment]
Fix applied. Closing :)

**Comment by teto** [comment]
that was fast (as usual :p ) ! Thanks guys !
