### ISSUE TITLE
Crash in mptcp_send_active_reset on 32-bit arch

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp#34]
Message from syslogddebian at Apr 14 01:32:33 ...kernel:[138647.861520] EIP:
[] mptcp_send_active_reset+0x49/0x11f SS:ESP 0068:f6ca7f18

This message is shown when the test 'so_linger_onoff-1_linger-0_rst.pkt' is run on debian-7.4.0-i386 with mptcp 0.88v. (test from 'examples/tests/sock_headers' folder)

Running the same test on ubuntu (13.10) x64 there is any problem.

**Comment by redward** [comment]
This message is shown only when a 'write' call on the socket is used after setsocktopt function on so_linger field. The only call to setsockopt does nothing.

**Comment by vvinothkumar** [comment]
Where would I find "examples/tests/sock_headers"?

**Comment by cpaasch** [comment]
https://github.com/ArnaudSchils/packetdrill_mptcp

**Comment by okias** [comment]
I think I get that message on my 64bit mptcp_3.12.x at commit 107e6783415cf995b5a31b71396573f2857c4307 (New 3.12 maintenance release).

I was just shutting down computer when I seen this, not enough long to make screenshot.

**Comment by jpronans** [comment]
I'm not clear on how this manifested itself. Was it a segfault and crash or just the message above?
Thanks.
John

**Comment by cpaasch** [comment]
This specific test-case was crashing the kernel in user-context. So, your application basically crashed at the kernel-level.

But, the bug in the code could also have crashed the entire kernel.

**Comment by jpronans** [comment]
Ah, this may explain something I was seeing on a VM but hadn't had a chance to debug yet.  I think I was experiencing both an application crash and kernel crash. 
Thanks.
