### ISSUE TITLE
Interface disappears in CentOS 7 after kernel installation

### ISSUE THREAD

**Issue by reuvenperetz** [multipath-tcp/mptcp#340]
Hello,
I've installed mptcp kernel 4.14.110 on my CentOS 7 virtual machine, and for some reason, I can't see eth0 anymore when running ifconfig.
The thing is, that before I installed this kernel version, I installed mptcp kernel 4.14.70 and had no such problem, but after configuring in grub to boot from 4.14.110 and rebooting my VM - I'm having this problem.
I didn't find any useful idea online and would love for any suggestion.

I'm not sure what additional info would help here, but here some commands I used (as explained above):

[root@localhost ~]# uname -a
Linux localhost 4.14.110.mptcp #11 SMP Fri Apr 5 20:02:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
[root@localhost ~]#  lspci | grep Ethernet
0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)

Thanks,
Reuven

**Comment by matttbe** [comment]
Hello,

I am not sure why an update would remove this. Except if the options are different? Maybe eth0 has been renamed? Logs from `dmesg` should indicate which interfaces have been seen by the kernel I think.

Also, don't hesitate to use the latest 4.14.x kernel (4.14.127.mptcp) or 4.19.x kernel released this week.

Matt

**Comment by reuvenperetz** [comment]
Thanks, Matt!

Okay. I'll try to update the kernel version to see if it still happens.
What do you mean by "options are different"?

**Comment by matttbe** [comment]
> What do you mean by "options are different"?

Kernel options might be different between these two versions. I don't remember when @cpaasch updated them.

**Comment by reuvenperetz** [comment]
oh.. I see.
I'll check it as well... Thanks!

**Comment by cpaasch** [comment]
@reuvenperetz  - did you compilethe kernel yourself or did you pick the pre-compiled images?

**Comment by reuvenperetz** [comment]
The last one. 
I followed these instructions (http://multipath-tcp.org/pmwiki.php/Users/RPM), but couldn't find kernel-headers for that to install, so upgraded to 4.14.110 (using the same yum repository).

**Comment by cpaasch** [comment]
Ah! Yes, then it might be a kernel-config issue. Please go and pick the latest latest build and let me know.

**Comment by reuvenperetz** [comment]
Will do! I'll update how it goes.
Thanks!

**Comment by reuvenperetz** [comment]
Unfortunately, it didn't help.
I installed version 4.14.127 and still can't see the interface.
I've tried to get some info from dmesg, but it didn't tell me much:
[root@localhost ~]# dmesg | grep 0b:00
[    0.131301] pci 0000:0b:00.0: [15ad:07b0] type 00 class 0x020000
[    0.132004] pci 0000:0b:00.0: reg 0x10: [mem 0xfd3fc000-0xfd3fcfff]
[    0.132682] pci 0000:0b:00.0: reg 0x14: [mem 0xfd3fd000-0xfd3fdfff]
[    0.133357] pci 0000:0b:00.0: reg 0x18: [mem 0xfd3fe000-0xfd3fffff]
[    0.134082] pci 0000:0b:00.0: reg 0x1c: [io  0x5000-0x500f]
[    0.136003] pci 0000:0b:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    0.136421] pci 0000:0b:00.0: supports D1 D2
[    0.136421] pci 0000:0b:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.136602] pci 0000:0b:00.0: disabling ASPM on pre-1.1 PCIe device.  You can enable it with 'pcie
_aspm=force'
[    0.207980] pci 0000:0b:00.0: BAR 6: assigned [mem 0xfd300000-0xfd30ffff pref]

When I boot with the kernel which doesn't give me this problem, I see:
[root@localhost ~]# dmesg | grep 0b:00
[    0.127576] pci 0000:0b:00.0: [15ad:07b0] type 00 class 0x020000
[    0.128423] pci 0000:0b:00.0: reg 0x10: [mem 0xfd3fc000-0xfd3fcfff]
[    0.129003] pci 0000:0b:00.0: reg 0x14: [mem 0xfd3fd000-0xfd3fdfff]
[    0.129831] pci 0000:0b:00.0: reg 0x18: [mem 0xfd3fe000-0xfd3fffff]
[    0.130422] pci 0000:0b:00.0: reg 0x1c: [io  0x5000-0x500f]
[    0.132432] pci 0000:0b:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    0.132894] pci 0000:0b:00.0: supports D1 D2
[    0.132895] pci 0000:0b:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.133082] pci 0000:0b:00.0: disabling ASPM on pre-1.1 PCIe device.  You can enable it with 'pcie
_aspm=force'
[    0.206589] pci 0000:0b:00.0: BAR 6: assigned [mem 0xfd300000-0xfd30ffff pref]
[    1.156539] vmxnet3 0000:0b:00.0: # of Tx queues : 2, # of Rx queues : 2
[    1.163669] vmxnet3 0000:0b:00.0 eth0: NIC Link is Up 10000 Mbps
[    2.719228] vmxnet3 0000:0b:00.0 eth0: intr type 3, mode 0, 3 vectors allocated
[    2.719879] vmxnet3 0000:0b:00.0 eth0: NIC Link is Up 10000 Mbps

One more thing I tried is to set two NICs for my virtual machine, and I've noticed this weird thing:
With 4.14.127 I can see eth0 now (but not eth1), but with 4.14.70 I can see two interfaces (eth0 and eth1).
I guess the problem origins from some misconfiguration (but it's just a guess).

Since I updated the kernel version from 4.14.70, only because I couldn't find a devel package for it, I tried to install something in between 4.14.70 and 4.14.110, and now I have version 4.14.91 which doesn't give me this problem (and installed kernel-devel successfully).
I hope I'll get back to that in the future, but in the meanwhile, I think I'm going to work with 4.14.91 on my machine.
Thanks a lot for you help Matt and Christoph!

**Comment by matttbe** [comment]
It seems `CONFIG_VMXNET3` has been disabled in March: https://github.com/multipath-tcp/mptcp-scripts/commit/31cf45a8eff758fa8a2b5856a3000df73acbdb30

@cpaasch where did you pick the new kconfig from? :)

@reuvenperetz if you want to test the latest version and if you can compile the kernel by yourself, don't hesitate to enable `CONFIG_VMXNET3` from menuconfig.
http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

**Comment by reuvenperetz** [comment]
oh! That makes sense! I didn't notice the new NIC wasn't vmxnet3 but e1000...

> @reuvenperetz if you want to test the latest version and if you can compile the kernel by yourself, don't hesitate to enable CONFIG_VMXNET3 from menuconfig.
http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

Will do!

**Comment by cpaasch** [comment]
Ok, I will add CONFIG_VMXNET3 back to the kernel-config of the pre-compiled images.

I picked the config from debian, so I would have thought it has all the important pieces. We really need to find a better way to generate these configs...

**Comment by matttbe** [comment]
Maybe we should take the kconfig from Fedora or RHEL when building .rpm?

**Comment by atomrofler** [comment]
Installed ubuntu with 4.19.55. vmxnet3 seems is to be disabled.

**Comment by matttbe** [comment]
Indeed, in the v0.95 .deb files, `CONFIG_VMXNET3` is not set.
I should be ON in next versions.

If you do need this driver, best is maybe for the moment to install the latest v0.94 version (kernel v4.14.146) where we have `CONFIG_VMXNET3=m`

  sudo apt-get install linux-mptcp-4.14

(you might have to change GRUB settings or manually select the v4.14 kernel when booting the kernel)

**Comment by atomrofler** [comment]
Already done. Thank you!

**Comment by matttbe** [comment]
I propose to close the ticket as the original question was for v4.14 kernel
