### ISSUE TITLE
amiusingmotcp.de reports "Not Enabled"

### ISSUE THREAD

**Issue by webgenius-coder** [multipath-tcp/mptcp#342]
I tried accessing amiusingmptcp.de site on a Samsung S10 device. The site reports MPTCP as "Not enabled"

I believe S10 has MPTCP enabled. I need to check with S10 since I am planning to use S10 as reference device for implementing MPTCP on my device.

Any help on this greatly appreciated. Thanks!

**Comment by matttbe** [comment]
Hi

The best would be to ask Samsung developers. I guess if MPTCP is added on this device, it will not be used by default, only if an app asks for it.

If you use amiusingmptcp.de, MPTCP can also be blocked by the network.

Maybe the best is to use a terminal app (Termux?) and launch: `sysctl net.mptcp` or `ls /proc/sys/net/mptcp`.

**Comment by madhanraj** [comment]
Not enabled by default

**Comment by matttbe** [comment]
Thank you @madhanraj for the confirmation! I didn't think about pinging you for that, that would have been quicker :)

I propose to close the issue then!

**Comment by webgenius-coder** [comment]
Is there any way to enable this for validating on Samsung devices?

**Comment by madhanraj** [comment]
Not possible in customer device. 
If rooting the device is possible, then it can be enabled I guess.
