### ISSUE TITLE
Not able to find MP_CAPABLE key in SYN packet

### ISSUE THREAD

**Issue by ManuAryan** [multipath-tcp/mptcp#344]
We are trying to verify the MP_CAPABLE param in the Samsung S10 device.
>> .We enabled the download booster option and tried to download 2gb data from playstore and started sniffing the same since the wlan and modem initial connection ,we verified the SYN packet to look for the MP_CAPABLE using wireshark ( Version 2.2.2 (v2.2.2-0-g775fb08)) yet we couldn't find the MP_capable param in the tcp initial connection.
However the document says there will be an additional MP_capable added to support this feature
Kindly help us ! are we missing something **here?**

Please find the screenshot. 
![Screenshot_20190718-121823_Settings 1](https://user-images.githubusercontent.com/16059484/61435582-6cd9b780-a956-11e9-8367-b45720a8ca5c.jpg)

**Comment by cpaasch** [comment]
@madhanraj - Can you comment?

**Comment by matttbe** [comment]
Hi,

I am not sure MPTCP is used for this. It seems it splits the big HTTP file in smaller bits and download different chunks from different networks.

**Comment by madhanraj** [comment]
Yes,  the above setting is for HTTP RANGE request. 
MPTCP setting can be found only in Korea and few other devices. 
P.S even if you get a Korean S10, MPTCP might not work during roaming

**Comment by matttbe** [comment]
@madhanraj  Thank you for your input!

Closing the ticket then.

**Comment by ManuAryan** [comment]
Thank you for answering questions.
