### ISSUE TITLE
Verifying MPTCP feature on nexus 5 device

### ISSUE THREAD

**Issue by ManuAryan** [multipath-tcp/mptcp#347]
Hi All,

I have flashed MPTCP kernel boot image to nexus 5 as suggested and also installed two APKs to enable the multiple interfaces on the device , though the amiusingmptcp.de website shows mp_tcp is enabled in the device when we tried downloading file from http://multipath-tcp.org/snapshots/ we didn't see any difference in the through put . It was same as downloading with mp_tcp disabled.
Are we missing something here ? and also please help us know how to validate session with MP TCP support.

We couldn't collect tcpdump too as adb root is not working in nexus 5 only adb shell su works .
Is there anyway we can collect tcp packet capture ?

Attached screenshots for setting configured in APKs. we are able to see both rmnet and wlan0 interfaces are up
![Screenshot_2019-07-26-19-19-05](https://user-images.githubusercontent.com/16059484/61959066-364c0e80-afe0-11e9-9f90-2ee96b980b13.png)
![Screenshot_2019-07-26-19-21-35](https://user-images.githubusercontent.com/16059484/61959068-364c0e80-afe0-11e9-8dc6-00593e70f0af.png)

**Comment by matttbe** [comment]
Hi

> though the amiusingmptcp.de website shows mp_tcp is enabled in the device

Can you try with LTE only? Maybe a middlebox is blocking MPTCP.

> Are we missing something here ? and also please help us know how to validate session with MP TCP support.

Packets traces on both the clients and the server would help.
(maybe turn `mptcp_debug` sysctl to 1 and look at `dmesg` but traces should be better for the moment)

> We couldn't collect tcpdump too as adb root is not working in nexus 5 only adb shell su works . Is there anyway we can collect tcp packet capture ?

Can you then do `adb shell` then `su`, then `tcpdump -i <lte iface> -s 150 -w <output> tcp`?
I guess there are some apps that can do some packet captures. But you need root access on the device.

**Comment by ManuAryan** [comment]
Thanks for answering the question , we learned middlebox is blocking MPTCP in wlan ,anyways it worked when we tried through hotspot.
