### ISSUE TITLE
Handling of locator ids with the netlink path manager

### ISSUE THREAD

**Issue by teto** [multipath-tcp/mptcp#348]
Hi,

This is a question about the netlink path manager. I am trying to create new subflows from my client. The module's `mptcp_nl_genl_create` expects local and remote ids. 
Remote ids can be collected along the way but I wonder how to choose the local id.
Are local ids supposed to be handled via the userspace client ? What are the constraints for assigning local ids ? Is it just a bijection (intf id, ip) <-> local id ? in which case the module could take care of it ?

NB: I have been looking into improving wireshark dissection of the MPTCP netlink protocol. Will share the results when it's a bit cleaner (had no idea how far lua scripting can let you go with wireshark, quite cool)

**Comment by cpaasch** [comment]
@teto - this issue here slipped through the cracks :-/ I think we can close it, right? :)
