### ISSUE TITLE
How can I start debuging?

### ISSUE THREAD

**Issue by yuemingjiang** [multipath-tcp/mptcp#35]
I port mptcp to Android phone, but it not work.  The data flow is mainly on WIFI interface(99.9%), nearly not go through via mobile interface. 
ip route:
default via 192.168.0.1 dev wlan0 
default via 10.69.75.166 dev rmnet0 
10.69.75.164/30 dev rmnet0  proto kernel  scope link  src 10.69.75.165 
10.69.75.166 dev rmnet0  scope link 
74.125.235.197 via 10.69.75.166 dev rmnet0 
192.168.0.0/24 dev wlan0  scope link 
192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.9  metric 321 
192.168.0.1 dev wlan0  scope link 
210.21.196.6 via 10.69.75.166 dev rmnet0  src 10.69.75.165 
221.5.88.88 via 10.69.75.166 dev rmnet0  src 10.69.75.165

**Comment by gdetal** [comment]
What type of application/traffic do you use/generate ? Is it HTTP download or upload ?
If it is HTTP, are you sure that MPTCP works ? Is http://amiusingmptcp.com showing a big green YES  ?
Do you have policy routing configured ? (output of ip rule and then ip route show table XXX)

**Comment by yuemingjiang** [comment]
gdetal, Thank you very much!
I can see the "Yes! You are all set to use MPTCP on this device!....", although the net speed is very very slowly.
Which application can be used for testing? If MPTCP can boost the network, the server must support MPTCP, right?

**Comment by gdetal** [comment]
@yuemingjiang there is an iperf application available on android that you can use or download from an MPTCP-enabled HTTP server.
You didn't answer my last question: do you have policy routing configured ?

**Comment by yuemingjiang** [comment]
@gdetal I didn't configure routing policy manually, I think netd do this. I port android_external_iproute2 and android_system_netd to my Android phone.

**Comment by yuemingjiang** [comment]
cat /proc/net/mptcp
  sl  loc_tok  rem_tok  v6 local_address                         remote_address                        st ns tx_queue rx_queue inode
   0: 3DEBDB7B 3DEBDB7B  0 0900A8C0:E544                         29D01C3C:0050                         01 01 00000000:00000000 20948

**Comment by gdetal** [comment]
netd does not by default enable 3G and WiFi and does not configure policy routing. Did you modify netd ?

**Comment by yuemingjiang** [comment]
@gdetal, I check the 3G and WIFI status, they are enable, I can "ping -I rmnet0 ..." and "ping -I wlan0 ..." meantime.
But about the policy routing, I have no idea how to configure it, now it behave as default setting.

**Comment by gdetal** [comment]
Look here then: https://listes-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2014-01/msg00027.html

**Comment by yuemingjiang** [comment]
@gdetal Thanks!
I already install this APK, and enable 3G + WIFI at the same time.

Do you have any guideline about the policy routing configure?

**Comment by gdetal** [comment]
The APK should configure automatically the policy routing, please give the output of ip rule show.

**Comment by yuemingjiang** [comment]
root@hammerhead:/ # ip route
default via 192.168.0.1 dev wlan0 
default via 10.73.105.33 dev rmnet0 
10.73.105.0/26 dev rmnet0  proto kernel  scope link  src 10.73.105.32 
10.73.105.33 dev rmnet0  scope link 
74.125.235.195 via 10.73.105.33 dev rmnet0 
192.168.0.0/24 dev wlan0  scope link 
192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.9  metric 321 
192.168.0.1 dev wlan0  scope link 
210.21.196.6 via 10.73.105.33 dev rmnet0  src 10.73.105.32 
221.5.88.88 via 10.73.105.33 dev rmnet0  src 10.73.105.32 

root@hammerhead:/ # ip rule
0:  from all lookup local 
99: from all to 10.73.105.33 lookup main 
99: from all to 74.125.235.195 lookup main 
32766:  from all lookup main 
32767:  from all lookup default

**Comment by gdetal** [comment]
It seems that the policy routing is not  configured at all. Have you executed and enabled the application from the APK ?

**Comment by yuemingjiang** [comment]
@gdetal Yes, I executed and enabled the application from the APK. I will check the command sent by  APK now. 
Thanks!

**Comment by yuemingjiang** [comment]
@gdetal I don't think APK can auto configure the routing policy. It just send following command:
ip link set dev wlan0 multipath on
ip link show dev wlan0
ip link show dev rmnet0

Do you have any idea to configure the routing policy manually?

**Comment by gdetal** [comment]
The app is supposed to do it. Do you have rooted your phone (it requires `su`) ?

To do it manually you have to follow: http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting

**Comment by yuemingjiang** [comment]
@gdetal Yes, I have rooted my phone, and can see the APK sending command to iproute2.
I follow the guideline, but an error encountered when I set 

ip route add default scope global nexthop via 192.168.0.1 dev wlan0
RTNETLINK answers: Invalid argument

By the way, wow, You are the author of android_packages_apps_MPTCPControl-ics!! You are a Great man!

**Comment by yuemingjiang** [comment]
@gdetal Until now, I'm confuse about mptcp. One quetions:
Apk on Android phone with MPTCP create several sockets to download file from Internet server, if the server is not MPTCP enable, then 3G & Wifi interface can downloading in same time?

**Comment by gdetal** [comment]
No it does not. It only enables the fact that 2 interfaces are up and running and that the routing is correctly configured such that MPTCP connections (so to an MPTCP-enabled server) can use both paths.

**Comment by yuemingjiang** [comment]
@gdetal Thanks! Your kindly help is very useful. 
I need a technical which can boost download speed from a normal server( mostly is MPTCP unable ) via  3G + Wifi. So I think MPTCP is not match my requirement.

**Comment by gdetal** [comment]
Indeed, there are download boosters that are available on android (as the one advertised by Samsung for the S5). These solutions are based on multiple HTTP range requests. See https://play.google.com/store/apps/details?id=it.opbyte.superdownload

I am closing the issue as in the end it is not related to MPTCP.
