### ISSUE TITLE
TCP error, Impossible Socket state 13

### ISSUE THREAD

**Issue by cifvts** [multipath-tcp/mptcp#358]
In our systems, we have this error in the kernel log:
```
[Thu Aug 22 11:25:58 2019] TCP: tcp_fin: Impossible, sk->sk_state=13
[Thu Aug 22 15:53:37 2019] TCP: tcp_fin: Impossible, sk->sk_state=13
...
[Thu Aug 22 17:06:31 2019] TCP: tcp_fin: Impossible, sk->sk_state=13
[Thu Aug 22 17:40:08 2019] TCP: tcp_fin: Impossible, sk->sk_state=13
```
MPTCP version 0.95, Kernel 4.19.56

**Comment by cpaasch** [comment]
This here means that we receive a valid FIN, while in RST_WAIT-state. Which means we somehow got past the check in ```mptcp_handle_options```. I can't see how that would ever happen...

Might be worth to add a ```dump_stack()``` call in tcp_fin, to see where this here is coming from.

**Comment by cifvts** [comment]
If you give me a pathc I can apply to and hopefully I will have a server on which to put it soon. I will able then to give you feedback on this and also #352.

**Comment by cifvts** [comment]
If it might help you, this is a log with the logging patch from #352 with some of this message popping up.
[kern.log_state13.tar.gz](https://github.com/multipath-tcp/mptcp/files/3622627/kern.log_state13.tar.gz)

**Comment by cpaasch** [comment]
Took some time, and finally being able to repro... but I managed to fix this. Will send a patch soon.

**Comment by matttbe** [comment]
> Will send a patch soon.

This patch has been applied in the repo and stable branches.

Please re-open the issue if needed.

**Comment by cifvts** [comment]
That's brilliant, thanks a lot for your work. Not sure how big was this problem but I am happy to help. Cheers!
