### ISSUE TITLE
Establishing MPTCP capable server

### ISSUE THREAD

**Issue by ManuAryan** [multipath-tcp/mptcp#359]
I have seen in many websites that people have set up MPTCP capable local servers for validating and throughput purpose, Can you mention the procedure to setup MPTCP local server which can be accessed both by WAN and WLAN for file download and upload , this is required for both uplink and downlink.

**Comment by matttbe** [comment]
Hi

I am not sure we can really help on that. All we can say is that  on your server running an MPTCP kernel, you need to configure the routing. Once it is done, you can install any service you like: HTTP server, IPerf3 server (easy to do download/upload), etc.

- http://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP?
- http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting
- http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP
- http://software.es.net/iperf/
