### ISSUE TITLE
openwrt shadowsocket libev failed as Protocol not avaliable

### ISSUE THREAD

**Issue by wttat** [multipath-tcp/mptcp#365]
i  use this mptcp patch https://github.com/xedp3x/openwrt/blob/mptcp/target/linux/generic/patches-3.10/622-mp-tcp.patch
to add  mptcp into my openwrt 14.07 based on realtek linux kernel 3.10.49
but i didnt use the iproute2 mptcp patch
shadowsock version is 3.3.1  
as i can read from the kernel output 
MPTCP stable release v0.87.4

my server use the lateset mptcp patch on Ubuntu 18.04 linux kernel 4.19.55  same ss version 3.3.1
 dmesg can read 
[47226216.987400] MPTCP: Stable release v0.95
i set the iptables as the ss-redir recommanded

# Create new chain
iptables -t nat -N SHADOWSOCKS
iptables -t mangle -N SHADOWSOCKS

# Ignore your shadowsocks server's addresses
# It's very IMPORTANT, just be careful.
iptables -t nat -A SHADOWSOCKS -d 123.123.123.123 -j RETURN

# Ignore LANs and any other addresses you'd like to bypass the proxy
# See Wikipedia and RFC5735 for full list of reserved networks.
# See ashi009/bestroutetb for a highly optimized CHN route list.
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

# Anything else should be redirected to shadowsocks's local port
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345

# Add any UDP rules
ip route add local default dev lo table 100
ip rule add fwmark 1 lookup 100
iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01

# Apply the rules
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
iptables -t mangle -A PREROUTING -j SHADOWSOCKS

# Start the shadowsocks-redir
ss-redir -u -c /etc/config/shadowsocks.json -f /var/run/shadowsocks.pid

except the udp part because it however make dns down
 i replaced the server address and the port to mine

the ss-redir run but output first
**enable multipath MPTCP
initai..
listen..
running from root user 
then it failed as 
failed to enable multipath TCP:Protocol not available**

it wil happen the same as i run by the luci-shadowsock or in the bash
how could i solve this ?
the server's MPTCP worked fine when i use a RPI3B  runing the latest MPTCP
is it because the different version of MPTCP?

**Comment by matttbe** [comment]
Hi @wttat 

>  MPTCP stable release v0.87.4

Your kernel is too old and no longer maintained.

I *guess* at that time it was not possible for an application to ask to use MPTCP using the setsockopt (I guess that's what your app is trying to do if I understand the reported error). If you cannot update your kernel, the only solution I see is to remove the option in your application to use MPTCP (by editing `/etc/config/shadowsocks.json`?)  and make sure all apps can use mptcp: `sysctl -w net.mptcp.mptcp_enabled=1`.

If you need support regarding your application, please see with the devs of the app (shadowsocks). If you need support for the MPTCP kernel, please use a recent one (MPTCP v0.94 for v4.14 or more recent).

**Comment by wttat** [comment]
> Hi @wttat
> 
> > MPTCP stable release v0.87.4
> 
> Your kernel is too old and no longer maintained.
> 
> I _guess_ at that time it was not possible for an application to ask to use MPTCP using the setsockopt (I guess that's what your app is trying to do if I understand the reported error). If you cannot update your kernel, the only solution I see is to remove the option in your application to use MPTCP (by editing `/etc/config/shadowsocks.json`?) and make sure all apps can use mptcp: `sysctl -w net.mptcp.mptcp_enabled=1`.
> 
> If you need support regarding your application, please see with the devs of the app (shadowsocks). If you need support for the MPTCP kernel, please use a recent one (MPTCP v0.94 for v4.14 or more recent).

thx very much for your answer
realtek only offer the openwrt firmware as linux kernel 3.10 , I really wanna to upgrade the kernel also but I couldn't.

by the time mptcp 0.87 didn't have the mptcp_enabled option and is default on .

shadowsock-libev support the mptcp option  since 3.1.1 by Nov 2017 it maybe a problem

may I ask  that is it   really impossible for this kind of setsockopt usage?

or how could I test the MPTCP in 0.87 without a proxy? VPN instead?

**Comment by matttbe** [comment]
> by the time mptcp 0.87 didn't have the mptcp_enabled option and is default on .

Then you only need to disable the option in Shadowsocks software to use MPTCP. MPTCP will be used whenever it is possible but mainly between the router and the MPTCP server.

> may I ask that is it really impossible for this kind of setsockopt usage?

You can still modify the kernel you are using to add the setsockopt usage. Without the setsockopt, I guess MPTCP will be used between the client and the router. But I don't think it is a problem: if your client doesn't support MPTCP, it should fallback to TCP

**Comment by matttbe** [comment]
I propose to close the issue if you don't mind as the kernel cannot be upgraded. It is then only a software issue and the worst case is: MPTCP is used for all TCP connections.

**Comment by wttat** [comment]
> I propose to close the issue if you don't mind as the kernel cannot be upgraded. It is then only a software issue and the worst case is: MPTCP is used for all TCP connections.

i got that . thx very much .
just one more question .will the mptcp 0.87 work with mptcp 0.95 the same time?
or i have to downgrade the other to 0.87 at once

**Comment by matttbe** [comment]
>  just one more question .will the mptcp 0.87 work with mptcp 0.95 the same time?

It should, they are supposed to implement the same protocol. But because v0.87 is quite old, you might hit bugs.
