### ISSUE TITLE
Increase latency on purpose?

### ISSUE THREAD

**Issue by Llorx** [multipath-tcp/mptcp#367]
Hi,

This is simple. I have 2 subflows (but going to upgrade to 3 in the future). They run over LTE and the latency/bandwidth changes a lot due to saturated antennas (we stream video on street events which have a lot of people congregated in a zone). Maybe we add satellite which has constant 700ms latency. The only thing that satellite changes is bandwidth. By the way right now I'm only talking about 2 saturated LTE connections.

We are used to have a lot of hardware with propietary systems, but they do almost the same: Send video through different connections. They add about 5 seconds latency (a lot when talking about a TCP connection, but we don't have any problem with that) so they can deal with asymmetric connections and always changing conditions for each ISP. If they send a packet through a subflow, they wait a lot of time before resending and such. Works like a charm for our environment, the problem is that we want also to RECEIVE (not send) aggregated RTMP streams (that's why we are starting with MPTCP).

I would like to know if there's an option for MPTCP like those propietary ones. To increase resend times and such to take care of all subflows changes. I don't mind having really high latency times as long as bandwidth is aggregated.

I'm asking because on testing we had really nice results, but on an event, when the antennas started to saturate, the RTMP streams started to drop a lot so we had to disable MPTCP and deal with our everyday problems again.

On the next event we are going to change to BLEST, and also thought on STTF, but reading this paper seems that is not going to help much: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8584135

Seems that MPTCP tries its best to have the best latency possible (which is good), but also seems that is the culprit of the problem when having asymmetric subflows, but I would like to focus on the ones that don't mind latency and want to focus on the maximum aggregation possible. I'm reading a lot about this and can't seem to find anything, so I'm asking here just in case I'm missing something.

I also guess that congestion control has something to do here. We are now with `bbr` but we are going to try `wvegas` next time: https://ieeexplore.ieee.org/document/6459978

The problem we have is that we cannot do continuous testing. We can test saturated antennas only when streaming, and we cannot have faulty streams, so we can only test just before we are going to start streaming, when all the people is on spot, meaning we can only test one or two configurations each couple of weeks :-/

Also, I don't know if tuning something under `sysctl net.tcp...` will also help, by increasing windows, or looking something about reordering levels. Do a single MPTCP connection use those configurations, or will each subflow use this configurations? Or they only work under normal TCP connections and MPTCP connections reads other options? If someone can throw a bit of light, will help a lot.

EDIT: Just made a fast test. `wvegas`, `lia`, `olia` and `balia` congestion controls had a really really bad performance. Also BLEST performed a bit worse than default. I'm now with `cubic`, which seems to have a slow start, but gets a steady result. Will test next stream over this.

EDIT2: By adding 300ms simulated delay to the second interface, the bandwidth dropped by a lot on all congestion controls and both shedulers. I'm going to try to modify system TCP options next week.

**Comment by matttbe** [comment]
Hi,

> Also, I don't know if tuning something under sysctl net.tcp... will also help, by increasing windows, or looking something about reordering levels. Do a single MPTCP connection use those configurations, or will each subflow use this configurations? Or they only work under normal TCP connections and MPTCP connections reads other options? If someone can throw a bit of light, will help a lot.

You can see MPTCP as a combination of multiple TCP flows, as a "big" TCP pipe. In other words, you can continue to tune MPTCP with `sysctl net.tcp.(...)`.
If you would like to use a maximum of bandwidth with subflows that have a huge latency, you have to increase both the sent and received buffers (tcp_rmem, tcp_wmem and maybe tcp_mem if you are limited in memory). If you start sending on a link with 700ms latency, it means that what you send on the other links might have to wait ~700ms on the buffers on the other side. Then you can try to estimate how much you might need in the buffer. Start by using two times this value I guess.

One last thing, when you change the sysctl values, it is valid only on the new socket so better to restart the server app when you change them.

**Comment by Llorx** [comment]
Perfect, thank you. Will test all that with simulated latency this week.

**Comment by mstrolo** [comment]
did you manage to work something with this?

**Comment by Llorx** [comment]
> did you manage to work something with this?

No. Any configuration I tried gave bad results. I ended with propietary systems as they are more configurable for bad performing links.
