### ISSUE TITLE
How to use the specific link for mptcp subflow by certain ip or domain ?

### ISSUE THREAD

**Issue by wttat** [multipath-tcp/mptcp#369]
mptcp path-manager is full-mesh . 4g_eth1 and wan_eth0.2  for uplink.
 how could i set it mptcp's subflow to use the specific link ? for example the youtube uses eth1 and the gmail uses eth0.2 for mptcp

**Comment by matttbe** [comment]
If you want some connections to use only one link and some other connections another link, you don't need MPTCP but setting proper routing rules.

    ip route add <youtube/prefix> via eth1
