### ISSUE TITLE
Rebase to Linux 5.4 (update: ported / linked in the comments)

### ISSUE THREAD

**Issue by arter97** [multipath-tcp/mptcp#372]
Linux 5.4 is the new LTS release:
https://www.kernel.org/category/releases.html

It'd be great to see MPTCP getting rebased to Linux 5.4 as well since 4.19 is more than a year old at this point :)

**Comment by arter97** [comment]
I've managed to bring the mptcp_trunk branch to v5.4.

The conflicts were relatively trivial, except commit c681edae33e86ff27be2d6cc717663d91df20b0e ("net: ipv4: move tcp_fastopen server side code to SipHash library"):
https://github.com/arter97/mptcp/commit/01d84bb0e5a5f5e9d0561f4fb790beb8e57f70c7

As a non-net expert, I had to revert it for now.

But rest of it seems to work fine.
I created 2 VMs with 8 virtual NICs each limited to 10 MiB/s and both default and roundrobin scheduler seems to work ok without any error logs to dmesg.
https://twitter.com/arter97/status/1209139573789356034

FWIW, I'm not able to reproduce #373 here.
As I'm writing, the VM A is sending /dev/urandom to VM B and so far no issues at 90 GiB.

I'll put my port on my GitHub repository here:
https://github.com/arter97/mptcp/commits/mptcp_trunk

GitHub seems to go total haywire if I send a pull-request as it'll include every commits from v5.1..v5.4.

I hope you guys can use/reference mine to bring v5.4 support more easily.

Thanks.

**Comment by matttbe** [comment]
Hi @arter97 

Thank you for the good work! And sorry for the lack of answer due to holiday period and MPTCP upstream work.

It is not easy to review a merge without re-doing the work but I am sure we can get inspiration from what you did. We also do need to fully support TFO. I am not sure how long it will take to do this move but it is definitively planned.

Cheers,
Matt

**Comment by matttbe** [comment]
Hi @arter97 

Christoph found some time to do this rebase on 5.4 and I think he resolved the conflicts you mentioned with TFO.

Thank you for having prepared his work! I guess we can close this ticket.
