### ISSUE TITLE
Question about the mptcp code related change 

### ISSUE THREAD

**Issue by patrickkh7788** [multipath-tcp/mptcp#374]
If I install the kernel and set `net.mptcp.mptcp_enabled = 1`,  is there any things need I to do with my app ?  for example  apply patch to nginx ?

how do I confirm it work with tcpdump or other tools? (I install same kernel on server  side and client  side)

**Comment by kpeletidis** [comment]
Not sure which change you are talking about. If both machines run an mptcp kernel then a tcpdump or tshark session on both machines should show MPTCP fields in the TCP header. You can start a very generic capture on a machine by doing something like:
```
tshark -i any
```

All you have to do on the client side is a simple connection request such as:
```
curl your.server.com
```
For more details on how to capture network traffic read the tshark (or tcpdump) online documentation.
