### ISSUE TITLE
 [RST] was sent on the second subflow immediately after [SYN, ACK] was received---almost the same with the issue164

### ISSUE THREAD

**Issue by leidemon** [multipath-tcp/mptcp#375]
hi, mptcp team:
    I use the mptcp to do some test,but i face one issue like issue164,can you give me some suggestions?
use:
    ubuntu 16.04
    mptcp 0.95
   shadowsocks-libev-3.3.3
I use one PC for ss-server,config as follow:
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"123456",
    "timeout":600,
    "method":"aes-256-cfb",
    "verbose":2,
    "mode":"tcp_and_udp"
}
cmd: ss-server -c config.json --mptcp -u
one for the ss-local(with privoxy for agent),configure as follow:
{
    "server":"192.168.9.42",
    "server_port":8388,
    "local":"127.0.0.1",
    "local_port":1080,
    "password":"123456",
    "timeout":600,
    "method":"aes-256-cfb",
    "mode":"tcp_and_udp",
    "verbose":2
}
cmd:ss-local -c config.json --mptcp -u
and the privoxy conf:
listen-address 127.0.0.1:8118
forward-socks5 / 127.0.0.1:1080 . 
ss-local have two interface:
192.168.9.43
192.168.9.199
when I test for mptcp aggregate Download,[RST] was sent on the second subflow immediately after [SYN, ACK] was received, would some one else can give me some suggestions?

**Comment by leidemon** [comment]
mptcp config:
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = redundant
net.mptcp.mptcp_enabled = 1

**Comment by leidemon** [comment]
in server side,the MPCapableFallbackSYNACK  is increasing for each connect;

**Comment by cpaasch** [comment]
Please take a look at my comment in https://github.com/multipath-tcp/mptcp/issues/164 - Can you gather individual pcaps on each interface? Just to confirm my theory of asymetric routing.

**Comment by leidemon** [comment]
> 请查看我在[＃164中的](https://github.com/multipath-tcp/mptcp/issues/164)评论-您可以在每个界面上收集单独的pcap吗？只是为了确认我的非对称路由理论。
hi, cpaasch:
I comment in issue164

**Comment by leidemon** [comment]
it can be closed @cpaasch
