### ISSUE TITLE
redundant call to tcp_tsq_write () in tcp_tsq_handler()

### ISSUE THREAD

**Issue by dejeneboru** [multipath-tcp/mptcp#386]
https://github.com/multipath-tcp/mptcp/blob/e0573b7437b00b96784a779dcad871772a677699/net/ipv4/tcp_output.c#L811
Is the call to tcp_tsq_write() in tcp_tsq_handler at the referenced point redundant or intended for some other purpose?

**Comment by cpaasch** [comment]
No, it is intended. The call to tcp_tsq_write with the meta-sk as an argument triggers the transmission on the meta-sk. What makes you think that it could be redundant?
