### ISSUE TITLE
FIN flag within DSS option crashes the kernel in user-context

### ISSUE THREAD

**Issue by redward** [multipath-tcp/mptcp#39]
When we send a packet with DSS and FIN flag to a mptcp v0.88 kernel then it crashes. 

// Receive a segment with a FIN flag. Problem here
//0.300 < PF. 1001:2002(1000) ack 1 win 257 'nop,nop,TS val 700 ecr 100, dss dack4 dsn4 FIN'
// This one is ok 
0.300 < PF. 1001:2001(1000) ack 1 win 257 'nop,nop,TS val 700 ecr 100, dss dack4 dsn4'
0.300 > . 1:1(0) ack 2002 win 488 'nop,nop,TS val 175 ecr 700, dss dack4 ' 

Test was done on Linux x64 (Ubuntu 13.10) and x32 (Debian wheezy), the entire file of test is: https://github.com/ArnaudSchils/packetdrill_mptcp/blob/master/packetdrill/gtests/net/packetdrill/examples/tests/ioctl/ioctl-siocinq-client.pkt

This actually occurs when a FIN flag is set but the DLL is not incremented by 1 ( DLL +1 for the FIN flag)

**Comment by cpaasch** [comment]
Fixed by:
commit c30b683da0db73e60d4695b45be665adc51c568b
Author: Christoph Paasch christoph.paasch@uclouvain.be
Date:   Sun Jul 13 21:07:03 2014 +0200

```
mptcp: Do not continue processing when meta has been closed
```
