### ISSUE TITLE
Can MPTCP_SCHED_DATA_SIZE be changed?

### ISSUE THREAD

**Issue by ytxing** [multipath-tcp/mptcp#395]
I am trying to put some other bytes in redsched_cb, which is 

`(struct redsched_cb *)&tp->mpcb->mptcp_sched[0];`

and of course it will exceed the limit of 
```
#define MPTCP_SCHED_DATA_SIZE 8
	u8 mptcp_sched[MPTCP_SCHED_DATA_SIZE] __aligned(8);
```
thus I change it into 
```
#define MPTCP_SCHED_DATA_SIZE 16
	u8 mptcp_sched[MPTCP_SCHED_DATA_SIZE] __aligned(8);
```

make &make install is successful, but it seems that when it runs the code that change the new redsched_cb, the kernel crashes.

I am wondering if it is possible to have extra space in the mpcb?
Please help!
Good day :D

**Comment by cpaasch** [comment]
What is your crash-log? Is the only change the increase in size of MPTCP_SCHED_DATA_SIZE?
