### ISSUE TITLE
sha256 functions prevents kernel compile

### ISSUE THREAD

**Issue by rstanislav** [multipath-tcp/mptcp#396]
Hello! I'm trying to cross compile RPi4 kernel (5.4.y.) with mptcp trunk patch, after few recent updates its broken now:

> make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs

>  LD      .tmp_vmlinux.kallsyms1
> net/mptcp/mptcp_ctrl.o: In function `mptcp_key_sha256':
> mptcp_ctrl.c:(.text+0x794): undefined reference to `sha256_update'
> mptcp_ctrl.c:(.text+0x7a0): undefined reference to `sha256_final'
> net/mptcp/mptcp_ctrl.o: In function `mptcp_hmac_sha256':
> mptcp_ctrl.c:(.text+0xe48): undefined reference to `sha256_update'
> mptcp_ctrl.c:(.text+0xe54): undefined reference to `sha256_final'
> mptcp_ctrl.c:(.text+0xf1c): undefined reference to `sha256_update'
> mptcp_ctrl.c:(.text+0xf28): undefined reference to `sha256_final'
> Makefile:1080: recipe for target 'vmlinux' failed
> make: *** [vmlinux] Error 1

Host is ubuntu 18.04 x64, libssl-dev is installed, version 1.1.1

Can someone help me please ?

**Comment by matttbe** [comment]
Hello

Can you check if `CONFIG_CRYPTO_SHA256` kernel config is enabled please?

**Comment by rstanislav** [comment]
It was checked as loadable module (m) - changed to builtin, compiled without problems! Spend almost a day to find a solution. Thanks alot for help!
