### ISSUE TITLE
How to add routes in following topology?

### ISSUE THREAD

**Issue by rockamble** [multipath-tcp/mptcp#398]
Description :-
------------
I have been trying to write code for MPTCP Proxy. 
For that I have 3 Linux systems and they all running on Ubuntu 16(H1,H2 and H3).On H1 I am running as TCP server and H3 I am running with MPTCP client. Middle device (H2) it is acting as MPTCP proxy and it will do all MPTCP to TCP conversion (both vise versa).

Problem :-
-------
The problem is if I wanted to work my code, both P1 and P2 ports of H3 Host should be reachable to P1 port of H1 Host. Currently I am doing socket programming where Server is running on H1  and client is running on H3. As I have added static route on H3 for H1 through 10.1.100.20 , it is always taking only single path. Not taking 10.1.200.20 path. 
Due to this MPTCP is not working. The configuration as below 

Configuration :-
============
In Host H3 :-
"ip rule add from 10.1.100.2 table 1
 ip rule add from 10.1.200.2 table 2

ip route add 10.1.100.0/24 dev enp0s8 scope link table 1

ip route add 10.1.1.0/24 dev enp0s8 scope link table 1

ip route add default via 10.1.100.20 dev enp0s8 table 1

ip route add 10.1.200.0/24 dev enp0s9 scope link table 2

ip route add 10.1.1.0/24 dev enp0s9 scope link table 2

ip route add default via 10.1.200.20 dev enp0s9 table 2
 "

and on H1 
"
ip route add 10.1.0.0/16 dev enp0s8
"

But still it is not working..

Could please help me with ip configuration of MPTCP on following topologyt ? 
My topology as below  
![untitled](https://user-images.githubusercontent.com/33920734/89194308-d0b43a00-d5c4-11ea-8583-ceeb8c76277d.png)

**Comment by matttbe** [comment]
Hi,

This issue doesn't seem to be linked with MPTCP as you only send ICMP echo request (ping).
I guess you need to make sure H2 accept to forward packets (sysctl ip_forward + check firewall) and route the packets to the right interface (it should not be an issue as H2's p2 and p3 are in the same LAN as H3's p1 and p2). Also H3 should reply on the right interface. IP rules / routes you added should do the job except that the IPs don't correspond with your schema. So check the IP ;-)

I'm going to close this issue as it is not linked to MPTCP.
Feel free to re-open it if I missed something.
