### ISSUE TITLE
Link to mailing-list on website does not work

### ISSUE THREAD

**Issue by julijane** [multipath-tcp/mptcp#399]
The title probably says it all. When I click on the link to the mailing-list, I only get an empty page. 

I have a question about a possible use for mptcp and I thought that it is best to ask that on the mailing-list, right?

**Comment by cpaasch** [comment]
Thanks for reporting this! I fixed the link.

It is at https://sympa-2.sipr.ucl.ac.be/sympa/info/mptcp-dev
