### ISSUE TITLE
Window scale is not respected when the RCVBUF is specified before listen

### ISSUE THREAD

**Issue by redward** [multipath-tcp/mptcp#40]
If you try out regular TCP, then after setting the recv-buffer to 40KB, the socket will behave different when sending the SYN/ACK.

With regular TCP, the SYN/ACK will have a window-scale of 0 (because the window-field of the TCP header can announce the fixed 40KB).
Actually, MPTCP is failing there. It announces a window-scale of 7 although it should not.
Found with on 
https://github.com/ArnaudSchils/packetdrill_mptcp/blob/master/packetdrill/gtests/net/packetdrill/examples/tests/sock_headers/so_rcvbuf-sndbuf_set_before_listen.pkt (line 22)

referenced from ArnaudSchils/packetdrill_mptcp#5

**Comment by cpaasch** [comment]
So, due to comment https://github.com/ArnaudSchils/packetdrill_mptcp/issues/5#issuecomment-42130106 this issue is actually fixed, no?

**Comment by redward** [comment]
Yes, that's right
