### ISSUE TITLE
how bulid Debian 10 mptcp

### ISSUE THREAD

**Issue by birdofprey** [multipath-tcp/mptcp#401]
os:Debian 10 Gnu/Linux
kernel: Linux localhost.localdomain 5.8.0-0.bpo.2-amd64 #1 SMP Debian 5.8.10-1~bpo10+1 (2020-09-26) x86_64 GNU/Linux
help me how build itself mptcp, enable mptcp ???

**Comment by matttbe** [comment]
Hi,

This kernel is not supported yet. But you can switch to an older kernel.

Some debian packages are available:
* http://multipath-tcp.org/pmwiki.php/Users/AptRepository
* https://github.com/multipath-tcp/mptcp/releases

To compile another branch yourself, please refer to http://multipath-tcp.org/pmwiki.php/Users/DoItYourself
