### ISSUE TITLE
(Q) Disabling MPTCP Between Reboots

### ISSUE THREAD

**Issue by metheis** [multipath-tcp/mptcp#403]
Hello,

I have MTCP enabled on an AWS EC2 instance running Debian Stretch. I've tested it and can see it working (for example, using `curl http://www.multipath-tcp.org`). However, when I want to disable MPTCP with `sudo sysctl -w net.mptcp.mptcp_enabled=0`, this works for the current boot but MPTCP re-enables after a reboot. I did play around with writing a script to disable at boot, but so far that actually hasn't worked. Is there a way to disable MPTCP that persists through reboots without installing a clean kernel?

**Comment by cpaasch** [comment]
Hello. Yes, sysctl settings do not persiste across reboots.

One way to disable is would be to put the sysctl settings in /etc/sysctl.conf
