### ISSUE TITLE
MPTCP version 1

### ISSUE THREAD

**Issue by praupadhyaya** [multipath-tcp/mptcp#405]
Hi,

I am using the following version of MPTCP
sudo dmesg | grep MPTCP
[    0.351608] MPTCP: Stable release v0.95.1

Works mighty fine for version 0, but when I change the version to 1 with --
sysctl -w net.mptcp.mptcp_version=1
-- I find that it does not work properly.
Specifically, when my application is the connection initiator using the above (and is the first data sender towards a server), I see that the messages are not following RFC 8684. Specifically, when the initiator sends the data for the first time, as per RFC 8684, it is obligated to MP_CAPABLE option along with data level parameters, but that is not happening. I see that DSS is also being sent unexpectedly during the handshake but it does not contain the relevant parameters for the subflow sequence mapping creation for the server.

Is the version 1 implementation at all stable or just a work in progress ?

Regards
-Prashant

**Comment by matttbe** [comment]
Hi Prashant,

> Works mighty fine for version 0, but when I change the version to 1 with --
> sysctl -w net.mptcp.mptcp_version=1
> -- I find that it does not work properly.

MPTCP 0.95 doesn't fully support MPTCPv1 (RFC 8684). The full support is in progress in the `mptcp_trunk` branch of this repo.
Is it an issue for you to use this one?

Cheers,
Matt
