### ISSUE TITLE
i downloaded mptcp v0.95.1 for ubuntu 20.04

### ISSUE THREAD

**Issue by trinadh61** [multipath-tcp/mptcp#411]
i have configured according to the steps proivdided in the doc but still i am not able use mptcp in my laptop

trinadh@trinadh-HP-Laptop-15-bs0xx:~$ sudo uname -r
4.19.126.mptcp

trinadh@trinadh-HP-Laptop-15-bs0xx:~$ sysctl net.mptcp
net.mptcp.mptcp_checksum = 1
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 3
net.mptcp.mptcp_version = 0

**Comment by matttbe** [comment]
Hi

What does _i am not able use mptcp in my laptop_ mean for you?

Did you check with this command? `curl multipath-tcp.org`
Or visited http://amiusingmptcp.de ?
