### ISSUE TITLE
Blank screen issue while trying to boot into mptcp kernel

### ISSUE THREAD

**Issue by Sidvik0110** [multipath-tcp/mptcp#412]
Hey
I have installed the ubuntu mptcp kernel v 4.19.126 by following the steps in the following link:http://multipath-tcp.org/pmwiki.php/Users/AptRepository

After downloading , when i have tried to boot into the mptcp kernel from grub menu during startup, the boot successfully processes till the login page. After entering the password, the screen becomes blank and will be stuck there. 

Need help in overcoming this problem.TIA

**Comment by matttbe** [comment]
Hello

Maybe you need a newer version.

Would you eventually be able to compile the kernel? You can use the `mptcp_v0.95` branch (default one)
http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

(We should probably build new packages. But we also need to find an alternative to Bintray now...)
