### ISSUE TITLE
why is my packet size only 40 bytes and ack is 1480 bytes？

### ISSUE THREAD

**Issue by JianHaoYu** [multipath-tcp/mptcp#413]
In mininet, I set up a client in H1 (a host with two network ports, an IP address of 10.0.0.2 and an IP address of 10.0.2.2) and a server in H2(IP address is 10.0.1.2). When the client requests the server, the server will send 100mb of data to the client. However, when I use tcpprobe to capture packets, I find that the length of packets sent from 10.0.1.2 to 10.0.2.2 / 10.0.0.2 is only 40 bytes, while the length of packets sent from H1 to H2 is 1480 bytes. Why does this happen?

This is part of the output file of tcpprobe：

5.646215760 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 221696
5.646665815 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 224256
5.647320075 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 227328
5.647879295 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 229888
5.648487052 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 232960
5.649084729 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 235520
5.649698844 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 238592
5.650269337 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 241664
5.650911418 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 244224
5.651483104 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 247296
5.652169282 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 249856
5.652785216 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 252928
5.653379563 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 255488
5.654066119 10.0.2.2:45877 10.0.1.2:6868 1480 0xb2cd661a 0xb2cd661a 10 2147483647 57344 231793 258560
5.691307874 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b4c851 0xe1b3e931 40 2147483647 146944 124989 57344
5.691358688 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b4d379 0xe1b3eec5 41 2147483647 150016 124453 57344
5.692097063 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b4dea1 0xe1b3f459 42 2147483647 153088 123987 57344
5.692827452 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b4e9c9 0xe1b3f9ed 43 2147483647 155648 123669 57344
5.693021046 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b4f4f1 0xe1b3ff81 44 2147483647 158720 123481 57344
5.694025644 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b50019 0xe1b40515 45 2147483647 161280 123252 57344
5.694600882 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b50b41 0xe1b40aa9 46 2147483647 164352 123175 57344
5.695186545 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b51669 0xe1b4103d 47 2147483647 167424 123066 57344
5.695755702 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b52191 0xe1b415d1 48 2147483647 169984 123043 57344
5.696362048 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b52cb9 0xe1b41b65 49 2147483647 173056 123073 57344
5.696702120 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b537e1 0xe1b420f9 50 2147483647 175616 123174 57344
5.697218998 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b54309 0xe1b4268d 51 2147483647 178688 123261 57344
5.697961809 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b54e31 0xe1b42c21 52 2147483647 181248 123400 57344
5.699538741 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b55959 0xe1b431b5 53 2147483647 184320 123504 57344
5.699633814 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b56481 0xe1b43749 54 2147483647 187392 123790 57344
5.699720116 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b56fa9 0xe1b43cdd 55 2147483647 189952 123970 57344
5.700233295 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b57ad1 0xe1b44271 56 2147483647 193024 124138 57344
5.700905429 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b585f9 0xe1b44805 57 2147483647 195584 124275 57344
5.701531135 10.0.1.2:6868 10.0.2.2:45877 40 0xe1b59121 0xe1b44d99 58 2147483647 198656 124479 57344

**Comment by matttbe** [comment]
Hi

TCPProbe kernel module has been deprecated for a while and removed upstream between v4.14 and v4.19 I think.
I'm not sure what I'm looking here. Is it the len from TCP point of view? In this case, it makes sense if you still have to add 20B for the IPv4 layer.
