### ISSUE TITLE
What method should I have to track the congestion window of MPTCP?

### ISSUE THREAD

**Issue by JianHaoYu** [multipath-tcp/mptcp#414]
What method should I have to track the congestion window of MPTCP? Is the congestion window tracked by tcpprobe still reliable?

**Comment by matttbe** [comment]
Hi,

I think TCP Probe kernel module has been deprecated and removed a long time ago, no?
Maybe we are not talking about the same thing.

I guess the best is to use eBPF and/or tracing functions. There is a TCP Probe tracing function I think `/sys/kernel/debug/tracing/events/tcp/tcp_probe/`.

**Comment by yogiex** [comment]
maybe since ubuntu 16.04 tcpprobe has been removed from the kernel, but maybe [```ss -i```](https://man7.org/linux/man-pages/man8/ss.8.html) command can trace cwnd
