### ISSUE TITLE
Bintray stop service 

### ISSUE THREAD

**Issue by codati** [multipath-tcp/mptcp#416]
hi, 
your repository https://dl.bintray.com/multipath-tcp/mptcp_deb will soon be shut down 
more details => https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
thank you for reading me (:

**Comment by matttbe** [comment]
Hi,
Thank you for your message.
Unfortunately we didn't find any good alternatives. So we moved all new `.deb` and `.rpm` packages to GitHub Releases page: https://github.com/multipath-tcp/mptcp/releases

**Comment by matttbe** [comment]
Feel free to react to our last message on our mailing list ;-)

**Comment by codati** [comment]
thx
you plan to take a deb repository later?

**Comment by matttbe** [comment]
Not for the moment. It seems that most people are OK by manually downloading .deb packages (4) from Github.
But feel free to react on the ML: https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2021-05/msg00000.html
