### ISSUE TITLE
Cooperation offer

### ISSUE THREAD

**Issue by avgustskuratov** [multipath-tcp/mptcp#417]
Hello. I use your technology (https://github.com/PhSchmitt/MultipathControl) in my project and would like to offer cooperation or ask for help (not for free). I found this contact on the site tessares.net, which was listed in the github profile of one of the project participants (https://github.com/gdetal).

**Comment by matttbe** [comment]
This message has been detected as a spam. If this was a mistake, please contact Tessares via its website.
