### ISSUE TITLE
How can i use the mptcp socket api?

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#419]
I followed <a href="http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP" target="_blank">**this**</a> to use the MPTCP Socket API.
my mptcp setting (mptcp_enabled=2) -> <a href="https://i.stack.imgur.com/kKebQ.png" target="_blank">**mptcp setting**</a>

I wrote the echo server(localhost) and client in c. 
And I used tcpdump to capture between(server - client).

But I failed, because packet not with the mptcp option.
this is tcpdump result. (test message is "hello") -> <a href="https://i.stack.imgur.com/aoPxF.png" target="_blank">**result image**</a>

This is echo server source code -> <a href="https://i.stack.imgur.com/YwE3V.png" target="_blank">**mptcp echo server**</a>
And this client source code -> <a href="https://i.stack.imgur.com/pEB9W.png" target="_blank">**mptcp client**</a>

<br>

What did I miss?
Please tell me a solution.
Thank you.

**Comment by matttbe** [comment]
Hi,

Please don't share code with image but with text.

I guess you are using an app on your loopback? MPTCP is disabled for local only traffic (e.g. `127.0.0.1`).

**Comment by pak-ji** [comment]
Right.. I tested it with a loopback address.

Thank you for letting me know the solution.
I won't upload the source code as an image next time.

Thank you so much!!

**Comment by matttbe** [comment]
You're welcome
