### ISSUE TITLE
compile at ubuntu server 18.04 LTS error

### ISSUE THREAD

**Issue by yogiex** [multipath-tcp/mptcp#421]
hello, after bintray service is down, i tried to compile mptcp but got error like this

![image](https://user-images.githubusercontent.com/31413884/116006272-b0d21400-a634-11eb-8282-05b9d6f1478a.png)

sry, but i dont know how to compile kernel from scratch before

thanks

**Comment by matttbe** [comment]
Hi yogiex,

You can still download the different packages on Github Release page: https://github.com/multipath-tcp/mptcp/releases

To compile it yourself, you can follow instructions there: http://multipath-tcp.org/pmwiki.php/Users/DoItYourself
Note that you can also follow other instructions: there is nothing specific to MPTCP there, you can follow generic instructions about how to build a kernel. Just make sure to enable MPTCP in the config.

**Comment by yogiex** [comment]
okay i will try it
