### ISSUE TITLE
Merging the latest trunk branch causes conflict with linux-stable

### ISSUE THREAD

**Issue by arter97** [multipath-tcp/mptcp#424]
Commit 8cc351a3d44462b81caf3d654e7498898a95af60 from linux-5.4.y or 435ccfa894e35e3d4a1799e6ac030e48a7b69ef5 from mainline ("tcp: Prevent low rmem stalls with SO_RCVLOWAT.") causes conflict with recent trunk commit: d8e3bd88da5fbee8e8ccfc9b3f4aa56e11ee06ce ("mptcp: avoid meta window shrink impacting subflow").

```
  CC      net/ipv4/tcp.o
  CC      net/ipv4/tcp_input.o
net/ipv4/tcp.c: In function ‘tcp_stream_is_readable’:
net/ipv4/tcp.c:510:21: error: implicit declaration of function ‘tcp_receive_window’; did you mean ‘tcp_receive_window_now’? [-Werror=implicit-function-declaration]
  510 |                 if (tcp_receive_window(tp) <= inet_csk(sk)->icsk_ack.rcv_mss)
      |                     ^~~~~~~~~~~~~~~~~~
      |                     tcp_receive_window_now
net/ipv4/tcp_input.c: In function ‘tcp_data_ready’:
net/ipv4/tcp_input.c:4847:13: error: implicit declaration of function ‘tcp_receive_window’; did you mean ‘tcp_receive_window_now’? [-Werror=implicit-function-declaration]
 4847 |             tcp_receive_window(tp) > inet_csk(sk)->icsk_ack.rcv_mss &&
      |             ^~~~~~~~~~~~~~~~~~
      |             tcp_receive_window_now
```

Just wanted to ask for a proper fix from the MPTCP developers instead of fixing it blindly myself.

Can I just replace those with `tcp_receive_window_now()`?

Thanks!

**Comment by matttbe** [comment]
Hi!

> Can I just replace those with `tcp_receive_window_now()`?

Yes, that's correct.
That's what we did in our stable branch, see commit 8b7c5e4a105b9d561eb5fb8cba26efbac861bc7 ;-)

**Comment by arter97** [comment]
Thanks!

May I ask which repository does the commit 8b7c5e4a105b9d561eb5fb8cba26efbac861bc7 belong to?

**Comment by matttbe** [comment]
Arf, sorry, I missed the first char: https://github.com/multipath-tcp/mptcp/commit/f8b7c5e4a105b9d561eb5fb8cba26efbac861bc7
The last commit on mptcp_v0.95 branch.
