### ISSUE TITLE
Scheduler questions currently being implemented

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#426]
I have completed the MPTCP socket API (MPTCP_SCHEDULER, MPTCP_PATH_MANAGER, MPTCP_INFO) test provided in this link.
https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

I got curious after the experiment.

Q) Is there any other scheduler in the current MPTCP Linux kernel other than "default(LL), "RRR", "redundant", and "BLEST"?

Thank you. :)

**Comment by matttbe** [comment]
Hi,

> Q) Is there any other scheduler in the current MPTCP Linux kernel other than "default(LL), "RRR", "redundant", and "BLEST"?

We don't have other ones than these ones in this public repository: https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/net/mptcp/Kconfig#L92

By looking at the different published papers on the subject, there are others but they have not been "upstreamed" to this repository.

Can I close the ticket?
