### ISSUE TITLE
Questions) Netlink Path Manager 

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#430]
I want to control the subflow of MPTCP dynamically in Application Layer.

I understand that this can be done through MPTCP's Netlink Path-manager.

I'm asking you because there's no explanation for netlink path-manager on www.multipath-tcp.org

Do you have a detailed usage guide for Netlink Path-manager?

**Comment by VenkateswaranJ** [comment]
You can you use `https://github.com/intel/mptcpd` or take it as reference and implement your own.

**Comment by matttbe** [comment]
Hello,

Good point, there is nothing in our wiki about it. I just added a small section to start with:

> New in v0.95: 'netlink': This path-manager can be controlled from the userspace. See the [source code](https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/include/uapi/linux/mptcp.h) for the API documentation or [mptcpd](https://github.com/intel/mptcpd) for an Open-Source daemon. 

See: https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

This Netlink API was also described in: https://dl.acm.org/doi/abs/10.1145/2716281.2836113 (other websites also provide the PDF)

Note that a more advanced socket API has been studied but never applied in this repo:
* https://github.com/bhesmans/mptcp
* https://datatracker.ietf.org/doc/html/draft-hesmans-mptcp-socket-03
* https://dl.acm.org/doi/abs/10.1145/2959424.2959433 (other websites also provide the PDF)

I hope you don't mind if I close this ticket if provided info from @VenkateswaranJ  and I are enough

**Comment by pak-ji** [comment]
thanks :) @VenkateswaranJ  @matttbe
