### ISSUE TITLE
ip tools missing in the release binary packages

### ISSUE THREAD

**Issue by wizd** [multipath-tcp/mptcp#436]
Sad to hear that Bintry no longer hosting the apt repository. I need the tools to keep tcp connections alive. Please include the IP tools if possible. thank you!

**Comment by matttbe** [comment]
Hi,

Indeed, Bintray was an easy solution for us, that's a shame we no longer have it. We didn't find any good alternatives.

Instead, we uploaded all binaries to Github.
You can then find IPRoute2 binaries there too: https://github.com/multipath-tcp/iproute-mptcp/releases
Not that you can also compile the source code to obtain the same binaries if needed.

Feel free to re-open this ticket if needed.
