### ISSUE TITLE
MPTCP Netlink API question.

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#437]
- Generic Netlink API
https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/include/uapi/linux/mptcp.h
> <pre> Commands for MPTCP:
>   * MPTCP_CMD_ANNOUNCE: token, loc_id, family, saddr4 | saddr6 [, sport]
>   * Announce a new address to the peer.
> </pre>

<br>

Q1) Is the token used here local_token or remote_token?
And
Q2) Where can I get a token? (_**"/proc/net/mptcp_net/mptcp"**_ => Is it okay to use tokens that exist in that path?)

**Comment by VenkateswaranJ** [comment]
`Q1) Is the token used here local_token or remote_token?`
Local token
`Q2) Where can I get a token? ("/proc/net/mptcp_net/mptcp" => Is it okay to use tokens that exist in that path?)`
Yes (also you will get the token on mptcp create/established events)

**Comment by pak-ji** [comment]
@VenkateswaranJ  Thank you so much :)

**Comment by matttbe** [comment]
Hi,

Typically, you get tokens by listening to events, e.g. `MPTCP_EVENT_CREATED` → a new MPTCP connection has been created, the token (and more) is provided.

Note that in `/proc/net/mptcp_net/mptcp`, the token is only readable by the root user.

**Comment by pak-ji** [comment]
@matttbe  Thank you so much :)
