### ISSUE TITLE
MPTCP Netlink API Question)

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#438]
Issues : https://github.com/multipath-tcp/mptcp/issues/437
ADD_ADDR signal sent successfully. Thank you for the above link advice.

However, I face a different problem.
The problem is the "MPTCP_CMD_SUB_CREATE" command.
this command required rem_id.
> <pre>*   - MPTCP_CMD_SUB_CREATE: token, family, loc_id, rem_id, daddr4 | daddr6,
> *                           dport [, saddr4 | saddr6, sport, backup, if_idx]
> *       Create a new subflow. </pre>

But I couldn't get the rem_id.

Qustion) 
How can the client get the rem_id? 
Should the client wait for the event(MPTCP_EVENT_ANNOUNCED)?

**Comment by VenkateswaranJ** [comment]
`Should the client wait for the event(MPTCP_EVENT_ANNOUNCED)?`
Yes (As far as I know, that's the only safe way to get the remote address and ID).
The address and ID needs to be announced from remote side before executing MPTCP_CMD_SUB_CREATE.

Note: The ID should be unique within the MPTCP connection.

**Comment by pak-ji** [comment]
> `Should the client wait for the event(MPTCP_EVENT_ANNOUNCED)?`
> Yes (As far as I know, that's the only safe way to get the remote address and ID).
> The address and ID needs to be announced from remote side before executing MPTCP_CMD_SUB_CREATE.
> 
> Note: The ID should be unique within the MPTCP connection.

Thanks :)
