### ISSUE TITLE
changing MPTCP congestion control algorithem by modprobe

### ISSUE THREAD

**Issue by basrahd** [multipath-tcp/mptcp#444]
Dear All
Can I use the following command **modprobe mptcp_olia** instead of **syctl -w net.ipv4.tcp_congestion_control=olia** . If I use **modprobe mptcp_olia** in mininet host then I issue the command  **iperf3** to calculate throughput, Does that mean that throughput belongs to olia not to default CCA (cubic)?.

when I use mininet host to change CCA through **syctl -w net.ipv4.tcp_congestion_control=olia**  , I experienced the error ( sysctl: cannot stat  /proc/sys/net/ipv4.tcp_congestion_control: No such
 file or directory). I think that MPTCP works correctly with terminal client in kernel  but when I use **mininet host** I had the above mistake. 

Briefly: can I use **modprobe mptcp_olia** instead of s**ysctl -w  net.ipv4.tcp_congestion_control=olia in mininet host** in mininet host?. 
Best Regards

**Comment by matttbe** [comment]
Hello,

It seems we forgot about this question. I think you need both: first `modprobe` to have the cc in `net.ipv4.tcp_available_congestion_control` (and `net.ipv4.tcp_allowed_congestion_control`?), then changing `sysctl net.ipv4.tcp_congestion_control`
I guess you need to change the sysctl except maybe if `olia` is set as the default one somehow?

You can use `ss -ti` to check which TCP CC is in use.

Do you mind if I close this ticket?

**Comment by basrahd** [comment]
I appreciate your efforts.
