### ISSUE TITLE
What is default packet scheduler?

### ISSUE THREAD

**Issue by pak-ji** [multipath-tcp/mptcp#445]
What is default packet scheduler in MPTCP v0.95 ??
is it Low-Latency?? (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8584135)

**Comment by matttbe** [comment]
Hello,

> What is default packet scheduler in MPTCP v0.95 ??

It is still the low RTT one.
I guess in the paper you mention, they developed another packet scheduler they didn't upstream.

In our tree, we have: default (lowest RTT first), round-robin, redundant and Earliest Completion First (ECF). Is it one of them?

**Comment by matttbe** [comment]
(feel free to close this ticket if it answers your question)

**Comment by pak-ji** [comment]
Thanks :)

**Comment by pak-ji** [comment]
I'm sorry to reopen it.
Where can I see the document about Lowest RTT First?

**Comment by matttbe** [comment]
>  Where can I see the document about Lowest RTT First?

It is explained in a few papers -- even the one you pointed I think -- as it is the default one but I think the first one describing this is this one: https://dl.acm.org/doi/abs/10.1145/2630088.2631977

**Comment by pak-ji** [comment]
thanks :)
