### ISSUE TITLE
Issue while creating RPM package 

### ISSUE THREAD

**Issue by sdntechforum** [multipath-tcp/mptcp#447]
Hi All,

Anyone faced this error while building the RPM package, I am trying to find more info about this error - 

[admin@bn16-90 mptcp-mptcp_v0.96]$ make rpm-pkg
scripts/kconfig/conf  --syncconfig Kconfig

*** Error during sync of the configuration.

make[2]: *** [scripts/kconfig/Makefile:73: syncconfig] Error 1
make[1]: *** [Makefile:590: syncconfig] Error 2
Makefile:678: include/config/auto.conf.cmd: No such file or directory
make: *** [Makefile:696: include/config/auto.conf.cmd] Error 2
make: *** Deleting file 'include/config/auto.conf.cmd'

**Comment by matttbe** [comment]
Hi,

Strange but I'm sorry, I don't know exactly what's wrong. It looks like there is an issue with the kernel config. We didn't modify this part in this fork, so it looks like a "generic Linux kernel compilation error".
I hope you don't mind to close this issue then.

Do you have the same issue with just `make`? No complains with `make menuconfig`?
If no, maybe best to look for help elsewhere, maybe on [Linux Questions](https://www.linuxquestions.org/questions/linux-kernel-70/)

Please share the solution here once it is fixed to help others facing the same issue later.
