### ISSUE TITLE
package download issue

### ISSUE THREAD

**Issue by aminssl** [multipath-tcp/mptcp#450]
Hi All,
The links to Debian and RPM packages on binary.com is not working.
for example the following link forwards me to jfrog website !?
https://bintray.com/multipath-tcp/mptcp_deb/mptcp/v0.95.1

does anyone else has the same issue ?

BR.
Amin.

**Comment by VenkateswaranJ** [comment]
Hi,

Repositories hosted on binary.com is no longer available. You can find the latest packages here https://github.com/multipath-tcp/mptcp/releases
It's also updated on the mptcp website https://multipath-tcp.org/pmwiki.php/Users/RPM
