### ISSUE TITLE
Compile to ARM64

### ISSUE THREAD

**Issue by eackkk** [multipath-tcp/mptcp#458]
Hi, does mptcp support arm64 architecture? I downloaded the mptcp 0.94.7  and tried to compile it into aarch64 architecture, but I found that there is no in the .config file:
CONFIG_MPTCP=y
CONFIG_INET_MPTCP_DIAG=y
CONFIG_MPTCP_IPV6=y
only:
CONFIG_DEFAULT_MPTCP_PM="default"
There are a small number of mptcp related strings in the compiled vmlinux, but I am not sure whether the .config display is normal
When I compile menuconfig with arm64, no MPTCP related options are found

**Comment by matttbe** [comment]
Hi,

Did you follow steps from http://multipath-tcp.org/pmwiki.php/Users/DoItYourself ?

> configure the Kernel by doing make xconfig or make menuconfig and enable MultiPath TCP:
>
> * You cannot set IPv6 as a module. Either compile it into the kernel, or disable it.
> * enable MPTCP protocol (Networking support -> Networking options -> TCP/IP networking -> MPTCP protocol (MPTCP)) (if you cannot find that checkbox, then you have not correctly disabled one of the above options)
> * (...)

Maybe one parent option (Networking support -> Networking options -> TCP/IP networking) is not enabled. Which "defconfig" did you use? Or are you starting from a blank .config?

    make ARCH=arm64 defconfig
    make ARCH=arm64 menuconfig

**Comment by eackkk** [comment]
Yes, I compiled it in the following way:
make CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 defconfig
make CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 menuconfig
But there is no option for mptcp：
![Screenshot_20211215_114937](https://user-images.githubusercontent.com/73926435/146120179-878b49b7-b306-4d49-bf63-8ea39152145f.png)

**Comment by eackkk** [comment]
Thank you for your reply, I found the answer at http://multipath-tcp.org/pmwiki.php/Users/DoItYourself
I need to disable IPv6 or compile it into the kernel
