### ISSUE TITLE
Amazon AWS MPTCP

### ISSUE THREAD

**Issue by aminssl** [multipath-tcp/mptcp#469]
Dear All,
I wanted to setup MPTCP enabled VM in AWS EC2 and found the following instruction in MPTCP website:
1- https://multipath-tcp.org/pmwiki.php/Users/AWSGCE
 --- I couldn't find the "MPTCP-v0.92" or any other versions AMI in Amazon community AMIs or any other places like Market Place  at all, I checked all of the mentioned region and there was no success.

2- https://multipath-tcp.org/pmwiki.php/Users/AmazonEC2
--- as this instruction is based on ubuntu 11 !!!! i didn't went through it because there is no date of publish for this instruction and kernel patching in AWS changes time by time.

anybody have any handy instruction for how to instantiate a MPTCP enabled VM in EC2? 
 I also tried Amazon Linux 2 (https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/)as it says it has MPTCP built in,  but couldn't have multipath connectivity yet. 

Any suggestion or advice?

BR.
Amin.

**Comment by matttbe** [comment]
Hi Amin,

Linux Kernel >= 5.6 have a different implementation, please see https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations

If you want the MPTCP out-of-tree kernel on AWS, you probably need to install a Fedora-like or Debian/Ubuntu-like distribution and install a new kernel from our Releases page and reboot on this new kernel. But I didn't try.

I'm closing this issue as it is a duplicated of #431.
