### ISSUE TITLE
Installing MPTCP in ubuntu 20.04 (linux v5.4).

### ISSUE THREAD

**Issue by elhachi** [multipath-tcp/mptcp#477]
Hello,
Could you please suggest to me the right way to install mptcp in ubuntu 20.04 (Linux version 5.4)? I tried to follow this tutorial (https://gist.github.com/brandonheller/2730049) but it gave me an error, and since I'm a beginner in Linux I couldn't get my head around the official documentation (https://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP?) 
the error: gpg: no valid openpgp data found.
Thank you so much for your help.

**Comment by matttbe** [comment]
Hello,

> I tried to follow this tutorial (https://gist.github.com/brandonheller/2730049) but it gave me an error

Please don't use it, it is from 10 years ago.

Instead, the easier solution is to install the .deb of the last release, e.g.: https://multipath-tcp.org/pmwiki.php/Users/AptRepository
(then reboot and select the new kernel in the list in Grub before booting)

Or compile it yourself, that's not difficult but it is longer: https://multipath-tcp.org/pmwiki.php/Users/DoItYourself

**Comment by obonaventure** [comment]
Or upgrade to ubuntu 22.04 and you'll keep MPTCP immediately
