### ISSUE TITLE
MPTCP is enabled but not working

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp#483]
Hello there,

first of all, thank you o much for the great protocol.

I have installed mptcp in Ubuntu 22 and, sysctl net.mptcp.enabled is returning 1, but I can not see mptcp in uname -a, and in the net/mptcp folder threre are only five files. What can be wrong? Would you please help me.

Thanks a lo

**Comment by matttbe** [comment]
Hello,

Ubuntu 22.04 comes with a newer kernel containing a re-implementation of MPTCP.
This implementation had to be different to be accepted in the vanilla/upstream kernel. Some features are still missing, the work is in progress. You can follow the development there: https://github.com/multipath-tcp/mptcp_net-next

Please check this wiki page to know the different between the "out-of-tree" kernel (this project) and the upstream one (the one coming with Ubuntu 22.04): https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations=

You can still install an older kernel and get the out-of-tree implementation but best is probably to check if the upstream one suite you, open ticket/send patch if not and if it is really blocking, switch to the out-of-tree kernel.

I hope you don't mind if I close this ticket as the "issue" is not with this kernel.
