### ISSUE TITLE
Setting Roundrobin Scheduler

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp#485]
Hello

I hope you are doing well.

I am trying to test different schedulers when I am using:
sudo sysctl net.mptcp.mptcp_scheduler=default
or
sudo sysctl net.mptcp.mptcp_scheduler=redundant
everything is fine but when I use:
sudo sysctl net.mptcp.mptcp_scheduler=roundrobin
I encounter the following error:
sysctl: setting key "net.mptcp.mptcp_scheduler": No such file or directory
How can I fix this error?

Thanks a lot

**Comment by matttbe** [comment]
Did you compile this roundrobin packet scheduler?

  grep MPTCP_ROUNDROBIN /boot/config-$(uname -r)

**Comment by rezapoorzare1** [comment]
Thanks for the response.
It seems that it is not included. how can I compile MPTCP_ROUNDROBIN and add it to the mptcp implementation?

**Comment by matttbe** [comment]
How did you install your kernel? By compiling it yourself or by installing packages?

**Comment by rezapoorzare1** [comment]
By compiling myself.

**Comment by matttbe** [comment]
Then you need to enable this option (`make menuconfig`, then search for `MPTCP_ROUNDROBIN` with `/` key) before re-compiling and re-installing the kernel.

Feel free to re-open this ticket if after all of that you still cannot enable this packet scheduler
