### ISSUE TITLE
MPTCP Servers

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp#486]
Hello,
I hope you are doing well.
Is it possible for you to introduce numerous websites and servers that are supporting MPTCP? We want to compare page load time on many websites by deploying MPTCP and without it.
Thanks a million

**Comment by matttbe** [comment]
Hello,

A few websites are using MPTCP but I don't know any list.
You can maybe contact people behind https://mptcp.io if they have a list.

Many scientific papers used an MPTCP proxy between the client and the server to add MPTCP support, e.g. https://inl.info.ucl.ac.be/system/files/ieee_communications2016.pdf (but there are plenty others)

**Comment by rezapoorzare1** [comment]
Thanks a lot for the response

**Comment by obonaventure** [comment]
The most update paper analyzing the deployment of MPTCP is https://arxiv.org/pdf/2205.12138.pdf
