### ISSUE TITLE
VPS usage

### ISSUE THREAD

**Issue by mstrolo** [multipath-tcp/mptcp#487]
Hello all.

as I know you must have mptcp on the server side as well...

can the server handle only one client? can several clients connect to the same server but with different IP?

**Comment by matttbe** [comment]
Hello,

> as I know you must have mptcp on the server side as well...

That's correct.

> can the server handle only one client?

Yes, that's similar to TCP. e.g. the server can restrict to one client or close the listening socket after having accepted one connection.
In other words, that's the app that needs to take this decision and it is independent to MPTCP: socket options.

> can several clients connect to the same server but with different IP?

Of course. Also just like with TCP.

Feel free to close the ticket if this reply to your questions.

**Comment by mstrolo** [comment]
so if i want more the one client in the server what is the option?
docker?

**Comment by matttbe** [comment]
The configuration is the same as with regular TCP: your application can manage all of that when creating network sockets.

In other words, it depends on your application. If your app can only accept one client at a time, you need to start a few instances. Using docker can be a solution.
