### ISSUE TITLE
TCP_CORK option is not respected with multi subflows

### ISSUE THREAD

**Issue by redward** [multipath-tcp/mptcp#49]
With a single flow there is no problem. 
When we open a new subflow and put then the TCP_CORK on the main subflow, the ceilling time is not respected => it's sent immediately. 

Example from [tcp_cork_on_08.pkt](https://github.com/ArnaudSchils/packetdrill_mptcp/blob/master/gtests/net/packetdrill/examples/tests/tcp_headers/tcp_cork_on_08.pkt)

**Comment by cpaasch** [comment]
First, in tcp_cork_on_08.pkt:

You cannot do:

```
+0 setsockopt(6, SOL_TCP, TCP_CORK, [1], 4) = 0 
```

Socket 6 is not visiable to the user-space, so TCP_CORK cannot be set on it. Only the socket of the initial subflow is visible to userspace.

Then, lines:

```
+0.1  write(4, ..., 1440) = 1440 
+0 > P. 1:1441(1440) ack 1 <dss dack4=trunc_r64_hmac(key_a)+1 dsn4=trunc_r64_hmac(key_b)+1 >  sock(6)
+0.3 < . 1:1(0) ack 1441 win 225 <dss dack4=trunc_r64_hmac(key_b)+1441> sock(6)

+0  write(4, ..., 1440) = 1440
+0  > . 1:1001(1000) ack 1 <dss dack4=trunc_r64_hmac(key_a)+1 dsn4=trunc_r64_hmac(key_b)+1> sock(4)
```

This looks strange, you are expecting the same dsn4 (trunc_r64_hmac(key_b)+1) on both subflows.

Also, when I run this test, I get errors of "packet is not for expected socket".

If you want to make sure that a packet goes on a specific subflow, you have to introduce a delay-difference between the subflows. MPTCP will first select the subflow with the lowest RTT. In your case, both subflows experience during their 3-way handshake an RTT of 100ms. Additionally, to assure that the correct RTT-estimation is used, you should do "ip tcp_metrics flush" at the beginning of the script.

**Comment by cpaasch** [comment]
Closing, as the packetdrill-script does not makes a lot of sense.

Don't hesitate to reopen when the bug still produces with a corrected packetdrill-script.

**Comment by redward** [comment]
You were right for the DSN: dsn4=trunc_r64_hmac(key_b)+1 on sock (4) .It should be +1001 and not +1. 
With this, MPTCP is not correctly distributing the segments. 

There is a second issue, when we write a second time and expect it for the same segment as previous one (socket 4) it's not waiting for the ceiling time.

I've updated the test with your recommendations. 
The issue should be then re-opened.

**Comment by cpaasch** [comment]
Honestly, everything is working for me. What is the issue actually?

**Comment by redward** [comment]
Now it's working fine. Sorry for delay
