### ISSUE TITLE
MPTCP in ns3-mmWave or n3

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp#492]
Hello there,

I hope everything is good.
I am trying to test different variants of MPTCP in ns3-mmWave. I have tried to use DCE but it seems that is into working after Ubuntu 16.04 and I have encountered some errors. What is the solution for testing MPTCP? Is there another way of testing MPTCP in ns3 environments?

Thanks a lot

**Comment by matttbe** [comment]
Hi @rezapoorzare1 

I don't think there is an official support of MPTCP in NS3.
A Pull request was sent a few years ago but it has never been merged apparently: https://codereview.appspot.com/369810043/

Probably best to ask this question to the NS3 community.
Feel free to update this ticket if you have any news to share about this subject.

**Comment by rezapoorzare1** [comment]
Thanks a lot for the clarification.

**Comment by matttbe** [comment]
Closing the case but feel free to add new comments if there is anything new about this subject.

**Comment by vandit86** [comment]
Please, check this presentation : https://www.youtube.com/watch?v=rurAMkuWgaY
This framework allows you to test any version of MPTCP with any type of access technologies implemented in ns-3..  contact me if you want to read a full version of this paper, with a detailed configuration description..  
also, you can ask for support in official ns-3 mailing list : https://groups.google.com/g/ns-3-users/

**Comment by rezapoorzare1** [comment]
Thanks a lot Vandit.
How did you connect ns3 and the Linux kernel, so you had MPTCP in ns3?
Is it possible to share your code with me?

Thanks a lot

**Comment by vandit86** [comment]
> How did you connect ns3 and the Linux kernel, so you had MPTCP in ns3?

Yes. This way, one can use real MPTCP implementation in ns-3 scenarios. 

> Is it possible to share your code with me?

Some examples can be found in : https://github.com/vandit86/ns3-scratch

**Comment by rezapoorzare1** [comment]
Thanks a lot for your answer.
I will test and come back to you.
Thanks
