### ISSUE TITLE
Available schedulers 

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp#494]
Hello there,

I hope that you are doing well.
I have a question:
Is there a command line that shows the available schedulers? Like one for congestion control:
"sysctl net.ipv4.tcp_available_congestion_control"

Thanks a lot

**Comment by matttbe** [comment]
Hello,

No, I don't think there is any commands.
You can list all MPTCP modules maybe:

    ls /lib/modules/$(uname -r)/kernel/net/mptcp/*.ko

**Comment by rezapoorzare1** [comment]
Thanks a lot for your answer.
I appreciate the time you spend on answering issues, thanks a lot.

**Comment by matttbe** [comment]
:+1: I suggest to close this issue then!
