### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by abcdxyzk** [multipath-tcp/mptcp#501]
net/ipv6/tcp_ipv6.c
1164		if (!inet_rsk(req)->saw_mpc)
1165			inet_csk(newsk)->icsk_af_ops = &mptcp_v6_mapped;

need change to: ???
1164		if (inet_rsk(req)->saw_mpc)

**Comment by matttbe** [comment]
Hi,

Thank you for this bug report but can you share more details please: why is it a bug? on which kernel?

Did you see a strange behaviour linked to that? Or did you inspect the code and saw this that looks suspicious?

Do you want to propose a patch (or pull request)?

EDIT: https://github.com/multipath-tcp/mptcp/blob/a35e1901a49e800cddbb1c016ecd1dc09e0cb538/net/ipv6/tcp_ipv6.c#L1160-L1168
