### ISSUE TITLE
Failure of installation of MPTCP

### ISSUE THREAD

**Issue by sanjitbarik** [multipath-tcp/mptcp#508]
git clone --depth=1 git://github.com/multipath-tcp/mptcp.git              not link

**Comment by matttbe** [comment]
Hi

Indeed, you should use `https://` instead of `git://`.
Where did you see these instructions?

**Comment by matttbe** [comment]
I updated a few pages in from multipath-tcp.org.

Please report other issues with a link to the page showing the wrong URL.

Thanks

**Comment by sanjitbarik** [comment]
Dear friend
thank you
I have some issue on Multipath TCP installation .I will touch with you very soon

**Comment by sanjitbarik** [comment]
Dear friends
when I login to Ubuntu with Linux in MPTCP ,the following error occurs as
per the attached file. Pl. Pl.suggest..
thanks
