### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by sanjitbarik** [multipath-tcp/mptcp#510]
Please help me to rectify following error:
./scratch/mptcp_p_p.cc: In function ‘int main(int, char**)’:
../scratch/mptcp_p_p.cc:47:68: error: ‘MpTcpSocketBase’ was not declared in this scope
   47 |   Config::SetDefault("ns3::TcpL4Protocol::SocketType", TypeIdValue(MpTcpSocketBase::GetTypeId()));
      |                                                                    ^~~~~~~~~~~~~~~
../scratch/mptcp_p_p.cc:70:3: error: ‘MpTcpPacketSinkHelper’ was not declared in this scope
   70 |   MpTcpPacketSinkHelper sink("ns3::TcpSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), port));
      |   ^~~~~~~~~~~~~~~~~~~~~
../scratch/mptcp_p_p.cc:71:35: error: ‘sink’ was not declared in this scope; did you mean ‘link’?
   71 |   ApplicationContainer sinkApps = sink.Install(nodes.Get(1));
      |                                   ^~~~
      |                                   link
../scratch/mptcp_p_p.cc:75:3: error: ‘MpTcpBulkSendHelper’ was not declared in this scope
   75 |   MpTcpBulkSendHelper source("ns3::TcpSocketFactory", InetSocketAddress(Ipv4Address(i.GetAddress(1)), port));
      |   ^~~~~~~~~~~~~~~~~~~
../scratch/mptcp_p_p.cc:76:3: error: ‘source’ was not declared in this scope
   76 |   source.SetAttribute("MaxBytes", UintegerValue(0));
      |   ^~~~~~
../scratch/mptcp_p_p.cc:69:12: error: unused variable ‘port’ [-Werror=unused-variable]
   69 |   uint16_t port = 9;
      |            ^~~~
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/home/vboxuser/ns-allinone-3.35/ns-3.35/build'
Build failed
 -> task in 'mptcp_p_p' failed with exit status 1 (run with -v to display more information)

**Comment by matttbe** [comment]
Hi,

I'm sorry, I have to close this because this is not related to MPTCP kernel but rather to NS3 (and I don't know which version because I don't think MPTCP is supported in NS3).

Please report this issue where you downloaded the source code of this issue.
