### ISSUE TITLE
LIA,BALIA, OLIA congestion control

### ISSUE THREAD

**Issue by sanjitbarik** [multipath-tcp/mptcp#512]
Hi , 
 I am new  on the topic MPTCP, Can i get Ns3 coding of  LIA, BALIA and OLIA  congestion control
please help me.

**Comment by matttbe** [comment]
Hi,

I don't know, this GitHub repo is about an out-of-tree Linux kernel implementation, not about NS3. As far as I know, NS3 doesn't support MPTCP but there are some implementations available, probably made to write some papers, not sure if they are still alive.

Please report the issue to the people who have added MPTCP support in NS3, you will not find answers here and we cannot help for that.
