### ISSUE TITLE
enable MPTCP for Ns3

### ISSUE THREAD

**Issue by sanjitbarik** [multipath-tcp/mptcp#514]
hi 
you are doing well.
How to  enable MPTCP for NS3. Please suggest and guide me

**Comment by matttbe** [comment]
Hello,

> How to enable MPTCP for NS3. Please suggest and guide me

Sorry but the answer will be the same as in #512: I don't know, you are asking this question at the wrong place. This repository is about adding MPTCP capabilities in the Linux kernel, not about NS3.

**Comment by sanjitbarik** [comment]
ok sir
