### ISSUE TITLE
can not delete qdisk with handle 0

### ISSUE THREAD

**Issue by SANLANGWU** [multipath-tcp/mptcp#517]
When i use mptcp,my ubuntu report this question "can not delete qdisk with handle 0"

**Comment by matttbe** [comment]
That's an interesting statement. Do you know why?

**Comment by SANLANGWU** [comment]
I don't konw what happened,maybe we can discuss it together

**Comment by matttbe** [comment]
I don't know how we can know without sharing info about your system: Ubuntu version? Kernel version? How you compiled/installed the kernel and the OS? What else you did after the installation? Your environment? Where is the error coming from? More details about it (`dmesg` / `journalctl -k -b0`)? etc.

MPTCP kernel doesn't modify QDisk. But maybe the kernel is too old for the OS or a feature has not been enabled, etc.

**Comment by SANLANGWU** [comment]
Thank you.I meet this problem a few month ago and I delete my virtual machine for some reason.

**Comment by matttbe** [comment]
> I meet this problem a few month ago and I delete my virtual machine for some reason.

OK, then we can close this ticket.
