### ISSUE TITLE
The Directory for the Default Scheduler .c code

### ISSUE THREAD

**Issue by rezapoorzare** [multipath-tcp/mptcp#522]
Hello there, 

I have a simple question:
Where is the .c code for the default scheduler?
The others, for example, redundant are in the mptcp_v0.96/net/mptcp directory, but I cannot find the default scheduler code here?
Could you please guide me on this?

Thanks a million

**Comment by matttbe** [comment]
Hello

In `net/mptcp/mptcp_sched.c`, with other stuff.
https://github.com/multipath-tcp/mptcp/blob/612d75f01e95867dc94ac4f9f230f6f1bd09c9ac/net/mptcp/mptcp_sched.c#L503-L509

**Comment by rezapoorzare** [comment]
Thank you so much for your response, I appreciate it.

Have a very nice time

**Comment by matttbe** [comment]
Thanks, you too as well!
