### ISSUE TITLE
cannot configure MPTCP

### ISSUE THREAD

**Issue by youyouyoyo** [multipath-tcp/mptcp#66]
i have already installed MPTCP with apt-repository on unbutn 14.10,but i cannot find mptcp in proc/sys/net.

**Comment by cpaasch** [comment]
Unfortunately, there is no MPTCP-image available for Ubuntu 14.10. Only for 14.04.

Nevertheless, you should be able to boot on an MPTCP-kernel by entering grub during the bootup and selecting the MPTCP 3.14 kernel.
