### ISSUE TITLE
apt-repository for the newest v0.89-release cn a Ubuntu Trusty (14.04) 

### ISSUE THREAD

**Issue by youyouyoyo** [multipath-tcp/mptcp#67]
i install mptcp  following the public apt-repository for automated installation, first two steps are successfully done,but when i  install MPTCP with the following:
sudo apt-get update
sudo apt-get install linux-mptcp
there is always an error like this:can't find package linux-mptcp.

**Comment by cpaasch** [comment]
Are you on a 32-bit installation of Ubuntu?

If that's the case, then you cannot install MPTCP via the apt-repository because there are no 32-bit images available.

**Comment by youyouyoyo** [comment]
Thanks for your reply！ 
My ubuntu is 64-bit .And i have installed MPTCP via apt-repository.But i couldn't configure routing successfully.

**Comment by cpaasch** [comment]
Ok, as you managed to install MPTCP I close this issue.
