### ISSUE TITLE
about MPTCP VERISON

### ISSUE THREAD

**Issue by hongweishang** [multipath-tcp/mptcp#75]
We use MPTCP, but we can not get the MPTCP version. There is nothing about MPTCP verison in "dmesg". Is it defined in a source file? which file please?

**Comment by vvinothkumar** [comment]
You can find it in "/net/mptcp/mptcp_ctrl.c"

Line no 2573  pr_info("MPTCP: Stable release v0.89.5");

On Tue, Mar 31, 2015 at 9:32 AM, hongweishang notifications@github.com
wrote:

> We use MPTCP, but we can not get the MPTCP version. There is nothing about
> MPTCP verison in "dmesg". Is it defined in a source file? which file please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/multipath-tcp/mptcp/issues/75.

## 

## 

Vinoth

**Comment by hongweishang** [comment]
Thank you !

**Comment by cpaasch** [comment]
Although, if you boot on an MPTCP-kernel, it should be visible in the dmesg.
