### ISSUE TITLE
[question] about compiling MPTCP on Raspberry PI

### ISSUE THREAD

**Issue by T0mek** [multipath-tcp/mptcp#77]
Hi All,

Do you have any experiences with compiling the newest code release (0.89) on Raspberry PI?
I followed the 'success story' procedure described on:
https://github.com/raspberrypi/linux/issues/713
and it does not work for me - I am not able to boot kernel  - all what I get is 'rainbow screen'

I also followed suggestions from:
https://gist.github.com/davasiloaei/7301598
and all time it is the same.

Maybe you have any latest experiences and could give me some hints?
I would be very graceful for any help.

regards,
Tomek

**Comment by cpaasch** [comment]
Closing this issue.

**Comment by opensourcegeek** [comment]
@T0mek 0 did you get anywhere? I'm stuck with rainbow screen as well - I'm trying it on pi 3.

**Comment by T0mek** [comment]
Unfortunately not.  After long hours of investigations and struggles, I just stopped working on this.
However if you have any success with this topic, please share with us. 
Tomek.

**Comment by opensourcegeek** [comment]
@T0mek I'll see how far I can take it, I think merging pi fork with mptcp fork loses few things like I cannot find any device tree blobs specific to pi. I looked into it only briefly.
