### ISSUE TITLE
Question: Performing Backup mode operation

### ISSUE THREAD

**Issue by m4n1c22** [multipath-tcp/mptcp#79]
I have installed the latest linux kernel implementation of MPTCP in my two VM images. I have tried simulating the MPTCP modes of operation on my virtual machines by configuring the path managers. I am able to simulate Full Path mode. But I am not able to do the Back up mode operation. This is config I did with my machine:

VM1:
2 interfaces: eth0 (ipA1), eth1 (ipA2)

VM2:
2 interfaces: eth0(ipB1), eth1 (ipB2)

I am running iperf with one VM as client and other as a server. I have even configured the iproute2 tool which configures the backup mode. When I am setting the path manager as full mesh and say eth1 of VM1 as backup and runs the iperf I am getting data transmitted from ipA1 through eth1 (which is not supposed to happen ideally). Can you please help. Please tell me if it is something I am doing wrong from my side.

**Comment by cpaasch** [comment]
Can you please share a (short) packet-trace of this scenario?
The subflows should have the backup-bit set, thus we might start by looking for this one.

**Comment by cpaasch** [comment]
Am I right in the assumption that you use v0.89.2 and that the initial subflow goes over eth1? In that case, there is a bug that has been fixed by ef13cdbd842 (mptcp: Fix backup-mode on initial subflow) in the most recent stable version (v0.89.5).

**Comment by m4n1c22** [comment]
Yep. Thanks for replying. It is the same problem where the initial subflow
uses the eth1. I will try the new version and see if it works.

**Comment by cpaasch** [comment]
Thanks for the reply. Closing this issue here then.
