### ISSUE TITLE
MPTCP Coupled Congestion Control is not available in kernel configuration

### ISSUE THREAD

**Issue by ghost** [multipath-tcp/mptcp#80]
I got the source and I'm trying to compile the kernel by myself following the steps given in the main page but the option to add the MPTCP Coupled Congestion Control is not actually in the options, so I can't select it as Default Congestion Control for TCP. Even when I configure the options to show me all the options it didn't appear (I'm using gconfig). I don't know if it's already added to another option or something like that. The version I'm trying to install is MPTCP: Stable release v0.89.5. Thanks in advance!

**Comment by cpaasch** [comment]
Closing, as this is being discussed on the mailing-list.
