### ISSUE TITLE
Can't open(or use) another interface(wlan0) after disabling the first one using : ip link set dev eth0 multipath off

### ISSUE THREAD

**Issue by AnsEMU** [multipath-tcp/mptcp#81]
Hello
I am having a problem with implementing MPTCP, and I am not sure if I can identify the problem, I will start with giving information about my system and what I did in order to install MPTCP followed up with routing configurations.
.
.
-OS type : 64-bit.
-one network card with the motherboard so 2 ethernet cables can be conected. 
-in our first implementation we used one ethernet and a wireless and in the second one we used the two ethernet cables.

-after using : sudo nano /etc/lsb-release .  i get :
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
.
.
-also after using : dmesg | grep MPTCP . i get :
[    0.357941] MPTCP: Stable release v0.89.2
.
.
Now the work that was done : 
-root@ENES:/home/enes# route -n 
Kernel IP routing table 
Destination     Gateway         Genmask              Flags    Metric Ref        Use Iface 
0.0.0.0             10.10.0.1         0.0.0.0                  UG          0      0             0 eth0 
10.10.0.0         0.0.0.0             255.255.254.0      U             1      0             0 eth0 
172.20.10.0     0.0.0.0             255.255.255.240  U              9      0            0 wlan0 
root@ENES:/home/enes# ip rule add from 10.10.0.203 table 1 
root@ENES:/home/enes# ip rule add from 172.20.10.4 table 2 
root@ENES:/home/enes# ip route add 10.10.0.0/24 dev eth0 scope link table 1 
root@ENES:/home/enes# ip route add default via 0.0.0.0 dev eth0 table 1 
root@ENES:/home/enes# ip route add 172.20.10.0/24 dev wlan0 scope link table 2 
root@ENES:/home/enes# ip route add default via 0.0.0.0 dev wlan0 table 2 
root@ENES:/home/enes# ip route add default scope global nexthop via 0.0.0.0 dev eth0 
RTNETLINK answers: File exists 
root@ENES:/home/enes# ip rule show 
0:  from all lookup local 
32764:  from 172.20.10.4 lookup 2 
32765:  from 10.10.0.203 lookup 1 
32766:  from all lookup main 
32767:  from all lookup default 
root@ENES:/home/enes# ip route 
default via 10.10.0.1 dev eth0  proto static 
10.10.0.0/23 dev eth0  proto kernel  scope link  src 10.10.0.203  metric 1 
172.20.10.0/28 dev wlan0  proto kernel  scope link  src 172.20.10.4  metric 9 
root@ENES:/home/enes# ip route show table 1 
default dev eth0 
10.10.0.0/24 dev eth0  scope link 
root@ENES:/home/enes# ip route show table 2 
default dev wlan0 
172.20.10.0/24 dev wlan0  scope link 
root@ENES:/home/enes# apt-get install ncftp 
Reading package lists... Done 
Building dependency tree  
Reading state information... Done 
The following NEW packages will be installed: 
  ncftp 
0 upgraded, 1 newly installed, 0 to remove and 543 not upgraded. 
Need to get 589 kB of archives. 
After this operation, 1.287 kB of additional disk space will be used. 
Get:1 http://tr.archive.ubuntu.com/ubuntu/ trusty/universe ncftp amd64 2:3.2.5-1.1 [589 kB] 
Fetched 589 kB in 2s (236 kB/s)  
Selecting previously unselected package ncftp. 
(Reading database ... 195387 files and directories currently installed.) 
Preparing to unpack .../ncftp_2%3a3.2.5-1.1_amd64.deb ... 
Unpacking ncftp (2:3.2.5-1.1) ... 
Processing triggers for man-db (2.6.7.1-1) ... 
Setting up ncftp (2:3.2.5-1.1) ... 
update-alternatives: using /usr/bin/ncftp3 to provide /usr/bin/ncftp (ncftp) in auto mode 
root@ENES:/home/enes#
i also did this : 
oot@ENES:/home/enes# sysctl -w net.mptcp.mptcp_enabled=1 
net.mptcp.mptcp_enabled = 1 
root@ENES:/home/enes# sysctl -w net.mptcp.mptcp_checksum=0 
net.mptcp.mptcp_checksum = 0 
root@ENES:/home/enes# sysctl -w net.mptcp.mptcp_syn_retries=3 
net.mptcp.mptcp_syn_retries = 3 
root@ENES:/home/enes# sysctl net.mptcp.mptcp_path_manager=fullmesh  
net.mptcp.mptcp_path_manager = fullmesh
root@ENES:/home/enes# sysctl net.mptcp.mptcp_scheduler=default   
## net.mptcp.mptcp_scheduler = default 

> > now we installed ncftp and we connected to ftp://ftp.multipath-tcp.org later we used : get 1GB and we start downloading.
> > for network traffic monitoring we use : ifstat 
> > furthermore, the result for both implementations were the same
> >  while the file is being downloaded i tried to enable (using : sudo ip link set dev wlan0 multipath on)the second interface which is the second ethernet or wireless let us consider wireless....but nothing change it is not downloading to illustrate more, the load is not being shared (still zeros ).
> > .
> > .
> > i hope i was able to provide enough information to diagnose the problem.wish for a solution !!!! THANKS

**Comment by AnsEMU** [comment]
Also i can off the first interface with the command but i cant on it or on any other interface.

**Comment by cpaasch** [comment]
I'm not sure what the problem is you are facing.
Don't you see both interfaces being used? You see no traffic at all on the secondary interface? Maybe you can start by taking a packet-trace.

**Comment by AnsEMU** [comment]
we see only a traffic on one interface which is the default one that's when we start downloading the 1GB file,and when i use : uname -a  
i get : 
Linux ENES 3.14.0-89-mptcp #2 SMP Tue Sep 23 10:17:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AnsEMU** [comment]
also when we check the availability of mptcp on https://amiusingmptcp.com/ we get NO answer

**Comment by cpaasch** [comment]
This means that you have a middlebox on your path that is removing the MPTCP-options. You can check it with tracebox (http://tracebox.org).

**Comment by AnsEMU** [comment]
working on it ......

**Comment by AnsEMU** [comment]
after executing --> root@ENES:git clone https://github.com/tracebox/tracebox.git  finish successfully 
then 
root@ENES:/home/enes# cd tracebox/
then
root@ENES:/home/enes/tracebox# ./bootstrap.sh
Submodule 'noinst/libcrafter' (https://github.com/pellegre/libcrafter.git) registered for path 'noinst/libcrafter'
Submodule 'tests/tools/click' (https://github.com/bhesmans/click.git) registered for path 'tests/tools/click'
Cloning into 'noinst/libcrafter'...
remote: Counting objects: 2461, done.
remote: Total 2461 (delta 0), reused 0 (delta 0), pack-reused 2461
Receiving objects: 100% (2461/2461), 2.86 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (1700/1700), done.
Checking connectivity... done.
Submodule path 'noinst/libcrafter': checked out 'dc4d017e2502a734cac1d37e3b5dba346f0de5f0'
Cloning into 'tests/tools/click'...
remote: Counting objects: 81398, done.
remote: Total 81398 (delta 0), reused 0 (delta 0), pack-reused 81398
Receiving objects: 100% (81398/81398), 20.26 MiB | 2.37 MiB/s, done.
Resolving deltas: 100% (64944/64944), done.
Checking connectivity... done.
Submodule path 'tests/tools/click': checked out '81f20b46e58634445b0e6e3a05bbb72a3cb335ef'
./bootstrap.sh: 6: ./bootstrap.sh: autoreconf: not found

autoreconf: not found  ------> how to solve this ?

**Comment by obonaventure** [comment]
> ./bootstrap.sh: 6: ./bootstrap.sh: autoreconf: not found
> 
> autoreconf: not found ------> how to solve this ?

try

sudo apt-get install autoconf

if on ubuntu

**Comment by AnsEMU** [comment]
i tried : sudo apt-get install autoreconf    but it didn't work instead i tried : sudo apt-get install dh-autoreconf
and it worked 
but when doing the rest of the command : 
$ make
$ sudo make install
i get 
root@ENES:/home/enes/tracebox# make
make: **\* No targets specified and no makefile found.  Stop.
root@ENES:/home/enes/tracebox# sudo make install
make: **\* No rule to make target `install'.  Stop.
any idea ?

**Comment by oliviertilmans** [comment]
Hello,
As you did not have autoconf available when you ran bootstrap.sh, the script did not complete.
Run this before doing the make:

``` bash
autoreconf -i
./configure
```

Please also make sure you have the required build dependencies:
autotools automake libtool liblua-dev libpcap-dev libjson0 libjson0-dev

If you are still experiencing issues wrt. Tracebox afterwards, please open them on https://github.com/tracebox/tracebox/issues to make things easier to track.

**Comment by AnsEMU** [comment]
i think that went fine .... i will paste the results of this command 
$ tracebox -n -p IP/TCP/MSS/MPCAPABLE/WSCALE bahn.de
in  https://github.com/tracebox/tracebox/issues
please can you follow up with me !!!! thanks
