### ISSUE TITLE
Update mptcp

### ISSUE THREAD

**Issue by aygkhn** [multipath-tcp/mptcp#82]
Hello
I am using ubuntu 14.04 v0.89.2 but mptcp is not working. I wanna update v0.89.5.
How can i update v0.89.5. Can you help me please?

**Comment by obonaventure** [comment]
Hello

> I am using ubuntu 14.04 v0.89.2 but mptcp is not working. I wanna update
> v0.89.5.
> How can i update v0.89.5. Can you help me please?

It is unlikely that the problem that you observe is due to a kernel
version. See http://multipath-tcp.org/pmwiki.php/Users/AptRepository
for install notes.

**Comment by aygkhn** [comment]
I follow all step. I have two ethernet card. One is Realtek 10/100mb one is onboard 10/100.  But when i configure it doesnt work. Just eth0 works.

**Comment by obonaventure** [comment]
On 31/05/15 22:47, aygkhn wrote:

> I follow all step. I have two ethernet card. One is Realtek 10/100mb one
> is onboard 10/100. But when i configure it doesnt work. Just eth0 works.

try to follow the procedure described here

http://blog.multipath-tcp.org/blog/html/2014/10/30/testing_multipath_tcp.html?highlight=discard
