### ISSUE TITLE
Configure Scheduler roundrobin Mode and ACK for the second subflow TCP

### ISSUE THREAD

**Issue by djaneu** [multipath-tcp/mptcp#85]
Hello,
I installed MPTCP 0.89.2 version Ubuntu 14.04 LTS computer and when I try to configure the scheduler in roundrobin mode, the following message appears:
sysctl : setting key "net.mptcp.mptcp_scheduler" no such file or directory 

Command used : sudo sysctl -w net.mptcp.mptcp_scheduler=roundrobin

Should I upgrade to another version of MPTCP?

The other problem is in the use of MPTCP

The first sub-stream is okay, but at establishing the second flow connection, only the SYN / SYN-ACK part is performed. No ACK is returned by the client

Here are some picture to illustrate the problem

Global view
![bug_join_connection1](https://cloud.githubusercontent.com/assets/12947565/8225904/0d4e1b2a-159a-11e5-9f2a-82a6ac142c56.png)

SYN for the second TCP subflow
![bug_join_2](https://cloud.githubusercontent.com/assets/12947565/8225905/12c8a156-159a-11e5-9743-38936a45efdd.png)

SYN-ACK for the second TCP subflow
![bug_mptcp3](https://cloud.githubusercontent.com/assets/12947565/8225916/51fb2a42-159a-11e5-8ada-df8014da3fa9.png)

Any ideas?

Thanks

**Comment by gdetal** [comment]
I'll let @cpaasch answer your first question as he is the one generating the ubuntu packages. However, it is most likely that the RR scheduler is not built in these images.

For the second part, I guess that this is a packet trace on the server. Can you do the same on the client to see whether the SYN/ACK reached the client. If it is dropped in the network, the client will re-transmit the SYN as seen in your capture.

**Comment by djaneu** [comment]
For the second part, yes it was the view from the server.
I just see the view from the client. The result is identical. SYN-ACK packet is received from the client.

View from the client :
![1](https://cloud.githubusercontent.com/assets/12947565/8227291/74ed12a2-15a6-11e5-8421-61213d357629.png)

**Comment by cpaasch** [comment]
@djaneu : Concerning the Ubuntu packages, indeed the round-robin scheduler is not compiled in. However, I do no more maintain the Ubuntu packages. Would be great if somebody could pick this up and maybe host them on launchpad.

**Comment by cpaasch** [comment]
And, can you show the content (TCP-options) of the SYN/ACK on the client-side?

**Comment by djaneu** [comment]
Content (TCP-options of the SYN/ACK

![a](https://cloud.githubusercontent.com/assets/12947565/8248091/30f2570a-165b-11e5-8436-8dbe1c075dff.JPG)

**Comment by cpaasch** [comment]
The SYN/ACK looks good.

Can you do a "nstat" before and after the experiment and show the output of the one after it?

Thanks!

**Comment by djaneu** [comment]
After recheck the configuration on my workstation, I found the source of the problem,

After a restart, the configuration of routing is lost on my computer, when the configuration is ok, the ACK is present and it's work.

Wireshark view from the client with TCP filter
![ok](https://cloud.githubusercontent.com/assets/12947565/8300835/3e5921a4-1989-11e5-8888-c501cfca92fb.png)

**Comment by cpaasch** [comment]
Good! So, everything is working now.

**Comment by liulijie** [comment]
hello, I have the same question as you. what is   the meaning of the sentence  "I found the source of the problem," ? 

![screenshot from 2015-10-27 19 44 44](https://cloud.githubusercontent.com/assets/13060467/10755792/3fd4d632-7ce3-11e5-8774-3809c08932b7.png)

![mp](https://cloud.githubusercontent.com/assets/13060467/10755936/2b479a8c-7ce4-11e5-80df-5279a9770627.png)
I  had did  this, why i had the question.

![screenshot from 2015-10-27 19 48 06](https://cloud.githubusercontent.com/assets/13060467/10755860/aed25e2e-7ce3-11e5-906d-6bfad7ddfc74.png)

Thank you very much!

**Comment by liulijie** [comment]
Thank you. I am OK.  insmod /lib/modules/4.1.0/kernel/net/mptcp/mptcp_rr.ko 
linux and mptcp are new to me.

**Comment by aalnajjar** [comment]
Hi all,
I am new to MPTCP. I've installed it from multipath-tcp.org by recompiling the kernel. I've used the same MPTCP configuration on the client and the server, and noticed there is no difference in terms of performance when using the Default and Roindrobin scheduler algorithms.
Is that correct or there is something should be done to get different performance with those algorithms?

**Comment by anandianjali** [comment]
Hi,
I installed MPTCP 0.90 version in Ubuntu 14.04 LTS. I want to try the scheduler round robin as I am currently working on analysing the performance of various schedulers in video streaming. After making the scheduler as round robin am getting the same behaviour as that of default scheduler. Kindly suggest what could I do to rectify this?
