### ISSUE TITLE
mptcp patch for ubuntu

### ISSUE THREAD

**Issue by ak47for** [multipath-tcp/mptcp#89]
We want to compile the MPTCP source on ubuntu.
Is there patch for ubuntu?

**Comment by PhSchmitt** [comment]
what do you mean by "patch" ? The source can be compiled on ubuntu using the usual kernel compile settings.
If you have further questions, I recommend asking on the mailing-list (mptcp-dev@listes.uclouvain.be) where you'll most likely get more (and quicker) answers than here
