### ISSUE TITLE
Version number not updated in kernel messages, and need to be more centralized & accessible

### ISSUE THREAD

**Issue by MoffTigriss** [multipath-tcp/mptcp#90]
Freshly compiled from 0.90 branch

``` console
dmesg | grep -i mptcp
[    0.408001] MPTCP: Stable release v0.89.0-rc
```

Seem (net/mptcp/) mptcp_ctrl.c need a little update. The version is hardcoded on [line 2638](https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.90/net/mptcp/mptcp_ctrl.c#L2638) (Aug 3, 2015).

[Issue #57](https://github.com/multipath-tcp/mptcp/issues/57) is similar, but on the fullmesh module.

MPTCP need something centralized to show the current version, and making it easy to read if possible.

**Comment by cpaasch** [comment]
Hello,

the v0.90 branch has not yet been "officially" released. Feature-work has still been ongoing in this branch. Once we tag this as the new stable release, we will bump the version in mptcp_ctrl.c.

Cheers,
Christoph

**Comment by zorun** [comment]
It seems this issue is still there with v0.91:

```
[    0.000000] Linux version 4.1.26-d5a1069-mptcp (builduser@builder) (gcc version 6.1.1 20160602 (GCC) ) #1 SMP PREEMPT Sat Jun 18 21:44:32 CEST 2016
[    0.546011] MPTCP: Stable release v0.89.0-rc
```

**Comment by cpaasch** [comment]
Argh... I knew I forgot something ... :)
