### ISSUE TITLE
Path manager (ndiffports) ports allocation

### ISSUE THREAD

**Issue by GinesGarcia** [multipath-tcp/mptcp#98]
Hi,
how mptcp manages port allocation when we are using ndiffports? random allocation? is there any way to assign ports directly to each flow in order to be able to control them?

Thanks!

**Comment by cpaasch** [comment]
It does it based on the Linux Kernel source-port selection algorithm, which chooses a random base on a src/dst-basis and then uses monotonically increasing port numbers.

**Comment by cpaasch** [comment]
Oh, and no, it is not currently possible to select the source-ports of the subflows.

**Comment by GinesGarcia** [comment]
Ok thanks!!!
